Repository hmcts/et-sya-frontend, pull requests merged in 2022-05, with the labels that each got.

#217 Code coverage
  package.json
  src/main/controllers/DesiredClaimOutcomeController.ts
  src/test/functional/features/etClaimForSomeoneElse.js
  src/test/functional/features/etMultipleClaimsForMyself.js
  src/test/functional/features/etpage.js
  src/test/functional/features/returnToExistingClaim.js
  src/test/unit/controller/CompensationOutcomeController.test.ts
  src/test/unit/controller/DesiredClaimOutcomeController.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/controller/NoticePayController.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-217

#220 RET-1441: add the exit survey to the claim submit page.
  src/main/assets/scss/main.scss
  src/main/assets/scss/utilities/_borders.scss
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/views/claim-submitted.njk
Labels: ns:et, prd:et, rel:et-sya-pr-220

#222 Test automation for ret 1441
  src/test/functional/features/etStepToMakeYourClaim.js
Labels: ns:et, prd:et, rel:et-sya-pr-222

#221 1521: change label to 'save as draft' and update the '/are-you-still-working' page
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/new-account-landing.json
  src/main/resources/locales/en/translation/still-working.json
  src/test/functional/features/checkAndSubmitCliam.js
  src/test/functional/features/etStepToMakeYourClaim.js
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/compensation-outcome.test.ts
  src/test/unit/views/date-of-birth.test.ts
  src/test/unit/views/desired-claim-outcome.test.ts
  src/test/unit/views/new-account-landing.test.ts
  src/test/unit/views/past-employer.test.ts
  src/test/unit/views/start-date.test.ts
  src/test/unit/views/still-working.test.ts
  src/test/unit/views/summarise-your-claim.test.ts
  src/test/unit/views/telephone-number.test.ts
  src/test/unit/views/tribunal-recommendation-outcome.test.ts
  src/test/unit/views/update-preference.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-221

#225 Ret 1522 update validation messages for past-employer and still-working
  src/main/resources/locales/en/translation/past-employer.json
  src/main/resources/locales/en/translation/still-working.json
Labels: ns:et, prd:et, rel:et-sya-pr-225

#223 Ret 1759
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/oidc/index.ts
  src/main/services/CaseService.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-223

#226 accessibility changes
  package.json
  src/test/a11y/a11y.ts
Labels: ns:et, prd:et, rel:et-sya-pr-226

#230 RET-865 integrate Fortify scan stage in Jenkins pipeline
  Jenkinsfile_nightly
  package.json
  src/test/java/.gitignore
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
  src/test/java/settings.gradle
Labels: ns:et, prd:et, rel:et-sya-pr-230

#231 RET-865 integrate Fortify into nightly Jenkins pipeline
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-231

#232 Ret 865 integrate fortify pipeline
  src/test/java/gradlew
Labels: ns:et, prd:et, rel:et-sya-pr-232

#235 Attempt to fix Fortify Scan stage in nightly build
  Jenkinsfile_nightly
  charts/et-sya/Chart.yaml
  charts/et-sya/values.aat.template.yaml
  charts/et-sya/values.preview.template.yaml
  charts/et-sya/values.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-235

#234 Ret 1727v2
  src/main/controllers/NoticeEndController.ts
  src/main/controllers/NoticeLengthController.ts
  src/main/resources/locales/en/translation/notice-end.json
  src/main/resources/locales/en/translation/notice-length.json
  src/main/views/notice-length.njk
  src/test/functional/features/checkyourAnswers.js
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/routes/notice-end.test.ts
  src/test/unit/controller/NoticeEndController.test.ts
  src/test/unit/views/notice-length.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-234

#236 Ret 1727v2
  src/main/controllers/NoticeEndController.ts
  src/main/resources/locales/en/translation/notice-end.json
  src/main/views/notice-end.njk
  src/test/unit/views/notice-end.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-236

#238 Updated Jenkins file to sync with 'perftest' environment
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-sya-pr-238

#228 RET 1026 - link to generate the 'Save a copy' PDF
  src/main/controllers/DownloadClaimController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/routes/routes.ts
  src/main/services/CaseService.ts
  src/main/views/claim-submitted.njk
  src/test/unit/controller/DownloadClaimController.test.ts
  src/test/unit/mocks/mockResponse.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-228

#241 test refactor for authorized pages
  src/test/functional/features/authPage.js
  src/test/functional/features/checkAndSubmitCliam.js
  src/test/functional/features/checkyourAnswers.js
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/functional/features/empDetailsWhileWorking.js
  src/test/functional/features/employeeGotNewJob.js
  src/test/functional/features/employeeNotWorking.js
  src/test/functional/features/etSingleClaimForMyself.js
  src/test/functional/features/etStepToMakeYourClaim.js
  src/test/functional/features/etpage.js
  src/test/functional/features/placeOfWork.js
  src/test/functional/features/returnToExistingClaim.js
Labels: ns:et, prd:et, rel:et-sya-pr-241
