Repository hmcts/et-sya-frontend, pull requests merged in 2022-06, with the labels that each got.

#243 Task List 1: Reasonable Adjustments Skeleton Pages (Restructure)
  src/main/controllers/ComfortableController.ts
  src/main/controllers/CommunicatingController.ts
  src/main/controllers/DocumentsController.ts
  src/main/controllers/PersonalDetailsCheckController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/controllers/SupportController.ts
  src/main/controllers/TravelController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/comfortable.json
  src/main/resources/locales/en/translation/communicating.json
  src/main/resources/locales/en/translation/documents.json
  src/main/resources/locales/en/translation/reasonable-adjustments.json
  src/main/resources/locales/en/translation/support.json
  src/main/resources/locales/en/translation/tasklist-check.json
  src/main/resources/locales/en/translation/travel.json
  src/main/routes/routes.ts
  src/main/views/reasonable-adjustments.njk
  src/main/views/tasklist-check.njk
  src/test/routes/comfortable.test.ts
  src/test/routes/communicating.test.ts
  src/test/routes/documents.test.ts
  src/test/routes/personal-details-check.test.ts
  src/test/routes/support.test.ts
  src/test/routes/travel.test.ts
  src/test/unit/controller/ComfortableController.test.ts
  src/test/unit/controller/CommunicatingController.test.ts
  src/test/unit/controller/DocumentsController.test.ts
  src/test/unit/controller/PersonalDetailsCheckController.test.ts
  src/test/unit/controller/ReasonableAdjustmentsController.test.ts
  src/test/unit/controller/SupportController.test.ts
  src/test/unit/controller/TravelController.test.ts
  src/test/unit/views/comfortable.test.ts
  src/test/unit/views/communicating.test.ts
  src/test/unit/views/documents.test.ts
  src/test/unit/views/reasonable-adjustments.test.ts
  src/test/unit/views/support.test.ts
  src/test/unit/views/tasklist-check.test.ts
  src/test/unit/views/travel.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-243

#240 Ret 1725
  dump.rdb
  src/main/components/form/validator.ts
  src/main/controllers/AverageWeeklyHoursController.ts
  src/main/controllers/BenefitsController.ts
  src/main/controllers/NoticeLengthController.ts
  src/main/controllers/NoticePeriodController.ts
  src/main/controllers/NoticeTypeController.ts
  src/main/controllers/PensionController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/average-weekly-hours.json
  src/main/resources/locales/en/translation/benefits.json
  src/main/resources/locales/en/translation/notice-length-months.json
  src/main/resources/locales/en/translation/notice-length-weeks.json
  src/main/resources/locales/en/translation/notice-length.json
  src/main/resources/locales/en/translation/notice-period-no-longer-working.json
  src/main/resources/locales/en/translation/notice-period-working.json
  src/main/resources/locales/en/translation/notice-period.json
  src/main/resources/locales/en/translation/notice-type.json
  src/main/resources/locales/en/translation/pay.json
  src/main/resources/locales/en/translation/pension.json
  src/main/views/notice-length.njk
  src/main/views/notice-period.njk
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/functional/features/empDetailsWhileWorking.js
  src/test/routes/notice-length.test.ts
  src/test/routes/notice-type.test.ts
  src/test/routes/pension.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/BenefitsController.test.ts
  src/test/unit/views/notice-length.test.ts
  src/test/unit/views/notice-period.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-240

#245 Ret 1796
  charts/et-sya/Chart.yaml
  charts/et-sya/values.aat.template.yaml
  charts/et-sya/values.preview.template.yaml
  charts/et-sya/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  package.json
  src/main/app.ts
  src/main/controllers/CompensationOutcomeController.ts
  src/main/controllers/DesiredClaimOutcomeController.ts
  src/main/controllers/PcqController.ts
  src/main/controllers/TribunalRecommendationOutcomeController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/helmet/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/pcq/createToken.ts
  src/main/pcq/index.ts
  src/main/routes/routes.ts
  src/test/routes/compensation-outcome.test.ts
  src/test/routes/desired-claim-outcome.test.ts
  src/test/routes/notice-length.test.ts
  src/test/routes/notice-type.test.ts
  src/test/routes/pension.test.ts
  src/test/routes/tribunal-recommendation-outcome.test.ts
  src/test/routes/video-hearings.test.ts
  src/test/unit/controller/CompensationOutcomeController.test.ts
  src/test/unit/controller/DesiredClaimOutcomeController.test.ts
  src/test/unit/controller/PcqController.test.ts
  src/test/unit/controller/TribunalRecommendationOutcomeController.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/utils/createToken.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-245

#244 idam automation changes for accessibility pages
  Jenkinsfile_CNP
  package.json
  src/test/a11y/a11y.ts
Labels: ns:et, prd:et, rel:et-sya-pr-244

#249 RET-1514 Reasonable Adjustments - Validation & Errors
  src/main/controllers/PersonalDetailsCheckController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/resources/locales/en/translation/reasonable-adjustments.json
  src/main/resources/locales/en/translation/tasklist-check.json
  src/main/resources/locales/en/translation/update-preference.json
  src/main/views/reasonable-adjustments.njk
  src/main/views/tasklist-check.njk
  src/test/unit/controller/ReasonableAdjustmentsController.test.ts
  src/test/unit/views/reasonable-adjustments.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-249

#257 RET-1888 issues 5-6
  src/main/assets/scss/main.scss
  src/main/resources/locales/en/translation/notice-end.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/template.njk
  src/test/routes/video-hearings.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-257

#258 Update Helm chart config setting
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-258

#260 Update Helm chart repository dependency
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-260

#251 Ret 327
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/case.ts
  src/main/definitions/definition.ts
  src/main/modules/oidc/index.ts
  src/main/resources/locales/en/translation/type-of-claim.json
  src/test/functional/features/etSingleClaimForMyself.js
  src/test/routes/steps-to-making-your-claim.test.ts
  src/test/unit/controller/PastEmployerController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
  src/test/unit/views/type-of-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-251

#255 Ret 349
  src/main/components/form/validator.ts
  src/main/controllers/GenderDetailsController.ts
  src/main/resources/locales/en/translation/gender-details.json
  src/test/routes/gender-details.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/views/gender-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-255

#263 Ret 349
  src/main/resources/locales/en/translation/gender-details.json
Labels: ns:et, prd:et, rel:et-sya-pr-263

#259 RET-1728 - Employment Notice Period Validation
  dump.rdb
  src/main/components/form/validator.ts
  src/main/controllers/BenefitsController.ts
  src/main/controllers/DobController.ts
  src/main/controllers/JobTitleController.ts
  src/main/controllers/NoticeEndController.ts
  src/main/controllers/NoticeLengthController.ts
  src/main/controllers/NoticePayController.ts
  src/main/controllers/NoticeTypeController.ts
  src/main/controllers/PensionController.ts
  src/main/controllers/StartDateController.ts
  src/main/controllers/StillWorkingController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/constants.ts
  src/main/definitions/dates.ts
  src/main/resources/locales/en/translation/average-weekly-hours.json
  src/main/resources/locales/en/translation/benefits.json
  src/main/resources/locales/en/translation/date-of-birth.json
  src/main/resources/locales/en/translation/notice-end.json
  src/main/resources/locales/en/translation/notice-length-months.json
  src/main/resources/locales/en/translation/notice-length-weeks.json
  src/main/resources/locales/en/translation/notice-pay.json
  src/main/resources/locales/en/translation/notice-type.json
  src/main/resources/locales/en/translation/pay.json
  src/main/resources/locales/en/translation/pension.json
  src/main/resources/locales/en/translation/start-date.json
  src/main/resources/locales/en/translation/still-working.json
  src/main/routes/routes.ts
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/functional/features/empDetailsWhileWorking.js
  src/test/functional/features/employeeNotWorking.js
  src/test/routes/notice-end.test.ts
  src/test/routes/notice-length.test.ts
  src/test/routes/notice-pay.test.ts
  src/test/routes/notice-type.test.ts
  src/test/routes/pension.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/EndDateController.test.ts
  src/test/unit/controller/NoticeEndController.test.ts
  src/test/unit/controller/NoticePayController.test.ts
  src/test/unit/controller/helpers.test.ts
  src/test/unit/views/job-title.test.ts
  src/test/unit/views/notice-end.test.ts
  src/test/unit/views/notice-pay.test.ts
  src/test/unit/views/start-date.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-259

#264 Ret 1931
  src/main/resources/locales/en/translation/reasonable-adjustments.json
Labels: ns:et, prd:et, rel:et-sya-pr-264

#253 moving login to azure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/test/a11y/a11y.ts
  src/test/functional/authUser/loginIdam.js
  src/test/functional/config.js
  src/test/functional/data.json
  src/test/functional/features/authPage.js
Labels: ns:et, prd:et, rel:et-sya-pr-253
