Repository hmcts/et-sya-frontend, pull requests merged in 2022-10, with the labels that each got.

#344 Ret 1968 - Check your answers
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/CaseDocumentController.ts
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/ClaimSubmittedController.ts
  src/main/controllers/PlaceOfWorkController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/SubmitClaimController.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/addressUK.ts
  src/main/definitions/constants.ts
  src/main/definitions/definition.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/resources/locales/en/translation/claimant-applications.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/routes/routes.ts
  src/main/services/CaseSelectionService.ts
  src/main/services/CaseService.ts
  src/main/views/check-your-answers.njk
  src/main/views/claim-submitted.njk
  src/main/views/employer-no-longer-working.njk
  src/main/views/employer-notice.njk
  src/main/views/employer-working.njk
  src/main/views/respondent-details-check.njk
  src/test/a11y/a11y.ts
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/routes/authenticated-routes.test.ts
  src/test/unit/controller/ChangeDetailsControllerTest.test.ts
  src/test/unit/controller/CheckAnswers.test.ts
  src/test/unit/controller/ClaimSubmitted.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/SubmitCaseController.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/services/CaseSelectionService.test.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/claim-submitted.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-344

#375 Add conditional statement to stop ex if no file
  src/main/controllers/DescribeWhatHappenedController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-375

#376 remove tag for failing test, feature will be refactored with e2e test
  src/test/end-to-end/features/WIP/checkAndSubmitCliam.js
Labels: ns:et, prd:et, rel:et-sya-pr-376

#368 Ret 2577 tech debt
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/controllers/helpers/RouterHelpers.ts
  src/main/helper/state-sequence.ts
  src/main/resources/locales/en/translation/video-hearings.json
  src/main/resources/locales/en/translation/whistleblowing-claims.json
  src/test/unit/components/address_validator.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/CitizenHubController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-368

#377 RET-2600 change lip or representative question
  src/main/controllers/LipOrRepController.ts
  src/test/routes/lip-or-representative.test.ts
  src/test/unit/controller/LipOrRepController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-377

#379 Ret 2596: Fix file type upload and update hint to include existing file
  src/main/components/form/validator.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/test/unit/components/validator.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-379

#378 RET-2582
  src/main/assets/js/address/links.ts
  src/main/assets/js/session/session-timeout.ts
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/PlaceOfWorkController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/modules/helmet/index.ts
  src/main/views/template.njk
  src/test/unit/assets/js/session/session-timeout.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-378

#380 Display No answer for reasonable adjustments
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-380

#382 Move handleUpdateDraftCase
  src/main/controllers/WorkAddressController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-382

#373 RET-2587: Temporary fix for pre-populated date fields
  sonar-project.properties
  src/main/controllers/DobController.ts
  src/main/controllers/EndDateController.ts
  src/main/controllers/NewJobStartDateController.ts
  src/main/controllers/NoticeEndController.ts
  src/main/controllers/StartDateController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-373

#367 RET-2578: Add invalidDate error description to end-date, notice-end, …
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantRequests.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/end-date.json
  src/main/resources/locales/en/translation/new-job-start-date.json
  src/main/resources/locales/en/translation/notice-end.json
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-367

#361 Ret 2070
  jest.config.js
  src/main/controllers/CaseDocumentController.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/CitizenHubDocumentController.ts
  src/main/controllers/ClaimDetailsController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/api/documentDetailsResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantRequests.ts
  src/main/definitions/constants.ts
  src/main/definitions/hub.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/acknowledgement-of-claim.json
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/claim-details.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/rejection-of-claim.json
  src/main/resources/locales/en/translation/response-acknowledgement.json
  src/main/resources/locales/en/translation/response-from-respondent.json
  src/main/resources/locales/en/translation/response-rejection.json
  src/main/resources/locales/en/translation/sidebar-contact-us.json
  src/main/resources/locales/en/translation/steps-to-making-your-claim.json
  src/main/resources/mocks/mockUserCaseWithCitizenHubLinks.ts
  src/main/routes/routes.ts
  src/main/services/CaseService.ts
  src/main/views/check-your-answers.njk
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/citizen-hub.njk
  src/main/views/claim-details.njk
  src/main/views/document-view.njk
  src/main/views/response-from-respondent-view.njk
  src/test/routes/citizen-hub.test.ts
  src/test/routes/claim-details.test.ts
  src/test/unit/controller/CaseDocumentController.test.ts
  src/test/unit/controller/CheckAnswers.test.ts
  src/test/unit/controller/CitizenHubDocumentController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/services/CaseSelectionService.test.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/test-helpers/requester.ts
  src/test/unit/views/acknowledgement-of-claim.test.ts
  src/test/unit/views/citizen-hub.test.ts
  src/test/unit/views/claim-details.test.ts
  src/test/unit/views/rejection-of-claim.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-361

#385 Feature/submit claim function
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/helpers/contactUs.js
  src/test/end-to-end/pages/checkYourAnswers/checkYourAnswers.js
  src/test/end-to-end/pages/claimDetails/claimDet.js
  src/test/end-to-end/pages/claimDetails/claimDetailsContentHelper.js
  src/test/end-to-end/pages/claimSubmitted/claimSubmitted.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/pages/submitClaim/submitClaimPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-385

#397 RET-2661: Fix for non uploaded file being visible
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/test/end-to-end/config.js
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-397

#402 Revert test url back to AAT
  src/test/end-to-end/config.js
Labels: ns:et, prd:et, rel:et-sya-pr-402

#396 Add pcq logging
  src/main/pcq/index.ts
Labels: ns:et, prd:et, rel:et-sya-pr-396

#409 RET-2224
  src/main/resources/locales/cy/translation/address-details.json
  src/main/resources/locales/cy/translation/telephone-number.json
Labels: ns:et, prd:et, rel:et-sya-pr-409

#389 RET-2223
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/date-of-birth.json
  src/main/resources/locales/cy/translation/sex-and-title.json
  src/main/resources/locales/en/translation/template.json
Labels: ns:et, prd:et, rel:et-sya-pr-389

#415 RET-2665
  src/main/controllers/TypeOfClaimController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-415

#417 RET-2665 tests
  src/test/unit/controller/TypeOfClaimController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-417

#419 RET-2663 - PDF View link is broken
  src/main/controllers/SubmittedCaseDocumentController.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/definitions/constants.ts
  src/main/routes/routes.ts
  src/main/services/CaseSelectionService.ts
  src/test/unit/controller/SubmittedCaseDocumentController.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-419

#416 RET-2679
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/test/unit/controller/RespondentDetailsCheckController.test.ts
  src/test/unit/mocks/mockUserCaseWithRespondent.ts
Labels: ns:et, prd:et, rel:et-sya-pr-416

#408 Ret 2673
  sonar-project.properties
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/main/routes/routes.ts
Labels: ns:et, prd:et, rel:et-sya-pr-408

#420 RET-2677: Add getSectionStatusForEmployment function for employment s…
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-420

#423 RET-2675 - Fix CYA page new job and notice end
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/test/unit/mocks/mockRequest.ts
Labels: ns:et, prd:et, rel:et-sya-pr-423

#425 Ret 2673 2
  src/main/definitions/constants.ts
Labels: ns:et, prd:et, rel:et-sya-pr-425

#427 RET-2694: Fix template error on section completed
  src/main/resources/locales/en/translation/tasklist-check.json
Labels: ns:et, prd:et, rel:et-sya-pr-427

#404 Merge master to release
  README.md
  sonar-project.properties
  src/main/HttpError.ts
  src/main/app.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/SubmittedCaseDocumentController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/VideoHearingsController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/modules/csrf/index.ts
  src/main/pcq/index.ts
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/tasklist-check.json
  src/main/resources/locales/en/translation/type-of-claim.json
  src/main/routes/routes.ts
  src/main/services/CaseSelectionService.ts
  src/main/views/address/postcodeEnter.njk
  src/main/views/cookie-preferences.njk
  src/main/views/form/form.njk
  src/main/views/form/multipartForm.njk
  src/main/views/macros/csrf.njk
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/routes/checklist.test.ts
  src/test/routes/contact-acas.test.ts
  src/test/routes/cookie-preferences.test.ts
  src/test/routes/home.test.ts
  src/test/routes/info.ts
  src/test/routes/lip-or-representative.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/routes/type-of-claim.test.ts
  src/test/routes/valid-no-acas-reason.test.ts
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/controller/RespondentDetailsCheckController.test.ts
  src/test/unit/controller/SubmittedCaseDocumentController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUserCaseWithRespondent.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-404

#430 RET-2693. Fix multipart form CSRF issue
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/views/form/multipartForm.njk
Labels: ns:et, prd:et, rel:et-sya-pr-430

#403 RET-2228 - Adding Welsh translations
  src/main/resources/locales/cy/translation/average-weekly-hours.json
  src/main/resources/locales/cy/translation/benefits.json
  src/main/resources/locales/cy/translation/job-title.json
  src/main/resources/locales/cy/translation/notice-length-months.json
  src/main/resources/locales/cy/translation/notice-length-weeks.json
  src/main/resources/locales/cy/translation/notice-period-working.json
  src/main/resources/locales/cy/translation/notice-type.json
  src/main/resources/locales/cy/translation/pay.json
  src/main/resources/locales/cy/translation/pension.json
  src/main/resources/locales/cy/translation/start-date.json
Labels: ns:et, prd:et, rel:et-sya-pr-403

#411 RET-2226: Add Welsh translations to past-employer and still-working
  src/main/resources/locales/cy/translation/past-employer.json
  src/main/resources/locales/cy/translation/still-working.json
Labels: ns:et, prd:et, rel:et-sya-pr-411

#401 RET-2235: Making a claim (Onboarding) pages - Welsh translation content
  src/main/assets/scss/patterns/_task-list.scss
  src/main/controllers/ClaimantApplicationsController.ts
  src/main/controllers/helpers/TranslateTypesOfClaimHelper.ts
  src/main/resources/locales/cy/translation/acas-multiple.json
  src/main/resources/locales/cy/translation/checklist.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/claim-saved.json
  src/main/resources/locales/cy/translation/claim-submitted.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/enter-address.json
  src/main/resources/locales/cy/translation/home.json
  src/main/resources/locales/cy/translation/lip-or-representative.json
  src/main/resources/locales/cy/translation/new-account-landing.json
  src/main/resources/locales/cy/translation/return-to-existing.json
  src/main/resources/locales/cy/translation/single-or-multiple-claim.json
  src/main/resources/locales/cy/translation/steps-to-making-your-claim.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/cy/translation/type-of-claim.json
  src/main/resources/locales/cy/translation/valid-no-acas-reason.json
  src/main/resources/locales/cy/translation/work-postcode.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/steps-to-making-your-claim.njk
  src/test/unit/controller/ClaimantApplicationsController.test.ts
  src/test/unit/controller/helpers/TranslateTypesOfClaimHelper.test.ts
  src/test/unit/mocks/mockApplicationWithAllTypeOfClaims.ts
  src/test/unit/mocks/mockTranslations.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-401

#414 RET-2231 - Adding Welsh translations
  src/main/resources/locales/cy/translation/end-date.json
  src/main/resources/locales/cy/translation/new-job-pay.json
  src/main/resources/locales/cy/translation/new-job-start-date.json
  src/main/resources/locales/cy/translation/notice-period-no-longer-working.json
Labels: ns:et, prd:et, rel:et-sya-pr-414

#434 RET-2234: Welsh translations
  src/main/resources/locales/cy/translation/check-your-answers.json
  src/main/resources/locales/cy/translation/claim-submitted.json
  src/main/resources/locales/cy/translation/claim-type-discrimination.json
  src/main/resources/locales/cy/translation/claimant-applications.json
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/no-acas-reason.json
  src/main/resources/locales/cy/translation/notice-end.json
  src/main/resources/locales/cy/translation/place-of-work.json
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/cy/translation/type-of-claim.json
Labels: ns:et, prd:et, rel:et-sya-pr-434

#437 re enable fortify scan and cross browser steps
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-437

#435 RET-2232
  src/main/resources/locales/cy/translation/acas-cert-num.json
  src/main/resources/locales/cy/translation/no-acas-reason.json
  src/main/resources/locales/cy/translation/respondent-address.json
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/cy/translation/respondent-name.json
  src/main/resources/locales/cy/translation/work-address.json
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-435

#449 Disable Tests for ITHC
  package.json
  src/test/smoke/codecept.smoke.conf.js
Labels: ns:et, prd:et, rel:et-sya-pr-449

#450 reenable tests
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-450

#454 Fix Smoke Tests
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-454

#459 Adding the No ACAS Details Test for the purpose of proving that the M…
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
Labels: ns:et, prd:et, rel:et-sya-pr-459

#374 RET-2580: Translation checking tests
  package.json
  src/main/resources/locales/cy/translation/acknowledgement-of-claim.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/claim-details.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/contact-acas.json
  src/main/resources/locales/cy/translation/cookie-preferences.json
  src/main/resources/locales/cy/translation/describe-what-happened.json
  src/main/resources/locales/cy/translation/new-job.json
  src/main/resources/locales/cy/translation/rejection-of-claim.json
  src/main/resources/locales/cy/translation/response-acknowledgement.json
  src/main/resources/locales/cy/translation/response-from-respondent.json
  src/main/resources/locales/cy/translation/response-rejection.json
  src/main/resources/locales/cy/translation/sidebar-contact-us.json
  src/main/resources/locales/cy/translation/tasklist-check.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/cy/translation/type-of-claim.json
  src/test/unit/translations.spec.ts
Labels: ns:et, prd:et, rel:et-sya-pr-374

#413 RET-2230 - Added Welsh translations
  src/main/resources/locales/cy/translation/notice-end.json
Labels: ns:et, prd:et, rel:et-sya-pr-413

#462 Ret 1907 test
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests-local.sh
  bin/run-crossbrowser-tests.sh
  package.json
  src/test/end-to-end/config.js
  src/test/end-to-end/features/WIP/empDetailsWhileWorking.js
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/helpers/GeneralHelpers.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/pages/checkYourAnswers/checkYourAnswers.js
  src/test/end-to-end/pages/claimDetails/claimDet.js
  src/test/end-to-end/pages/claimSubmitted/claimSubmitted.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/employmentDetails/stillWorkingPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/end-to-end/pages/saveDraft/youCanSaveCard.js
  src/test/end-to-end/pages/stepsToMakingYourClaim/stepsToMakingYourClaim.js
  src/test/end-to-end/pages/submitClaim/submitClaimPages.js
  src/test/end-to-end/saucelabs.conf.js
  src/test/end-to-end/supportedBrowsers.js
Labels: ns:et, prd:et, rel:et-sya-pr-462

#463 RET-2235: Translations to ClaimantApplication
  src/main/controllers/ClaimantApplicationsController.ts
  src/main/controllers/helpers/ApplicationTableRecordTranslationHelper.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/common.json
  src/main/services/CaseSelectionService.ts
  src/test/unit/controller/ClaimantApplicationsController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/helpers/TranslateTypesOfClaimHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockApplicationWithAllTypeOfClaims.ts
  src/test/unit/mocks/mockTranslations.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/services/CaseSelectionService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-463

#458 Ret 2723 Added check to welsh tranlations that nothing is missing
  src/test/unit/translations.spec.ts
Labels: ns:et, prd:et, rel:et-sya-pr-458

#464 Ret 2234
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
  src/main/resources/locales/cy/translation/check-your-answers.json
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/work-address.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/work-address.json
  src/main/views/work-address.njk
  src/test/unit/mocks/mockRequest.ts
Labels: ns:et, prd:et, rel:et-sya-pr-464

#468 Update 1.1.0.1 with latest
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests-local.sh
  bin/run-crossbrowser-tests.sh
  config/perftest.json
  package.json
  src/test/end-to-end/config.js
  src/test/end-to-end/features/WIP/empDetailsWhileWorking.js
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/helpers/GeneralHelpers.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/pages/checkYourAnswers/checkYourAnswers.js
  src/test/end-to-end/pages/claimDetails/claimDet.js
  src/test/end-to-end/pages/claimSubmitted/claimSubmitted.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/employmentDetails/stillWorkingPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/end-to-end/pages/saveDraft/youCanSaveCard.js
  src/test/end-to-end/pages/stepsToMakingYourClaim/stepsToMakingYourClaim.js
  src/test/end-to-end/pages/submitClaim/submitClaimPages.js
  src/test/end-to-end/saucelabs.conf.js
  src/test/end-to-end/supportedBrowsers.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-468
