Repository hmcts/et-sya-frontend, pull requests merged in 2022-04, with the labels that each got.

#186 Ret 1019
  package.json
  src/main/app.ts
  src/main/auth/index.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/constants.ts
  src/main/modules/helmet/index.ts
  src/main/modules/oidc/index.ts
  src/main/services/CacheService.ts
  src/main/views/error-summary.njk
  src/test/unit/auth/auth.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/services/CacheService.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-186

#190 RET-1232
  src/main/controllers/NoticeEndController.ts
  src/main/controllers/NoticePayController.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/notice-end.json
  src/main/resources/locales/en/translation/notice-pay.json
  src/main/views/notice-end.njk
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/routes/notice-end.test.ts
  src/test/routes/notice-pay.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/NoticeEndController.test.ts
  src/test/unit/views/notice-end.test.ts
  src/test/unit/views/notice-pay.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-190

#193 automation for check your answers page
  src/test/functional/features/checkyourAnswers.js
Labels: ns:et, prd:et, rel:et-sya-pr-193

#191 RET-1239 - Contents Layer for contact details - gender, address, dob, phone no
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/GenderDetailsController.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/address-details.json
  src/main/resources/locales/en/translation/gender-details.json
  src/main/views/address-details.njk
  src/main/views/form/fields/option.njk
  src/main/views/gender-details.njk
  src/test/unit/views/address-details.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/gender-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-191

#194 RET-1028: Add logic that if Redis fails to provide the type of claim, the user is redirected back to type of claim page
  src/main/app.ts
  src/main/auth/index.ts
  src/main/modules/oidc/index.ts
  src/test/unit/auth/auth.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-194

#196 Test Automation For RET-1235 and Cross browser fix
  .eslintrc.js
  Jenkinsfile_nightly
  package.json
  src/test/functional/features/Data/test_doc.pdf
  src/test/functional/features/etStepToMakeYourClaim.js
  src/test/functional/saucelabs.conf.js
  src/test/functional/saucelabsHelper.js
  src/test/functional/supportedBrowsers.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-196

#202 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-202

#204 added comma separator
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-204

#201 Remove deleted pages from application
  src/main/controllers/AcasSingleClaimController.ts
  src/main/controllers/GenderDetailsController.ts
  src/main/controllers/MultipleRespondentCheckController.ts
  src/main/controllers/PresentEmployerController.ts
  src/main/controllers/SingleOrMultipleController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/acas-single-claim.json
  src/main/resources/locales/en/translation/multiple-respondent-check.json
  src/main/resources/locales/en/translation/present-employer.json
  src/main/routes/routes.ts
  src/main/views/acas-single-claim.njk
  src/main/views/check-your-answers.njk
  src/main/views/multiple-respondent-check.njk
  src/main/views/present-employer.njk
  src/test/functional/features/checkyourAnswers.js
  src/test/functional/features/etSingleClaimForMyself.js
  src/test/routes/acas-single-claim.test.ts
  src/test/routes/compensation-outcome.test.ts
  src/test/routes/gender-details.test.ts
  src/test/routes/mutiple-respondent-check.test.ts
  src/test/routes/present-employer.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/unit/controller/AcasSingleClaimController.test.ts
  src/test/unit/controller/MultipleRespondentCheckController.test.ts
  src/test/unit/controller/PresentEmployerController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/views/acas-single-claim.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/mutiple-respondent-check.test.ts
  src/test/unit/views/present-employer.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-201

#205 RET-1440 Add smart feedback survey link to banner
  src/main/resources/locales/en/translation/template.json
  src/main/views/template.njk
Labels: ns:et, prd:et, rel:et-sya-pr-205

#206 update dependencies and renovate config
  .github/renovate.json
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-206

#207 updated dependencies
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-207

#208 commented code for descrimination type
  src/test/functional/features/etSingleClaimForMyself.js
Labels: ns:et, prd:et, rel:et-sya-pr-208

#209 added code back for descrimination type
  src/test/functional/features/etSingleClaimForMyself.js
Labels: ns:et, prd:et, rel:et-sya-pr-209

#199 RET 1032 - Login to retrieve saved case - Node -> Java
  src/main/app.ts
  src/main/auth/index.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/definition.ts
  src/main/modules/oidc/index.ts
  src/main/services/CaseService.ts
  src/test/routes/type-of-claim.test.ts
  src/test/unit/auth/auth.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/routes/callback.test.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-199

#212 refactor introduced typo
  src/test/functional/saucelabs.conf.js
  src/test/functional/saucelabsHelper.js
Labels: ns:et, prd:et, rel:et-sya-pr-212

#211 Ret 1456
  README.md
  config/development.json
  package.json
  src/main/controllers/LipOrRepController.ts
  src/main/controllers/SingleOrMultipleController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/addressUK.ts
  src/main/definitions/complexTypes/claimantCorrespondence.ts
  src/main/definitions/complexTypes/claimantIndividual.ts
  src/main/definitions/constants.ts
  src/main/definitions/definition.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/oidc/index.ts
  src/main/modules/session/index.ts
  src/main/resources/locales/cy/translation/single-or-multiple-claim.json
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/single-or-multiple-claim.json
  src/main/services/CacheService.ts
  src/main/services/CaseService.ts
  src/test/functional/features/etpage.js
  src/test/routes/lip-or-representative.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/routes/callback.test.ts
  src/test/unit/services/CacheService.test.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-211

#213 enable running functional test on nightly build
  package.json
  src/test/functional/saucelabs.conf.js
Labels: ns:et, prd:et, rel:et-sya-pr-213

#215 fix mismatch Test URL params in jenkinsfile
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-215

#214 RET-1438-Update-draft-case
  config/test.json
  src/main/controllers/DobController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantCorrespondence.ts
  src/main/definitions/complexTypes/claimantIndividual.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/oidc/index.ts
  src/main/services/CaseService.ts
  src/test/routes/date-of-birth.test.ts
  src/test/unit/controller/DobController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-214
