Repository hmcts/et-sya-frontend, pull requests merged in 2022-12, with the labels that each got.

#534 RET-2745 Fix issues logged in pipeline et-sya-frontend tests
  src/test/routes/acas-cert-num.test.ts
  src/test/routes/address-details.test.ts
  src/test/routes/average-weekly-hours.test.ts
  src/test/routes/benefits.test.ts
  src/test/routes/claim-details-check.test.ts
  src/test/routes/claim-type-discrimination.test.ts
  src/test/routes/claim-type-pay.test.ts
  src/test/routes/compensation.test.ts
  src/test/routes/describe-what-happened.test.ts
  src/test/routes/employment-respondent-task-check.test.ts
  src/test/routes/end-date.test.ts
  src/test/routes/job-title.test.ts
  src/test/routes/lip-or-representative.test.ts
  src/test/routes/new-job-start-date.test.ts
  src/test/routes/new-job.test.ts
  src/test/routes/no-acas-number.test.ts
  src/test/routes/notice-end.test.ts
  src/test/routes/notice-length.test.ts
  src/test/routes/notice-period.test.ts
  src/test/routes/notice-type.test.ts
  src/test/routes/past-employer.test.ts
  src/test/routes/pay.test.ts
  src/test/routes/pension.test.ts
  src/test/routes/personal-details-check.test.ts
  src/test/routes/place-of-work.test.ts
  src/test/routes/respondent-name.test.ts
  src/test/routes/sex-and-title.test.ts
  src/test/routes/still-working.test.ts
  src/test/routes/telephone-number.test.ts
  src/test/routes/tell-us-what-you-want.test.ts
  src/test/routes/tribunal-recommendation.test.ts
  src/test/routes/update-preference.test.ts
  src/test/routes/video-hearings.test.ts
  src/test/routes/whistleblowing-claims.test.ts
  src/test/routes/work-address.test.ts
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/controller/TellUsWhatYouWantController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/controller/WhistleblowingClaimsController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-534

#526 Ret 2865 - Welsh language journey - Welsh language Claimant Applications page
  src/main/resources/locales/cy/translation/claimant-applications.json
  src/main/resources/locales/cy/translation/return-to-existing.json
  src/main/resources/locales/en/translation/claimant-applications.json
  src/main/resources/locales/en/translation/return-to-existing.json
  src/main/services/CaseSelectionService.ts
  src/main/views/claimant-applications.njk
  src/main/views/home.njk
  src/test/routes/selected-application.test.ts
  src/test/unit/services/CaseSelectionService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-526

#544 RET-2261. Fix link sizes.
  src/main/views/contact-the-tribunal.njk
Labels: ns:et, prd:et, rel:et-sya-pr-544

#543 Ret 2734 new
  src/main/controllers/ContactApplicationController.ts
  src/main/controllers/RemoveFileController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/ContactApplicationHelper.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/form.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/contact-application.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/contact-application.json
  src/main/views/contact-application.njk
  src/main/views/form/form.njk
  src/test/unit/controller/ContactApplicationController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-543

#541 Ret 2818
  src/main/controllers/UpdatePreferenceController.ts
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantCorrespondence.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/update-preference.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/update-preference.json
  src/test/end-to-end/pages/checkYourAnswers/checkYourAnswers.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/routes/describe-what-happened.test.ts
  src/test/routes/update-preference.test.ts
  src/test/unit/controller/ChangeDetailsControllerTest.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/update-preference.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-541

#555 Remove language toggle
  src/main/resources/locales/en/translation/template.json
Labels: ns:et, prd:et, rel:et-sya-pr-555

#556 RET-2734 - small fixes
  src/main/resources/locales/en/translation/contact-application.json
  src/main/views/contact-application.njk
Labels: ns:et, prd:et, rel:et-sya-pr-556

#520 Ret 2831 - IDAM journey - chosen language should persist after log out and log in
  src/main/assets/js/session/session-timeout.ts
  src/main/modules/oidc/index.ts
  src/test/unit/assets/js/session/session-timeout.test.ts
  src/test/unit/routes/callback.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-520

#563 Ret 2865 - Welsh language journey - Welsh language Claimant Applications page
  src/main/controllers/ClaimantApplicationsController.ts
  src/main/definitions/appRequest.ts
  src/test/unit/mocks/mockRequest.ts
Labels: ns:et, prd:et, rel:et-sya-pr-563

#560 RET-2888
  src/main/resources/locales/en/translation/update-preference.json
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
Labels: ns:et, prd:et, rel:et-sya-pr-560

#559 Ret 2615
  src/main/controllers/ContactTheTribunalController.ts
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/RemoveFileController.ts
  src/main/controllers/helpers/ContactApplicationHelper.ts
  src/main/definitions/constants.ts
  src/main/definitions/contact-applications.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal-amend.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-change-details.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-non-compliance.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-other.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-postpone.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-publicity.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-reconsider-decision.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-reconsider-judgement.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-respondent.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-strike.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-vary.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-withdraw.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-witness.json
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/en/translation/contact-the-tribunal-amend.json
  src/main/resources/locales/en/translation/contact-the-tribunal-change-details.json
  src/main/resources/locales/en/translation/contact-the-tribunal-non-compliance.json
  src/main/resources/locales/en/translation/contact-the-tribunal-other.json
  src/main/resources/locales/en/translation/contact-the-tribunal-postpone.json
  src/main/resources/locales/en/translation/contact-the-tribunal-publicity.json
  src/main/resources/locales/en/translation/contact-the-tribunal-reconsider-decision.json
  src/main/resources/locales/en/translation/contact-the-tribunal-reconsider-judgement.json
  src/main/resources/locales/en/translation/contact-the-tribunal-respondent.json
  src/main/resources/locales/en/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/en/translation/contact-the-tribunal-strike.json
  src/main/resources/locales/en/translation/contact-the-tribunal-vary.json
  src/main/resources/locales/en/translation/contact-the-tribunal-withdraw.json
  src/main/resources/locales/en/translation/contact-the-tribunal-witness.json
  src/main/resources/locales/en/translation/contact-the-tribunal.json
  src/main/views/contact-application.njk
  src/main/views/contact-the-tribunal-selected.njk
  src/main/views/contact-the-tribunal.njk
  src/main/views/tribunal-contact-selected.njk
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/unit/controller/ContactApplicationController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-559

#566 Ret 2615
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/helpers/contactUsForCitizenHub.js
  src/test/end-to-end/pages/citizenHub/citizenHub.js
  src/test/end-to-end/pages/claimantApplications/claimantApplications.js
  src/test/end-to-end/pages/steps.js
Labels: ns:et, prd:et, rel:et-sya-pr-566

#568 added welsh translations
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/cookie-preferences.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/cookie-preferences.json
  src/main/views/cookie-banner.njk
  src/main/views/cookie-preferences.njk
Labels: ns:et, prd:et, rel:et-sya-pr-568
