Repository hmcts/et-sya-frontend, pull requests merged in 2022-02, with the labels that each got.

#49 Ret 357: Acas single claim page
  src/main/controllers/SingleOrMultipleController.ts
  src/main/controllers/acas_single_claim/AcasSingleClaimController.ts
  src/main/controllers/acas_single_claim/content.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/acas-single-claim.json
  src/main/resources/locales/en/translation/common.json
  src/main/routes/routes.ts
  src/main/views/acas-single-claim.njk
  src/main/views/template.njk
  src/test/routes/acas-single-claim.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/unit/controller/AcasSingleClaimController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/views/acas-single-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-49

#56 Ret 793
  nodemon.json
  package.json
  src/main/assets/scss/main.scss
  src/main/controllers/NewAccountLanding/NewAccountLandingController.ts
  src/main/resources/locales/en/translation/new-account-landing.json
  src/main/routes/routes.ts
  src/main/views/new-account-landing.njk
  src/test/routes/new-account-landing.test.ts
  src/test/unit/controller/NewAccountLandingContoller.test.ts
  src/test/unit/views/new-account-landing.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-56

#42 Ret 337
  src/main/controllers/return_to_existing_claim/ReturnToExistingController.ts
  src/main/controllers/return_to_existing_claim/content.ts
  src/main/definitions/case.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/en/translation/return-to-existing.json
  src/main/routes/routes.ts
  src/main/views/return-to-claim.njk
  src/test/routes/return-to-existing.test.ts
  src/test/unit/controller/ReturnToExistingController.test.ts
  src/test/unit/views/return-to-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-42

#84 RET-1066: Rectified erroneous new lines causing build to fail
  src/main/resources/locales/en/translation/return-to-existing.json
Labels: ns:et, prd:et, rel:et-sya-pr-84

#48 RET-508 add generic form changes
  src/main/controllers/LipOrRepController.ts
  src/main/controllers/SingleOrMultipleController.ts
  src/main/controllers/single_or_multiple_claim/content.ts
  src/main/controllers/single_or_multiple_claim/singleOrMultipleController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/single-or-multiple-claim.json
  src/main/utils/getLegacyUrlFromLng.ts
  src/main/views/single-or-multiple-claim.njk
  src/test/routes/lip-or-representative.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/unit/controller/ClaimSaved.test.ts
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/utils/getLegacyUrlFromLng.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-48

#53 RET-919 add contact acas page and tests
  src/main/controllers/ContactAcasController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/contact-acas.json
  src/main/routes/routes.ts
  src/main/views/contact-acas.njk
  src/test/routes/contact-acas.test.ts
  src/test/unit/controller/ContactAcas.test.ts
  src/test/unit/views/contact-acas.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-53

#46 RET-360 add tel number
  package.json
  src/main/components/form/validator.ts
  src/main/controllers/tel_number/TelNumberController.ts
  src/main/controllers/tel_number/content.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/telephone-number.json
  src/main/routes/routes.ts
  src/main/views/telephone-number.njk
  src/test/routes/telephone-number.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/TelNumberController.test.ts
  src/test/unit/views/telephone-number.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-46

#47 RET-899 updates to use generic form
  src/main/controllers/LipOrRepController.ts
  src/main/controllers/litigation_in_person_or_representative/content.ts
  src/main/controllers/litigation_in_person_or_representative/lipOrRepController.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/views/lip-or-representative.njk
  src/test/routes/lip-or-representative.test.ts
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/views/lip-or-representative.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-47

#50 Ret 361
  src/main/controllers/update_preference/UpdatePreferenceController.ts
  src/main/controllers/update_preference/content.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/update-preference.json
  src/main/routes/routes.ts
  src/main/views/update-preference.njk
  src/test/routes/update-preference.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/views/update-preference.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-50

#52 RET-362 add video hearings choice page
  src/main/controllers/VideoHearingsController.ts
  src/main/controllers/helpers.ts
  src/main/controllers/video_hearings/VideoHearingsController.ts
  src/main/controllers/video_hearings/content.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/video-hearings.json
  src/main/views/form/form.njk
  src/main/views/video-hearings.njk
  src/test/routes/video-hearings.test.ts
  src/test/unit/controller/VideoHearingsController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-52

#36 Ret 845
  src/main/controllers/multiple_respondent/MultipleRespondentCheckController.ts
  src/main/controllers/multiple_respondent/content.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/multiple-respondent-check.json
  src/main/routes/routes.ts
  src/main/views/multiple-respondent-check.njk
  src/test/routes/mutiple-respondent-check.test.ts
  src/test/unit/controller/MultipleRespondentCheckController.test.ts
  src/test/unit/views/mutiple-respondent-check.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-36

#38 Ret 846
  src/main/controllers/acas_multiple/AcasMultipleController.ts
  src/main/controllers/acas_multiple/content.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/acas-multiple.json
  src/main/routes/routes.ts
  src/main/views/acas-multiple.njk
  src/test/routes/acas-multiple.test.ts
  src/test/unit/controller/AcasMultipleController.test.ts
  src/test/unit/views/acas-multiple.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-38

#81 Ret 860
  src/main/controllers/present_employer/PresentEmployerController.ts
  src/main/controllers/present_employer/content.ts
  src/main/definitions/case.ts
  src/main/definitions/radios.ts
  src/main/resources/locales/en/translation/present-employer.json
  src/main/routes/routes.ts
  src/main/views/present-employer.njk
  src/test/routes/acas-single-claim.test.ts
  src/test/routes/present-employer.test.ts
  src/test/unit/controller/PresentEmployerController.test.ts
  src/test/unit/views/present-employer.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-81

#86 Add new infrastructure folder for Redis cache infra
  infrastructure/.terraform-version
  infrastructure/README.md
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:et, prd:et, rel:et-sya-pr-86

#97 Bump nodejs helm chart
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-97

#94 Ret functional tests
  .eslintrc.js
  .gitignore
  Jenkinsfile_nightly
  README.md
  package.json
  src/test/functional/codecept.conf.js
  src/test/functional/config.js
  src/test/functional/features/homepage.js
  src/test/functional/pages/steps.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-94

#112 feat: upgraded node-js chart
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-112

#102 Fix failing routes tests
  src/main/modules/i18next/index.ts
  src/test/routes/address-details.test.ts
  src/test/routes/mutiple-respondent-check.test.ts
  src/test/routes/return-to-existing.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/routes/telephone-number.test.ts
  src/test/unit/controller/AcasMultipleController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/TelNumberController.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-102

#57 Ret 800
  src/main/resources/locales/en/translation/claim-saved.json
  src/main/views/claim-saved.njk
Labels: ns:et, prd:et, rel:et-sya-pr-57

#115 Chart upgrade node js
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-115

#101 RET-1089 basic gender details page
  src/main/resources/locales/en/translation/gender-details.json
  src/test/routes/address-details.test.ts
  src/test/routes/gender-details.test.ts
  src/test/routes/mutiple-respondent-check.test.ts
  src/test/routes/return-to-existing.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/routes/telephone-number.test.ts
  src/test/unit/controller/AcasMultipleController.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/controller/PresentEmployerController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/TelNumberController.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/views/gender-details.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-101

#100 Ret 1014
  charts/et-sya/Chart.yaml
  charts/et-sya/values.preview.template.yaml
  charts/et-sya/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  package.json
  src/main/app.ts
  src/main/modules/health/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/session/index.ts
  src/main/routes/routes.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-100

#114 Ret 1086: Type of claim page
  src/main/components/form/parser.ts
  src/main/controllers/helpers.ts
  src/main/controllers/type_of_claim/TypeOfClaimController.ts
  src/main/controllers/type_of_claim/content.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/definition.ts
  src/main/definitions/form.ts
  src/main/resources/locales/en/translation/type-of-claim.json
  src/main/routes/routes.ts
  src/main/views/form/fields/checkboxes.njk
  src/main/views/type-of-claim.njk
  src/test/routes/type-of-claim.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/views/type-of-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-114

#117 RET-1092 wire up task list 1
  package.json
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/gender_details/GenderDetailsController.ts
  src/main/controllers/gender_details/content.ts
  src/main/controllers/multiple_respondent/MultipleRespondentCheckController.ts
  src/main/definitions/constants.ts
  src/main/modules/helmet/index.ts
  src/main/resources/locales/en/translation/gender-details.json
  src/main/resources/locales/en/translation/steps-to-making-your-claim.json
  src/main/routes/routes.ts
  src/main/views/gender-details.njk
  src/main/views/steps-to-making-your-claim.njk
  src/test/routes/contact-acas.test.ts
  src/test/routes/gender-details.test.ts
  src/test/routes/steps-to-making-your-claim.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/controller/PastEmployerController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-117

#85 RET 1005 Job Title
  src/main/components/form/validator.ts
  src/main/controllers/job_title/JobTitleController.ts
  src/main/controllers/job_title/content.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/job-title.json
  src/main/routes/routes.ts
  src/main/views/job-title.njk
  src/test/routes/job-title.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/JobTitleController.test.ts
  src/test/unit/views/job-title.test.ts
  src/test/unit/views/still-working.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-85

#118 add functional test for RET-1014
  src/test/functional/features/homepage.js
Labels: ns:et, prd:et, rel:et-sya-pr-118

#120 RET-1058-emp-details-pension-notice
  src/main/controllers/employment_details_pension/EmploymentDetailsPensionController.ts
  src/main/controllers/employment_details_pension/content.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/employment-details-pension.json
  src/main/routes/routes.ts
  src/main/views/employment-details-pension.njk
  src/test/routes/employment-details-pension.test.ts
  src/test/unit/controller/EmploymentDetailsPensionController.test.ts
  src/test/unit/views/employment-details-pension.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-120
