Repository hmcts/et-sya-frontend, pull requests merged in 2022-01, with the labels that each got.

#22 feat: Updated sonar project to exclude some files
  package.json
  sonar-project.properties
  src/test/routes/home.ts
  src/test/unit/controller/HomeController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-22

#16 Ret 356
  sonar-project.properties
  src/main/controllers/LipOrRepController.ts
  src/main/controllers/SingleOrMultipleController.ts
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/template.json
  src/main/routes/routes.ts
  src/main/views/lip-or-representative.njk
  src/main/views/single-or-multiple-claim.njk
  src/main/views/template.njk
  src/test/routes/lip-or-representative.ts
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/views/lip-or-representative.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-16

#26 Ret 348
  config/default.json
  package.json
  src/main/app.ts
  src/main/components/form/form.ts
  src/main/components/form/parser.ts
  src/main/components/form/validator.ts
  src/main/controllers/dob/DobController.ts
  src/main/controllers/dob/content.ts
  src/main/controllers/gender_details/GenderDetailsController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/case.ts
  src/main/definitions/form.ts
  src/main/definitions/util-types.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/session/index.ts
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/date-of-birth.json
  src/main/resources/locales/en/translation/gender-details.json
  src/main/routes/routes.ts
  src/main/views/date-of-birth.njk
  src/main/views/form/fields.njk
  src/main/views/form/fields/checkboxes.njk
  src/main/views/form/fields/date.njk
  src/main/views/form/fields/hidden.njk
  src/main/views/form/fields/input.njk
  src/main/views/form/fields/option.njk
  src/main/views/form/fields/radios.njk
  src/main/views/form/fields/tel.njk
  src/main/views/form/fields/text.njk
  src/main/views/form/fields/textarea.njk
  src/main/views/form/form.njk
  src/main/views/gender-details.njk
  src/test/routes/date-of-birth.test.ts
  src/test/unit/components/form.test.ts
  src/test/unit/components/parser.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/DobController.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockResponse.ts
  src/test/unit/views/date-of-birth.test.ts
  tsconfig.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-26

#32 RET-508
  src/main/controllers/LipOrRepController.ts
  src/main/controllers/SingleOrMultipleController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/single-or-multiple-claim.json
  src/main/routes/routes.ts
  src/main/views/single-or-multiple-claim.njk
  src/main/views/webpack/js.njk
  src/test/routes/lip-or-representative.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/views/single-or-multiple-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-32

#31 RET 362
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/VideoHearingsController.ts
  src/main/controllers/claimSavedController.ts
  src/main/resources/locales/en/translation/video-hearings.json
  src/main/routes/routes.ts
  src/main/views/claim-saved.njk
  src/main/views/steps-to-making-your-claim.njk
  src/main/views/video-hearings.njk
  src/test/routes/steps-to-making-your-claim.test.ts
  src/test/routes/video-hearings.test.ts
  src/test/routes/you-claim-has-been-saved.test.ts
  src/test/unit/controller/ClaimSaved.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/VideoHearingsController.test.ts
  src/test/unit/views/video-hearing.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-31

#41 Ret 417
  charts/et-sya/Chart.yaml
  charts/et-sya/values.aat.template.yaml
  charts/et-sya/values.preview.template.yaml
  charts/et-sya/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/dev.json
  config/development.json
  docker-compose.yml
  package.json
  sonar-project.properties
  src/main/app.ts
  src/main/auth/index.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/server.ts
  src/test/unit/auth/auth.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-41

#55 upgraded property volumes version
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-55
