Repository hmcts/et-sya-frontend, pull requests merged in 2022-11, with the labels that each got.

#457 RET-2713: Welsh translation content - PCQ Integration
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/LanguageHelper.ts
  src/main/definitions/constants.ts
  src/main/pcq/index.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/helpers/LanguageHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-457

#474 Add hard wait after completing each section
  src/test/end-to-end/pages/claimDetails/claimDet.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
Labels: ns:et, prd:et, rel:et-sya-pr-474

#489 add retry option to help the pipeline
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
Labels: ns:et, prd:et, rel:et-sya-pr-489

#487 RET-2686 - Update journey for claimant not employed by respondent
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/test/unit/controller/RespondentAddressController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-487

#495 Ret 2765 fortify vulnerability
  src/main/assets/js/address/submit.ts
  src/main/assets/js/set-focus.ts
Labels: ns:et, prd:et, rel:et-sya-pr-495

#497 Ret 2778 - Content Security Policy directive failure
  webpack.config.js
Labels: ns:et, prd:et, rel:et-sya-pr-497

#500 Ret 2749
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-500

#504 fix failing test in R1.1.0.2
  src/test/end-to-end/features/WIP/empDetailsWhileWorking.js
  src/test/end-to-end/pages/employmentDetails/stillWorkingPages.js
  src/test/end-to-end/pages/employmentDetails/workingNoticePeriodPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-504

#498 PCQ url
  src/main/pcq/index.ts
Labels: ns:et, prd:et, rel:et-sya-pr-498

#506 Revert "PCQ url"
  src/main/pcq/index.ts
Labels: ns:et, prd:et, rel:et-sya-pr-506

#507 Fix failing functional tests
  src/test/end-to-end/features/WIP/empDetailsWhileWorking.js
  src/test/end-to-end/pages/employmentDetails/stillWorkingPages.js
  src/test/end-to-end/pages/employmentDetails/workingNoticePeriodPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-507

#476 RET-2735 link to citizen hub on /claimant-applications
  src/main/controllers/SubmittedCaseDocumentController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/services/CaseSelectionService.ts
  src/test/unit/controller/SubmittedCaseDocumentController.test.ts
  src/test/unit/mocks/mockApplications.ts
Labels: ns:et, prd:et, rel:et-sya-pr-476

#511 RET-2258 - Reuse post logic
  src/main/controllers/helpers/CaseHelpers.ts
  src/test/unit/controller/ReturnToExistingController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-511

#488 Ret 2709: Added selection for prefered language in contact preferences
  src/main/controllers/UpdatePreferenceController.ts
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantCorrespondence.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/update-preference.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/update-preference.json
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/pages/checkYourAnswers/checkYourAnswers.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/routes/update-preference.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/update-preference.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-488

#426 RET-2668
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/cy/translation/address-details.json
  src/main/resources/locales/cy/translation/claim-details-check.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/date-of-birth.json
  src/main/resources/locales/cy/translation/reasonable-adjustments.json
  src/main/resources/locales/cy/translation/sex-and-title.json
  src/main/resources/locales/cy/translation/tasklist-check.json
  src/main/resources/locales/cy/translation/telephone-number.json
  src/main/resources/locales/cy/translation/update-preference.json
  src/main/resources/locales/cy/translation/video-hearings.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/home.njk
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/helpers/contactUs.js
Labels: ns:et, prd:et, rel:et-sya-pr-426

#482 RET-2766. Fix callback.test.ts
  src/test/unit/mocks/mockUserCaseResponseMinimal.ts
  src/test/unit/routes/callback.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-482

#515 Ret 2740 refactor
  src/main/auth/index.ts
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/ChecklistController.ts
  src/main/controllers/ClaimSavedController.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/HomeController.ts
  src/main/controllers/NewAccountLandingController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/WorkAddressController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/LanguageHelper.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/index.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/views/address/postcodeEnter.njk
  src/main/views/check-your-answers.njk
  src/main/views/checklist.njk
  src/main/views/claim-saved.njk
  src/main/views/home.njk
  src/main/views/new-account-landing.njk
  src/main/views/respondent-details-check.njk
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePersonWelsh.js
  src/test/end-to-end/pages/employmentDetails/didYouWorkForOrg.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/end-to-end/pages/welshTranslations/claim.detail.welsh.page.js
  src/test/end-to-end/pages/welshTranslations/employment.and.respondent.details.welsh.page.js
  src/test/end-to-end/pages/welshTranslations/login.page.js
  src/test/end-to-end/pages/welshTranslations/personal.details.welsh.page.js
  src/test/end-to-end/pages/welshTranslations/prelogin.welsh.page.js
  src/test/end-to-end/pages/welshTranslations/submit.claim.welsh.page.js
  src/test/end-to-end/pages/welshTranslations/task.list.welsh.page.js
  src/test/routes/claim-submitted.test.ts
  src/test/routes/describe-what-happened.test.ts
  src/test/unit/auth/auth.test.ts
  src/test/unit/controller/ChangeDetailsControllerTest.test.ts
  src/test/unit/controller/ChecklistController.test.ts
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/controller/HomeController.test.ts
  src/test/unit/controller/ReturnToExistingController.test.ts
  src/test/unit/routes/callback.test.ts
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-515

#492 Ret 2691 - Update the hint text with file existing in describeWhatHappened to match spec
  src/main/resources/locales/en/translation/describe-what-happened.json
Labels: ns:et, prd:et, rel:et-sya-pr-492

#473 RET-2729 - Add second release locations
  src/main/controllers/WorkPostcodeController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-473

#512 RET-2809 Address Lines Update
  src/main/address/index.ts
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
Labels: ns:et, prd:et, rel:et-sya-pr-512

#525 RET-2782
  src/main/helper/ApiFormatter.ts
  src/test/unit/helper/ApiFormatter.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-525

#527 Ret 2870 contact link update
  src/main/views/citizen-hub-sidebar.njk
Labels: ns:et, prd:et, rel:et-sya-pr-527

#529 Ret 2872
  src/main/controllers/CitizenHubDocumentController.ts
  src/main/views/citizen-hub.njk
Labels: ns:et, prd:et, rel:et-sya-pr-529

#530 Merge 1.1.0.2 into welsh
  src/main/address/index.ts
  src/main/assets/js/address/submit.ts
  src/main/assets/js/set-focus.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/WorkPostcodeController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/definitions/constants.ts
  src/main/pcq/index.ts
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/main/resources/locales/en/translation/template.json
  src/main/services/CaseSelectionService.ts
  src/main/views/check-your-answers.njk
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/home.njk
  src/main/views/respondent-details-check.njk
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/helpers/contactUs.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/unit/controller/ReturnToExistingController.test.ts
  src/test/unit/controller/SubmittedCaseDocumentController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockUserCaseResponseMinimal.ts
  src/test/unit/routes/callback.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-530

#533 Ret-2738 Improve et-sya-frontend tests
  Jenkinsfile_CNP
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/routes/new-job.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-533

#535 fix address line failure
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-535

#519 Ret 2810 - Fix Fortify issues in 1.1.0.2
  charts/et-sya/Chart.yaml
  src/main/assets/js/set-focus.ts
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/ClaimDetailsCheckController.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/EmploymentAndRespondentCheckController.ts
  src/main/controllers/PcqController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/controllers/helpers/RouterHelpers.ts
  src/main/definitions/constants.ts
  src/main/pcq/index.ts
  src/test/unit/controller/ChangeDetailsControllerTest.test.ts
  src/test/unit/controller/PcqController.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-519

#510 Deployed to Demo : Release1.1Fixes
  src/main/address/index.ts
  src/main/controllers/CitizenHubDocumentController.ts
  src/main/pcq/index.ts
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/citizen-hub.njk
  src/test/end-to-end/config.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
Labels: ns:et, prd:et, rel:et-sya-pr-510

#536 RET-2810 - Fix redirect for respondent pages
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/helpers/RouterHelpers.ts
  src/test/unit/controller/ChangeDetailsControllerTest.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-536

#537 1.1.1 mergefix
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/CitizenHubDocumentController.ts
  src/main/controllers/helpers/RouterHelpers.ts
  src/main/helper/ApiFormatter.ts
  src/test/unit/controller/ChangeDetailsControllerTest.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-537

#540 Reset guid on return to existing
  src/main/controllers/ReturnToExistingController.ts
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/routes/return-to-existing.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-540

#532 Ret 2261
  src/main/controllers/ContactTheTribunalController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/definitions/constants.ts
  src/main/definitions/hub.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/en/translation/contact-the-tribunal.json
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/citizen-hub.njk
  src/main/views/contact-the-tribunal.njk
  src/main/views/tribunal-contact-selected.njk
  src/test/unit/mocks/mockEt1DataModel.ts
Labels: ns:et, prd:et, rel:et-sya-pr-532
