Repository hmcts/et-sya-frontend, pull requests merged in 2022-07, with the labels that each got.

#269 Modified Fortify gradlew file from Windows EOL to Unix EOL (LF)
  src/test/java/gradlew
Labels: ns:et, prd:et, rel:et-sya-pr-269

#271 Update Hmcts frontend packages
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-271

#275 Resolve_Pact_Test_Problem
  src/test/api/pact/pact-test/idam/get-user-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-275

#273 ignore issue fixed and removed ignore statements
  src/test/a11y/a11y.ts
Labels: ns:et, prd:et, rel:et-sya-pr-273

#277 RET-1973. Implement validation and errors for sex&gender, and DOB pages.
  package.json
  src/main/components/form/validator.ts
  src/main/controllers/DobController.ts
  src/main/controllers/GenderDetailsController.ts
  src/main/resources/locales/en/translation/gender-details.json
  src/test/routes/gender-details.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-277

#278 Update Helm Chart release nodejs to v2.4.5
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-278

#276 RET 1816 steps to making your claim task statuses (in progress, not started, completed)
  src/main/assets/scss/main.scss
  src/main/assets/scss/patterns/_task-list.scss
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/definition.ts
  src/main/resources/locales/en/translation/steps-to-making-your-claim.json
  src/main/views/steps-to-making-your-claim.njk
  src/test/unit/controller/helpers.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-276

#281 Ret 1979 - Task List 1 - Preferences - Validation and Errors
  dump.rdb
  src/main/controllers/VideoHearingsController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/en/translation/video-hearings.json
  src/main/views/form/fields/checkboxes.njk
  src/main/views/video-hearings.njk
  src/test/routes/video-hearings.test.ts
  src/test/unit/controller/VideoHearingsController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-281

#265 RET-1932
  src/main/controllers/AverageWeeklyHoursController.ts
  src/main/controllers/BenefitsController.ts
  src/main/controllers/DobController.ts
  src/main/controllers/JobTitleController.ts
  src/main/controllers/NoticeEndController.ts
  src/main/controllers/NoticeLengthController.ts
  src/main/controllers/NoticePeriodController.ts
  src/main/controllers/NoticeTypeController.ts
  src/main/controllers/PastEmployerController.ts
  src/main/controllers/PayController.ts
  src/main/controllers/PensionController.ts
  src/main/controllers/PersonalDetailsCheckController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/controllers/StartDateController.ts
  src/main/controllers/StillWorkingController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantEmploymentDetails.ts
  src/main/helper/ApiFormatter.ts
  src/test/unit/controller/AverageWeeklyHoursController.test.ts
  src/test/unit/controller/BenefitsController.test.ts
  src/test/unit/controller/DobController.test.ts
  src/test/unit/controller/JobTitleController.test.ts
  src/test/unit/controller/NoticeEndController.test.ts
  src/test/unit/controller/NoticeLengthController.test.ts
  src/test/unit/controller/NoticePeriodController.test.ts
  src/test/unit/controller/NoticeTypeController.test.ts
  src/test/unit/controller/PastEmployerController.test.ts
  src/test/unit/controller/PayController.test.ts
  src/test/unit/controller/PensionController.test.ts
  src/test/unit/controller/PersonalDetailsCheckController.test.ts
  src/test/unit/controller/StartDateController.test.ts
  src/test/unit/controller/StillWorkingController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-265

#284 RET 1995 and RET-2079 - Onboarding pages and postcodes for MVP
  config/default.json
  package.json
  src/main/app.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/WorkPostcodeController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/resources/locales/en/translation/acas-multiple.json
  src/main/resources/locales/en/translation/checklist.json
  src/main/resources/locales/en/translation/claim-saved.json
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/return-to-existing.json
  src/main/resources/locales/en/translation/single-or-multiple-claim.json
  src/main/resources/locales/en/translation/steps-to-making-your-claim.json
  src/main/resources/locales/en/translation/template.json
  src/main/resources/locales/en/translation/valid-no-acas-reason.json
  src/main/resources/locales/en/translation/work-postcode.json
  src/main/routes/routes.ts
  src/main/views/acas-multiple.njk
  src/main/views/checklist.njk
  src/main/views/claim-saved.njk
  src/main/views/lip-or-representative.njk
  src/main/views/single-or-multiple-claim.njk
  src/main/views/steps-to-making-your-claim.njk
  src/test/functional/features/commonFlow.js
  src/test/functional/features/etMultipleClaimsForMyself.js
  src/test/unit/controller/DownloadClaimController.test.ts
  src/test/unit/controller/WorkPostcodeController.test.ts
  src/test/unit/controller/helpers.test.ts
  src/test/unit/views/lip-or-representative.test.ts
  src/test/unit/views/single-or-multiple-claim.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
  src/test/unit/views/work-postcode.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-284
