Repository hmcts/et-sya-frontend, pull requests merged in 2022-08, with the labels that each got.

#289 RET-1889: Fix Accessibility automation failures
  src/main/controllers/AcasMultipleController.ts
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/AverageWeeklyHoursController.ts
  src/main/controllers/BenefitsController.ts
  src/main/controllers/ClaimDetailsCheckController.ts
  src/main/controllers/ClaimTypeDiscriminationController.ts
  src/main/controllers/ClaimTypePayController.ts
  src/main/controllers/CompensationController.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/EmploymentAndRespondentCheckController.ts
  src/main/controllers/LipOrRepController.ts
  src/main/controllers/NewJobController.ts
  src/main/controllers/NoAcasNumberController.ts
  src/main/controllers/NoticeLengthController.ts
  src/main/controllers/NoticePeriodController.ts
  src/main/controllers/PastEmployerController.ts
  src/main/controllers/PensionController.ts
  src/main/controllers/PersonalDetailsCheckController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/controllers/ReturnToExistingController.ts
  src/main/controllers/SingleOrMultipleController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/TellUsWhatYouWantController.ts
  src/main/controllers/TribunalRecommendationController.ts
  src/main/controllers/ValidNoAcasReasonController.ts
  src/main/controllers/VideoHearingsController.ts
  src/main/controllers/WhistleblowingClaimsController.ts
  src/main/definitions/constants.ts
  src/main/definitions/dates.ts
  src/main/definitions/form.ts
  src/main/definitions/radios.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/resources/locales/en/translation/address-details.json
  src/main/resources/locales/en/translation/enter-address.json
  src/main/resources/locales/en/translation/place-of-work.json
  src/main/routes/routes.ts
  src/main/views/address/postcodeEnter.njk
  src/main/views/form/fields/currency.njk
  src/main/views/form/fields/input.njk
  src/main/views/form/fields/upload.njk
  src/test/a11y/a11y.ts
Labels: ns:et, prd:et, rel:et-sya-pr-289

#288 Ret 1980 - Task List 1 - Preferences - Save data & Final checks
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/UpdatePreferenceController.ts
  src/main/controllers/VideoHearingsController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantContactPreference.ts
  src/main/definitions/complexTypes/claimantHearingPreference.ts
  src/main/helper/ApiFormatter.ts
  src/test/routes/update-preference.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/controller/VideoHearingsController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/video-hearing.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-288

#294 For pa11y testing with post-login pages
  Jenkinsfile_CNP
  src/main/modules/oidc/index.ts
  src/test/a11y/a11y.ts
Labels: ns:et, prd:et, rel:et-sya-pr-294

#279 1973. Validation of personal details pages.
  .gitignore
  dump.rdb
  src/main/components/form/dateValidators.ts
  src/main/components/form/validator.ts
  src/main/controllers/DobController.ts
  src/main/controllers/GenderDetailsController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/definitions/dates.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/en/translation/date-of-birth.json
  src/main/resources/locales/en/translation/gender-details.json
  src/main/resources/locales/en/translation/notice-end.json
  src/main/resources/locales/en/translation/start-date.json
  src/main/views/gender-details.njk
  src/test/routes/gender-details.test.ts
  src/test/unit/components/dateValidators.test.ts
  src/test/unit/components/form.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/DobController.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/controller/helpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-279

#299 ET-2066 Accessibility issues for et-sya-frontend - Responsive CSS
  src/main/assets/js/index.js
  src/main/assets/js/set-styles.ts
Labels: ns:et, prd:et, rel:et-sya-pr-299

#300 Bump Helm + types
  charts/et-sya/Chart.yaml
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-300

#296 Ret 2194 - Task List 1: Reasonable Adjustments - Last layer - Final checks
  src/main/controllers/ClaimDetailsCheckController.ts
  src/main/controllers/EmploymentAndRespondentCheckController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/UpdatePreferenceController.ts
  src/main/controllers/VideoHearingsController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantContactPreference.ts
  src/main/definitions/complexTypes/claimantCorrespondence.ts
  src/main/definitions/complexTypes/taskListCheckType.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/reasonable-adjustments.json
  src/main/resources/locales/en/translation/update-preference.json
  src/main/resources/locales/en/translation/video-hearings.json
  src/test/routes/update-preference.test.ts
  src/test/routes/video-hearings.test.ts
  src/test/unit/controller/ClaimDetailsCheckController.test.ts
  src/test/unit/controller/EmploymentAndRespondentCheckController.test.ts
  src/test/unit/controller/ReasonableAdjustmentsController.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/controller/VideoHearingsController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/reasonable-adjustments.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-296

#298 RET-1974. Save data and final checks for RET-349 and RET-835.
  src/main/controllers/GenderDetailsController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantIndividual.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/gender-details.json
  src/test/routes/gender-details.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-298

#303 Added TLS 1.2 min version to fix Fortify flaw
  src/main/server.ts
Labels: ns:et, prd:et, rel:et-sya-pr-303

#297 Ret 1934 - Employment Details (No longer working) - Final
  src/main/components/form/validator.ts
  src/main/controllers/BenefitsController.ts
  src/main/controllers/CompensationController.ts
  src/main/controllers/EndDateController.ts
  src/main/controllers/NewJobController.ts
  src/main/controllers/NewJobPayController.ts
  src/main/controllers/NewJobStartDateController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantEmploymentDetails.ts
  src/main/definitions/complexTypes/newEmploymentDetails.ts
  src/main/definitions/currency-fields.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/benefits.json
  src/main/resources/locales/en/translation/end-date.json
  src/main/resources/locales/en/translation/new-job-pay.json
  src/main/resources/locales/en/translation/new-job-start-date.json
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/BenefitsController.test.ts
  src/test/unit/controller/EndDateController.test.ts
  src/test/unit/controller/NewJobController.test.ts
  src/test/unit/controller/NewJobPayController.test.ts
  src/test/unit/controller/NewJobStartDateController.test.ts
  src/test/unit/controller/NoticePeriodController.test.ts
  src/test/unit/controller/PayController.test.ts
  src/test/unit/controller/PensionController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockLogger.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-297

#301 Ret 2064 - Updates the title for each page to be inline with accessibility guidelines
  src/main/resources/locales/en/translation/acas-multiple.json
  src/main/resources/locales/en/translation/benefits.json
  src/main/resources/locales/en/translation/claim-details-check.json
  src/main/resources/locales/en/translation/claim-saved.json
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/resources/locales/en/translation/claim-type-discrimination.json
  src/main/resources/locales/en/translation/claim-type-pay.json
  src/main/resources/locales/en/translation/compensation.json
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/main/resources/locales/en/translation/job-title.json
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/new-job.json
  src/main/resources/locales/en/translation/no-acas-reason.json
  src/main/resources/locales/en/translation/notice-length-months.json
  src/main/resources/locales/en/translation/notice-length-weeks.json
  src/main/resources/locales/en/translation/notice-period-no-longer-working.json
  src/main/resources/locales/en/translation/notice-type.json
  src/main/resources/locales/en/translation/past-employer.json
  src/main/resources/locales/en/translation/pay.json
  src/main/resources/locales/en/translation/pension.json
  src/main/resources/locales/en/translation/place-of-work.json
  src/main/resources/locales/en/translation/reasonable-adjustments.json
  src/main/resources/locales/en/translation/respondent-address.json
  src/main/resources/locales/en/translation/respondent-name.json
  src/main/resources/locales/en/translation/single-or-multiple-claim.json
  src/main/resources/locales/en/translation/still-working.json
  src/main/resources/locales/en/translation/tasklist-check.json
  src/main/resources/locales/en/translation/tell-us-what-you-want.json
  src/main/resources/locales/en/translation/tribunal-recommendation.json
  src/main/resources/locales/en/translation/update-preference.json
  src/main/resources/locales/en/translation/valid-no-acas-reason.json
  src/main/resources/locales/en/translation/work-address.json
  src/main/resources/locales/en/translation/work-postcode.json
  src/test/unit/mocks/mockEt1DataModel.ts
Labels: ns:et, prd:et, rel:et-sya-pr-301

#302 RET-2068_Error_Focus
  src/main/assets/js/index.js
  src/main/assets/js/set-focus.ts
  src/main/assets/js/set-styles.ts
  src/main/assets/scss/main.scss
Labels: ns:et, prd:et, rel:et-sya-pr-302

#313 Ret 1966
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/ClaimSubmittedController.ts
  src/main/public/img/favicon.ico
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/resources/locales/en/translation/notice-length-months.json
  src/main/views/check-your-answers.njk
  src/main/views/claim-submitted.njk
  src/main/views/employer-no-longer-working.njk
  src/main/views/employer-working.njk
  src/main/views/template.njk
  src/test/unit/controller/CheckAnswers.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/claim-submitted.test.ts
  tsconfig.json
Labels: ns:et, prd:et, rel:et-sya-pr-313

#309 Ret 1975
  src/main/assets/js/address/submit.ts
  src/main/controllers/AddressDetailsController.ts
  src/main/resources/locales/en/translation/address-details.json
  src/main/resources/locales/en/translation/enter-address.json
  src/main/views/address/postcodeEnter.njk
  src/main/views/address/postcodeSelect.njk
  src/test/unit/views/address-details.test.ts
  tsconfig.json
Labels: ns:et, prd:et, rel:et-sya-pr-309

#304 RET 2085 Sign out link
  src/main/modules/oidc/index.ts
  src/main/views/template.njk
  src/test/unit/views/lip-or-representative.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-304

#312 Ret 2195 employment details final checks
  src/main/controllers/AverageWeeklyHoursController.ts
  src/main/resources/locales/en/translation/average-weekly-hours.json
  src/main/resources/locales/en/translation/benefits.json
  src/main/resources/locales/en/translation/notice-length-months.json
  src/main/resources/locales/en/translation/notice-length-weeks.json
  src/main/resources/locales/en/translation/notice-period-working.json
  src/test/unit/views/average-weekly-hours.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-312

#317 Minor updates - RET-2064 and RET-2068
  src/main/resources/locales/en/translation/lip-or-representative.json
Labels: ns:et, prd:et, rel:et-sya-pr-317

#318 Add backstage configuration file
  catalog-info.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-318

#319 Feature/refactor e2e
  .gitignore
  package.json
  src/test/end-to-end/authUser/loginIdam.js
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/config.js
  src/test/end-to-end/features/Data/commonConfig.json
  src/test/end-to-end/features/Data/test_doc.pdf
  src/test/end-to-end/features/EmploymentRespondentDetails/verifyEmploymentAndRespondentDetails.js
  src/test/end-to-end/features/WIP/authPage.js
  src/test/end-to-end/features/WIP/checkAndSubmitCliam.js
  src/test/end-to-end/features/WIP/empDetailsWhileOnNotice.js
  src/test/end-to-end/features/WIP/empDetailsWhileWorking.js
  src/test/end-to-end/features/WIP/employeeGotNewJob.js
  src/test/end-to-end/features/WIP/employeeNotWorking.js
  src/test/end-to-end/features/WIP/etCachedPageTest.js
  src/test/end-to-end/features/WIP/etClaimForSomeoneElse.js
  src/test/end-to-end/features/WIP/etMultipleClaimsForMyself.js
  src/test/end-to-end/features/WIP/etSingleClaimForMyself.js
  src/test/end-to-end/features/WIP/etStepToMakeYourClaim.js
  src/test/end-to-end/features/WIP/returnToExistingClaim.js
  src/test/end-to-end/features/yourDetails/personalDetailsTest.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/pages/IDAM/signin.js
  src/test/end-to-end/pages/employmentDetails/areYouStillWorkingForOrg.js
  src/test/end-to-end/pages/employmentDetails/didYouWorkForOrg.js
  src/test/end-to-end/pages/personalDetails/personalDetails.js
  src/test/end-to-end/pages/saveDraft/youCanSaveCard.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/saucelabs.conf.js
  src/test/end-to-end/saucelabsHelper.js
  src/test/end-to-end/supportedBrowsers.js
  src/test/functional/authUser/loginIdam.js
  src/test/functional/config.js
  src/test/functional/features/commonFlow.js
Labels: ns:et, prd:et, rel:et-sya-pr-319
