Repository hmcts/et-sya-frontend, pull requests merged in 2022-09, with the labels that each got.

#326 update fullfuntional tests on jenkins to only run RET-BAT
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-326

#321 Ret 2281 - CR: ET1 Form - Sex and Title
  src/main/components/form/validator.ts
  src/main/controllers/GenderDetailsController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantIndividual.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/gender-details.json
  src/test/routes/gender-details.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/GenderDetailsController.test.ts
  src/test/unit/controller/helpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/gender-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-321

#314 Ret 1913 respondent details validation errors
  src/main/assets/js/address/errors.ts
  src/main/assets/js/address/links.ts
  src/main/assets/js/address/submit.ts
  src/main/components/form/address_validator.ts
  src/main/components/form/validator.ts
  src/main/controllers/AcasCertNumController.ts
  src/main/controllers/AddressLookupController.ts
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/NoAcasNumberController.ts
  src/main/controllers/PlaceOfWorkController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/WorkAddressController.ts
  src/main/controllers/WorkPostcodeController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/form.ts
  src/main/resources/locales/en/translation/acas-cert-num.json
  src/main/resources/locales/en/translation/enter-address.json
  src/main/resources/locales/en/translation/no-acas-reason.json
  src/main/resources/locales/en/translation/place-of-work.json
  src/main/resources/locales/en/translation/respondent-address.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/respondent-name.json
  src/main/resources/locales/en/translation/work-address.json
  src/main/routes/routes.ts
  src/main/views/address/postcodeEnter.njk
  src/main/views/no-acas-reason.njk
  src/main/views/respondent-details-check.njk
  src/test/a11y/a11y.ts
  src/test/routes/acas-cert-num.test.ts
  src/test/routes/authenticated-routes.test.ts
  src/test/routes/place-of-work.test.ts
  src/test/unit/components/address_validator.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/AcasCertNumController.test.ts
  src/test/unit/controller/AddressLookupController.test.ts
  src/test/unit/controller/ChangeDetailsControllerTest.ts
  src/test/unit/controller/EmploymentAndRespondentCheckController.test.ts
  src/test/unit/controller/NoAcasNumController.test.ts
  src/test/unit/controller/PlaceOfWorkController.test.ts
  src/test/unit/controller/RespondentAddressController.test.ts
  src/test/unit/controller/RespondentDetailsCheckController.test.ts
  src/test/unit/controller/RespondentNameController.test.ts
  src/test/unit/controller/WorkAddressController.test.ts
  src/test/unit/controller/helpers.test.ts
  src/test/unit/mocks/mockForm.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUserCaseWithRespondent.ts
  src/test/unit/views/place-of-work.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-314

#329 Removed tag from test:functional to disable tests
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-329

#328 Remove gender details + replace with sex and title
  src/main/controllers/DobController.ts
  src/main/controllers/SexAndTitleController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/resources/locales/en/translation/sex-and-title.json
  src/main/routes/routes.ts
  src/main/views/check-your-answers.njk
  src/main/views/sex-and-title.njk
  src/test/end-to-end/pages/personalDetails/personalDetails.js
  src/test/routes/sex-and-title.test.ts
  src/test/unit/controller/DobController.test.ts
  src/test/unit/controller/SexAndTitleController.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/describe-what-happened.test.ts
  src/test/unit/views/sex-and-title.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-328

#330 Updated Jenkins_CNP config to add demo branch.
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-sya-pr-330

#316 Ret 2086 - Post login page
  src/main/controllers/ClaimantApplicationsController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/ReturnToExistingController.ts
  src/main/controllers/SelectedApplicationController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/definitions/definition.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/oidc/index.ts
  src/main/resources/locales/en/translation/claimant-applications.json
  src/main/resources/locales/en/translation/common.json
  src/main/routes/routes.ts
  src/main/services/CaseSelectionService.ts
  src/main/services/CaseService.ts
  src/main/views/claimant-applications.njk
  src/test/routes/claim-type-discrimination.test.ts
  src/test/routes/selected-application.test.ts
  src/test/unit/controller/ClaimantApplicationsController.test.ts
  src/test/unit/controller/RespondentNameController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/controller/helpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/routes/callback.test.ts
  src/test/unit/services/CaseSelectionService.test.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/claimant-applications.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
  tsconfig.json
Labels: ns:et, prd:et, rel:et-sya-pr-316

#332 enable functional tests
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-332

#320 Ret 1976
  src/main/components/form/validator.ts
  src/main/controllers/AddressDetailsController.ts
  src/main/resources/locales/en/translation/address-details.json
  src/main/resources/locales/en/translation/place-of-work.json
  src/main/resources/locales/en/translation/telephone-number.json
  src/main/views/address/postcodeError.njk
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/AddressDetailsController.test.ts
  src/test/unit/controller/TelNumberController.test.ts
  src/test/unit/views/address-details.test.ts
  src/test/unit/views/telephone-number.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-320

#315 Ret 2260. CitizenUI hub.
  src/main/app.ts
  src/main/assets/scss/main.scss
  src/main/controllers/CitizenHubController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/definition.ts
  src/main/definitions/hub.ts
  src/main/helper/ApiFormatter.ts
  src/main/helper/state-sequence.ts
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/routes/routes.ts
  src/main/services/CacheService.ts
  src/main/services/CaseService.ts
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/citizen-hub.njk
  src/test/a11y/a11y.ts
  src/test/routes/citizen-hub-controller.test.ts
  src/test/unit/controller/AcasCertNumController.test.ts
  src/test/unit/controller/ClaimantApplicationsController.test.ts
  src/test/unit/controller/RespondentAddressController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockUserCaseWithRespondent.ts
  src/test/unit/routes/callback.test.ts
  src/test/unit/services/CacheService.test.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/citizen-hub-controller.test.ts
  src/test/unit/views/claimant-applications.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-315

#336 temp disable functional and xbrowser tests
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-336

#334 Redirect to PCQ before check your answers
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/definitions/constants.ts
Labels: ns:et, prd:et, rel:et-sya-pr-334

#338 Save PCQ Id to ccd
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/helper/ApiFormatter.ts
  src/main/pcq/index.ts
  src/test/unit/controller/PcqController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-338

#341 refactor config to user playwright helper
  package.json
  src/test/end-to-end/codecept.conf.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-341

#340 Ret 1977 - PO comments
  src/main/resources/locales/en/translation/enter-address.json
  src/main/resources/locales/en/translation/notice-length-weeks.json
  src/main/views/average-weekly-hours.njk
  src/main/views/benefits.njk
  src/main/views/job-title.njk
  src/main/views/new-job-pay.njk
  src/main/views/new-job-start-date.njk
  src/main/views/new-job.njk
  src/main/views/notice-end.njk
  src/main/views/notice-length.njk
  src/main/views/pay.njk
  src/main/views/pension.njk
  src/main/views/still-working.njk
  src/main/views/template.njk
  src/test/unit/views/address-details.test.ts
  src/test/unit/views/place-of-work.test.ts
  src/test/unit/views/respondent-address.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-340

#324 Ret 2256 - add api call to front end
  package.json
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/definitions/api/documentApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/services/CaseService.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-324

#342 RET-2251
  src/main/resources/locales/en/translation/return-to-existing.json
  src/main/views/checklist.njk
  src/main/views/claimant-applications.njk
Labels: ns:et, prd:et, rel:et-sya-pr-342

#345 Add ITHC
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-sya-pr-345

#346 RET-2538. Add case service method to update a submitted case's data.
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/definitions/constants.ts
  src/main/services/CaseService.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-346

#348 RET-2530. Don't store links of hublinks, only their statuses.
  src/main/controllers/CitizenHubController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/hub.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/mocks/mockUserCaseWithCitizenHubLinks.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-348

#347 Feature/employment details journey
  src/test/end-to-end/features/EmploymentRespondentDetails/employmentStatusJourneys.js
  src/test/end-to-end/features/EmploymentRespondentDetails/respondentDetailsJourney.js
  src/test/end-to-end/features/EmploymentRespondentDetails/verifyDidYouWorkForOrg.js
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/features/yourDetails/personalDetailsTest.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/pages/employmentDetails/areYouStillWorkingForOrg.js
  src/test/end-to-end/pages/employmentDetails/noLongerWorkingPages.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/employmentDetails/stillWorkingPages.js
  src/test/end-to-end/pages/employmentDetails/workingNoticePeriodPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/end-to-end/pages/steps.js
Labels: ns:et, prd:et, rel:et-sya-pr-347

#350 Added perftest config
  config/perftest.json
Labels: ns:et, prd:et, rel:et-sya-pr-350

#351 PCQ
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
  config/custom-environment-variables.json
Labels: ns:et, prd:et, rel:et-sya-pr-351

#355 Remove question mark
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
  src/main/pcq/createToken.ts
Labels: ns:et, prd:et, rel:et-sya-pr-355

#349 Ret 1937: Describe what happened page to upload a document to dm-store
  src/main/components/form/validator.ts
  src/main/controllers/ClaimTypeDiscriminationController.ts
  src/main/controllers/ClaimTypePayController.ts
  src/main/controllers/CompensationController.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/TellUsWhatYouWantController.ts
  src/main/controllers/TribunalRecommendationController.ts
  src/main/controllers/WhistleblowingClaimsController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/claimantRequests.ts
  src/main/definitions/definition.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/claim-type-discrimination.json
  src/main/resources/locales/en/translation/compensation.json
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/main/resources/locales/en/translation/tell-us-what-you-want.json
  src/main/routes/routes.ts
  src/main/views/describe-what-happened.njk
  src/main/views/form/fields/readonly.njk
  src/main/views/form/multipartForm.njk
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/ClaimTypeDiscriminationController.test.ts
  src/test/unit/controller/ClaimTypePayController.test.ts
  src/test/unit/controller/CompensationController.test.ts
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/controller/TellUsWhatYouWantController.test.ts
  src/test/unit/controller/TribunalRecommendationController.test.ts
  src/test/unit/controller/WhistleblowingClaimsController.test.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockFile.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/claim-type-discrimination.test.ts
  src/test/unit/views/describe-what-happened.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-349

#359 Ret 2542
  Jenkinsfile_nightly
  src/test/end-to-end/features/WIP/etMultipleClaimsForMyself.js
  src/test/end-to-end/features/claimDetails/claimDetailsTest.js
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/helpers/contactUs.js
  src/test/end-to-end/pages/IDAM/signin.js
  src/test/end-to-end/pages/claimDetails/claimDet.js
  src/test/end-to-end/pages/claimDetails/claimDetails.json
  src/test/end-to-end/pages/claimDetails/claimDetailsContentHelper.js
  src/test/end-to-end/pages/steps.js
  src/test/end-to-end/pages/stepsToMakingYourClaim/stepsToMakingYourClaim.js
Labels: ns:et, prd:et, rel:et-sya-pr-359

#337 Ret 1935 - Task List 2: Respondent Details - Next layer - Save data & Final checks
  src/main/components/form/address_validator.ts
  src/main/components/form/validator.ts
  src/main/controllers/AcasCertNumController.ts
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/ClaimTypePayController.ts
  src/main/controllers/CompensationController.ts
  src/main/controllers/NoAcasNumberController.ts
  src/main/controllers/PlaceOfWorkController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/TellUsWhatYouWantController.ts
  src/main/controllers/TribunalRecommendationController.ts
  src/main/controllers/WorkAddressController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/complexTypes/workAddressDetails.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/en/translation/address-details.json
  src/main/resources/locales/en/translation/no-acas-reason.json
  src/main/resources/locales/en/translation/place-of-work.json
  src/main/resources/locales/en/translation/respondent-address.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/respondent-name.json
  src/main/views/address/postcodeEnter.njk
  src/main/views/respondent-details-check.njk
  src/test/routes/place-of-work.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/AcasCertNumController.test.ts
  src/test/unit/controller/NoAcasNumController.test.ts
  src/test/unit/controller/PlaceOfWorkController.test.ts
  src/test/unit/controller/RespondentAddressController.test.ts
  src/test/unit/controller/RespondentNameController.test.ts
  src/test/unit/controller/WorkAddressController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-337

#364 RET-2556 - fix invalid acas certificate in func test
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-364

#362 Ret 2554
  src/main/pcq/index.ts
  src/test/unit/controller/PcqController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-362

#366 Ret 2571
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/helpers/commonFlowLocators.json
Labels: ns:et, prd:et, rel:et-sya-pr-366

#365 RET-2331: Fix callback tests et-sya-frontend
  src/test/unit/routes/callback.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-365

#363 RET-2569: Fix file format error not appearing
  src/main/components/form/validator.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/mocks/mockFile.ts
Labels: ns:et, prd:et, rel:et-sya-pr-363
