Repository hmcts/et-sya-frontend, pull requests merged in 2022-03, with the labels that each got.

#127 fix master deployment
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-127

#121 RET-1007 notice period
  src/main/components/form/validator.ts
  src/main/controllers/helpers.ts
  src/main/controllers/multiple_respondent/content.ts
  src/main/controllers/notice_period/NoticePeriodController.ts
  src/main/controllers/notice_period/content.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/en/translation/notice-period.json
  src/main/routes/routes.ts
  src/main/views/form/fields/radios.njk
  src/main/views/notice-period.njk
  src/test/routes/notice-period.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/NoticePeriodController.test.ts
  src/test/unit/views/notice-period.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-121

#122 Ret 943
  charts/et-sya/Chart.yaml
  charts/et-sya/values.aat.template.yaml
  charts/et-sya/values.preview.template.yaml
  charts/et-sya/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  jest.config.js
  package.json
  sonar-project.properties
  src/main/address/index.ts
  src/main/assets/js/address/errors.ts
  src/main/assets/js/address/links.ts
  src/main/assets/js/address/select.ts
  src/main/assets/js/address/submit.ts
  src/main/assets/js/enter-address.ts
  src/main/assets/js/index.js
  src/main/assets/js/selectors.ts
  src/main/assets/scss/main.scss
  src/main/controllers/AddressLookupController.ts
  src/main/controllers/place_of_work/PlaceOfWorkController.ts
  src/main/controllers/place_of_work/content.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/properties-volume/index.ts
  src/main/resources/locales/en/translation/enter-address.json
  src/main/resources/locales/en/translation/place-of-work.json
  src/main/routes/routes.ts
  src/main/views/address/postcodeEnter.njk
  src/main/views/address/postcodeError.njk
  src/main/views/address/postcodeSelect.njk
  src/main/views/place-of-work.njk
  src/test/routes/place-of-work.test.ts
  src/test/unit/address/address-lookup.test.ts
  src/test/unit/controller/AddressLookupController.test.ts
  src/test/unit/controller/PlaceOfWorkController.test.ts
  src/test/unit/mocks/mockPostcodeResponses.ts
  src/test/unit/mocks/mockedAddressLookupResponse.ts
  src/test/unit/views/place-of-work.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-122

#129 trying to fix aat
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-129

#130 pupeeteer skip download
  Dockerfile
Labels: ns:et, prd:et, rel:et-sya-pr-130

#119 RET-1087: Added the task list to the steps to making your claim page
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/resources/locales/en/translation/steps-to-making-your-claim.json
  src/main/views/steps-to-making-your-claim.njk
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-119

#152 Replace dependabot with renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:et, prd:et, rel:et-sya-pr-152

#147 Feature/RET-943 automation
  src/test/functional/features/placeOfWork.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-147

#156 update helm versions
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-156

#157 employmeent details while working and on notice - automation
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/functional/features/empDetailsWhileWorking.js
Labels: ns:et, prd:et, rel:et-sya-pr-157

#155 Initial pact test between et-sya and idam
  api/test/pact/pacts/et-sya-idamapi_users.json
  jest.pact.config.js
  package.json
  src/test/api/pact/pact-test/idam/get-user-details.test.ts
  src/test/api/pact/pact-test/settings/provider.mock.ts
  src/test/api/pact/pactUtil.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-155

#160 bump helm chart to v2.4.3
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-160

#146 RET 1178 - 'Check your answers' and 'Your claim has been submitted' skeleton pages.
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/ClaimSubmittedController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/routes/routes.ts
  src/main/views/check-your-answers.njk
  src/main/views/claim-submitted.njk
  src/test/routes/check-your-answers.test.ts
  src/test/routes/claim-submitted.test.ts
  src/test/unit/controller/CheckAnswers.test.ts
  src/test/unit/controller/ClaimSubmitted.test.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/claim-submitted.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-146

#158 Feature/ret 1178
  src/test/functional/features/checkAndSubmitCliam.js
Labels: ns:et, prd:et, rel:et-sya-pr-158

#162 update renovate config and packages
  .github/renovate.json
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-162

#164 RET-1169 task list 2 still working
  src/main/controllers/PastEmployerController.ts
  src/main/controllers/PresentEmployerController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/UpdatePreferenceController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/awilix/index.ts
  src/main/resources/locales/en/translation/template.json
  src/main/resources/locales/en/translation/update-preference.json
  src/test/routes/acas-multiple.test.ts
  src/test/routes/acas-single-claim.test.ts
  src/test/routes/address-details.test.ts
  src/test/routes/checklist.test.ts
  src/test/routes/contact-acas.test.ts
  src/test/routes/date-of-birth.test.ts
  src/test/routes/gender-details.test.ts
  src/test/routes/lip-or-representative.test.ts
  src/test/routes/mutiple-respondent-check.test.ts
  src/test/routes/new-account-landing.test.ts
  src/test/routes/past-employer.test.ts
  src/test/routes/present-employer.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/routes/telephone-number.test.ts
  src/test/routes/type-of-claim.test.ts
  src/test/routes/update-preference.test.ts
  src/test/routes/valid-no-acas-reason.test.ts
  src/test/routes/video-hearings.test.ts
  src/test/routes/you-claim-has-been-saved.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/views/update-preference.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-164

#173 Add yarn-audit-known-issues for minimist, updates ts-config-paths, config, codeceptjs versions
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-173

#144 RET 1214 - Reasonable Adjustments checkbox skeleton pages
  src/main/controllers/ComfortableController.ts
  src/main/controllers/CommunicatingController.ts
  src/main/controllers/DocumentsController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/controllers/SupportController.ts
  src/main/controllers/TravelController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/comfortable.json
  src/main/resources/locales/en/translation/communicating.json
  src/main/resources/locales/en/translation/documents.json
  src/main/resources/locales/en/translation/reasonable-adjustments.json
  src/main/resources/locales/en/translation/support.json
  src/main/resources/locales/en/translation/travel.json
  src/main/routes/routes.ts
  src/main/views/generic-form-template.njk
  src/test/routes/comfortable.test.ts
  src/test/routes/communicating.test.ts
  src/test/routes/documents.test.ts
  src/test/routes/reasonable-adjustments.test.ts
  src/test/routes/support.test.ts
  src/test/routes/travel.test.ts
  src/test/unit/controller/ComfortableController.test.ts
  src/test/unit/controller/CommunicatingController.test.ts
  src/test/unit/controller/DocumentsController.test.ts
  src/test/unit/controller/ReasonableAdjustmentsController.test.ts
  src/test/unit/controller/SupportController.test.ts
  src/test/unit/controller/TravelController.test.ts
  src/test/unit/views/comfortable.test.ts
  src/test/unit/views/communicating.test.ts
  src/test/unit/views/documents.test.ts
  src/test/unit/views/reasonable-adjustments.test.ts
  src/test/unit/views/support.test.ts
  src/test/unit/views/travel.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-144

#163 Ret 1006 employment start date
  src/main/components/form/validator.ts
  src/main/controllers/DobController.ts
  src/main/controllers/StartDateController.ts
  src/main/controllers/helpers.ts
  src/main/definitions/case.ts
  src/main/definitions/dates.ts
  src/main/resources/locales/en/translation/start-date.json
  src/main/views/start-date.njk
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/functional/features/empDetailsWhileWorking.js
  src/test/functional/features/employeeNotWorking.js
  src/test/routes/start-date.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/DobController.test.ts
  src/test/unit/controller/StartDateController.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/views/start-date.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-163

#172 RET-1236: Check and Submit - Next layer - Contents
  src/main/assets/js/index.js
  src/main/assets/js/print.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/views/check-your-answers.njk
  src/main/views/employer-no-longer-working.njk
  src/main/views/employer-notice.njk
  src/main/views/employer-working.njk
  src/main/views/respondent-details-no-acas.njk
  src/main/views/respondent-details.njk
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-172

#168 Add Pact Test to Pipeline
  .gitignore
  Jenkinsfile_CNP
  api/test/pact/pacts/et-sya-idamapi_users.json
  config/default.json
  jest.pact.config.js
  package.json
  src/main/assets/js/print.ts
  src/test/api/configuration/constants.ts
  src/test/api/configuration/health.ts
  src/test/api/configuration/index.ts
  src/test/api/configuration/references.ts
  src/test/api/configuration/ui.config.ts
  src/test/api/configuration/ui.ts
  src/test/api/pact/cer/ca-bundle.crt
  src/test/api/pact/pact-test/idam/get-user-details.test.ts
  src/test/api/pact/pact-test/settings/provider.mock.ts
  src/test/api/pact/pactUtil.ts
  src/test/api/pact/publish/publish.ts
  src/test/unit/views/check-your-answers.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-168

#185 smoke test added for et frontend application
  .gitignore
  jest.smoke.config.js
  package.json
  src/test/smoke/codecept.smoke.conf.js
  src/test/smoke/healthChech.test.ts
  src/test/smoke/pages/steps.js
  src/test/smoke/smoke.conf.js
  src/test/smoke/tests/healthCheck.test.js
Labels: ns:et, prd:et, rel:et-sya-pr-185

#184 Ret 1236
  src/main/views/check-your-answers.njk
  src/main/views/employer-no-longer-working.njk
  src/main/views/employer-notice.njk
  src/main/views/employer-working.njk
  src/main/views/respondent-details-no-acas.njk
  src/main/views/respondent-details.njk
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-184

#182 [RET-1231] Employment Details - Next Layer (Content)
  src/main/controllers/AverageWeeklyHoursController.ts
  src/main/controllers/BenefitsController.ts
  src/main/controllers/PayAfterTaxController.ts
  src/main/controllers/PayBeforeTaxController.ts
  src/main/controllers/StartDateController.ts
  src/main/definitions/case.ts
  src/main/definitions/radios.ts
  src/main/resources/locales/en/translation/average-weekly-hours.json
  src/main/resources/locales/en/translation/benefits.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/end-date.json
  src/main/resources/locales/en/translation/pay-after-tax.json
  src/main/resources/locales/en/translation/pay-before-tax.json
  src/main/resources/locales/en/translation/start-date.json
  src/main/views/average-weekly-hours.njk
  src/main/views/benefits.njk
  src/main/views/form/fields/charCount.njk
  src/main/views/form/fields/currency.njk
  src/main/views/pay-after-tax.njk
  src/main/views/pay-before-tax.njk
  src/main/views/start-date.njk
  src/test/functional/features/empDetailsWhileOnNotice.js
  src/test/functional/features/empDetailsWhileWorking.js
  src/test/routes/average-weekly-hours.test.ts
  src/test/routes/pay-after-tax.test.ts
  src/test/routes/pay-before-tax.test.ts
  src/test/routes/start-date.test.ts
  src/test/unit/views/average-weekly-hours.test.ts
  src/test/unit/views/benefits.test.ts
  src/test/unit/views/pay-after-tax.test.ts
  src/test/unit/views/pay-before-tax.test.ts
  src/test/unit/views/start-date.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-182

#165 RET-881 Current Work Address
  src/main/components/form/validator.ts
  src/main/controllers/PlaceOfWorkController.ts
  src/main/resources/locales/en/translation/place-of-work.json
  src/main/views/place-of-work.njk
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/PlaceOfWorkController.test.ts
  src/test/unit/views/place-of-work.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-165
