Repository hmcts/et-sya-frontend, pull requests merged in 2023-08, with the labels that each got.

#928 fix failing test on RET-3862
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-928

#931 Update CitizenHubController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-931

#932 Disable all docs
  src/main/controllers/citizen-hub/CitizenHubController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-932

#934 Update tags
  infrastructure/main.tf
Labels: ns:et, prd:et, no-changes, rel:et-sya-pr-934

#901 PET-1.1.2.3
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
  config/custom-environment-variables.json
  config/default.json
  src/main/controllers/AcasCertNumController.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/NoAcasNumberController.ts
  src/main/controllers/RespondentAddInCheckAnswerController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/RespondentRemoveController.ts
  src/main/controllers/ReturnToExistingController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/cy/translation/response-from-respondent.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/response-from-respondent.json
  src/main/resources/locales/en/translation/template.json
  src/main/utils/getLegacyUrlFromLng.ts
  src/main/views/check-your-answers.njk
  src/main/views/claim-details.njk
  src/main/views/respondent-details-check.njk
  src/main/views/response-from-respondent-view.njk
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/helpers/contactUs.js
  src/test/end-to-end/helpers/contactUsForCitizenHub.js
  src/test/end-to-end/pages/citizenHub/citizenHub.js
  src/test/routes/return-to-existing.test.ts
  src/test/unit/controller/RespondentAddInCheckAnswerController.test.ts
  src/test/unit/controller/RespondentRemoveController.test.ts
  src/test/unit/utils/getLegacyUrlFromLng.test.ts
  src/test/unit/views/respondent-details-check.test.ts
  src/test/unit/views/response-from-respondent-view.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-901

#935 separate nightly and master username credential
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-935

#937 RET-4060 Update IDAM port to 5062
  config/development.json
  infrastructure/state.tf
  package.json
  src/main/modules/helmet/index.ts
  yarn.lock
Labels: ns:et, prd:et, destroy, rel:et-sya-pr-937

#933 Alter contact us span for google analytics
  src/main/views/template.njk
Labels: ns:et, prd:et, rel:et-sya-pr-933

#924 Ret 3862 - Capture Respondent name/s in correct format
  charts/et-sya/Chart.yaml
  src/main/controllers/AcasCertNumController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/RespondentPostCodeEnterController.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/cy/translation/respondent-name.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/respondent-name.json
  src/main/views/respondent-name.njk
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
  src/test/end-to-end/helpers/caseHelper.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/routes/respondent-name.test.ts
  src/test/unit/controller/RespondentNameController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockUserCaseClaimDetails.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockUserCaseWithDocumentsComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/views/respondent-address.test.ts
  src/test/unit/views/respondent-details-check.test.ts
  src/test/unit/views/respondent-name.test.ts
  yarn.lock
Labels: ns:et, prd:et, no-changes, rel:et-sya-pr-924

#947 Add ID to the Sidebar contact us details component
  src/main/views/citizen-hub.njk
Labels: ns:et, prd:et, rel:et-sya-pr-947

#949 Switch from ts-jest to swc for monstrous test speedup
  .gitignore
  .swcrc
  jest.pact.config.js
  jest.routes.config.js
  jest.unit.config.js
  jest.views.config.js
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-949

#956 RET-4086: Removed passing res to helper functions
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/JudgmentDetailsController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/JudgmentHelpers.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/test/unit/controller/ApplicationDetailsController.test.ts
  src/test/unit/controller/JudgmentDetailsController.test.ts
  src/test/unit/controller/RespondToTribunalResponseController.test.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/mocks/mockDocumentDetailsResponse.ts
  src/test/unit/mocks/mockRequest.ts
Labels: ns:et, prd:et, rel:et-sya-pr-956

#953 RET-3802
  package.json
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/definitions/case.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/common.json
  src/main/views/error-summary.njk
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-953

#958 Redirect start to legacy
  package.json
  src/main/controllers/HomeController.ts
  src/test/unit/controller/HomeController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-958

#959 Add code back into package.json
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-959

#960 Revert redirect change
  package.json
  src/main/controllers/HomeController.ts
  src/test/unit/controller/HomeController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-960
