Repository hmcts/et-sya-frontend, pull requests merged in 2023-05, with the labels that each got.

#782 RET 3091 Upload hearing document
  src/main/components/form/validator.ts
  src/main/controllers/AboutHearingDocumentsController.ts
  src/main/controllers/HearingDocumentFileController.ts
  src/main/controllers/HearingDocumentUploadController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/controllers/helpers/FormHelpers.ts
  src/main/controllers/helpers/HearingDocumentUploadHelper.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/hearing-document-upload.json
  src/main/resources/locales/en/translation/hearing-document-upload.json
  src/main/views/hearing-document-upload.njk
  src/test/unit/controller/AboutHearingDocumentsController.test.ts
  src/test/unit/controller/HearingDocumentUploadController.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockFile.ts
  src/test/unit/views/about-hearing-documents.test.ts
  src/test/unit/views/hearing-document-upload.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-782

#781 Test coverage
  src/main/definitions/constants.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/YourAppsToTheTribunalController.test.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-781

#788 Ret 3471 titles added
  src/main/controllers/AddressPostCodeEnterController.ts
  src/main/controllers/AddressPostCodeSelectController.ts
  src/main/controllers/RespondentPostCodeEnterController.ts
  src/main/controllers/RespondentPostCodeSelectController.ts
  src/main/controllers/WorkPostCodeEnterController.ts
  src/main/controllers/WorkPostCodeSelectController.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/common.json
Labels: ns:et, prd:et, rel:et-sya-pr-788

#789 Ret 3093 - Add Bundles Completed page
  src/main/controllers/BundlesCompletedController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/bundles-completed.json
  src/main/resources/locales/en/translation/bundles-completed.json
  src/main/views/bundles-completed.njk
  src/test/routes/bundles-completed.test.ts
  src/test/unit/controller/BundlesCompletedController.test.ts
  src/test/unit/views/bundles-completed.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-789

#790 Code smells
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
Labels: ns:et, prd:et, rel:et-sya-pr-790

#793 RET-3154
  src/main/controllers/AllDocumentsController.ts
  src/main/controllers/AttachmentController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/documentTypeItem.ts
  src/main/definitions/complexTypes/sendNotificationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/definitions/hub.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/pcq/index.ts
  src/main/resources/locales/cy/translation/all-documents.json
  src/main/resources/locales/en/translation/all-documents.json
  src/main/views/all-documents.njk
  src/test/unit/controller/AllDocumentsController.test.ts
  src/test/unit/controller/ApplicationDetailsController.test.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/helpers/AllDocumentsHelper.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
  src/test/unit/controller/helpers/RespondentApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/controller/helpers/TseRespondentApplicationHelpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockUserCaseWithRespondentDocuments.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/utils/createToken.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-793

#795 Update Dockerfile
  Dockerfile
Labels: ns:et, prd:et, rel:et-sya-pr-795

#797 RET-3585
  src/main/components/form/validator.ts
  src/test/unit/components/validator.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-797

#798 RET-3585 (#797)
  sonar-project.properties
  src/main/components/form/validator.ts
  src/test/unit/components/validator.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-798

#800 Test coverage
  src/main/controllers/helpers/DocumentHelpers.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/controller/helpers/JudgmentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-800

#802 RET-3345
  src/main/controllers/AttachmentController.ts
  src/main/controllers/helpers/JudgmentHelpers.ts
Labels: ns:et, prd:et, rel:et-sya-pr-802

#805 stubbed postcode addresses made lower case
  src/main/controllers/AddressLookupController.ts
  src/test/unit/controller/AddressLookupController.test.ts
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-805

#806 Ret 3089 - Bundles- Have you agreed documents with other party screen
  src/main/controllers/AgreeingDocumentsForHearingController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/agreeing-documents-for-hearing.json
  src/main/resources/locales/en/translation/agreeing-documents-for-hearing.json
  src/main/views/agreeing-documents-for-hearing.njk
  src/test/routes/agreeing-documents-for-hearing.test.ts
  src/test/unit/views/agreeing-documents-for-hearing.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-806

#808 RET-3121
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-808

#812 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-812

#814 RET-3696
  src/main/resources/locales/cy/translation/claim-submitted.json
  src/main/resources/locales/en/translation/claim-submitted.json
Labels: ns:et, prd:et, rel:et-sya-pr-814

#811 duplicate acas number validation
  src/main/components/form/validator.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/resources/locales/cy/translation/acas-cert-num.json
  src/main/resources/locales/en/translation/acas-cert-num.json
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-811

#817 RET-3696
  src/main/controllers/ClaimSubmittedController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-817

#818 RET-3452
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/helpers/FormHelpers.ts
  src/main/resources/locales/cy/translation/check-your-answers.json
  src/main/resources/locales/en/translation/check-your-answers.json
Labels: ns:et, prd:et, rel:et-sya-pr-818

#821 RET-3732
  src/main/controllers/AddressPostCodeEnterController.ts
  src/main/controllers/RespondentPostCodeEnterController.ts
  src/main/controllers/WorkPostCodeEnterController.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/common.json
  src/main/views/address-postcode-enter.njk
  src/main/views/respondent-postcode-enter.njk
  src/main/views/work-postcode-enter.njk
Labels: ns:et, prd:et, rel:et-sya-pr-821

#820 RET-3727
  src/main/controllers/helpers/RespondentAnswersHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-820

#822 Ret 3732
  src/test/unit/components/form.test.ts
  src/test/unit/controller/AddressPostCodeEnterController.test.ts
  src/test/unit/controller/RespondentPostCodeEnterController.test.ts
  src/test/unit/controller/WorkPostCodeEnterController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-822

#807 RET-3594: Adding Rule92 holding page
  package.json
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/Rule92HoldingPageController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/representative.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/rule92-holding-page.json
  src/main/resources/locales/en/translation/rule92-holding-page.json
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/citizen-hub.njk
  src/main/views/rule92-holding-page.njk
  src/test/end-to-end/helpers/contactUsForCitizenHub.js
  src/test/end-to-end/pages/citizenHub/citizenHub.js
  src/test/routes/rule92-holding-page.test.ts
  src/test/unit/controller/Rule92HoldingPageController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/views/rule92-holding-page.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-807

#827 RET-3739
  src/main/controllers/SexAndTitleController.ts
  src/main/resources/locales/cy/translation/sex-and-title.json
  src/main/resources/locales/en/translation/sex-and-title.json
  src/main/views/form/form.njk
Labels: ns:et, prd:et, rel:et-sya-pr-827

#830 Make field optional
  src/test/unit/controller/SexAndTitleController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-830
