Repository hmcts/et-sya-frontend, pull requests merged in 2023-11, with the labels that each got.

#1045 RET-4029 - Welsh translations for application complete
  src/main/controllers/ApplicationCompleteController.ts
  src/main/resources/locales/cy/translation/application-complete.json
  src/test/routes/application-complete.test.ts
  src/test/unit/controller/ApplicationCompleteController.test.ts
  src/test/unit/views/application-complete.test.ts
Labels: ns:et, prd:et, no-changes, enable_keep_helm, rel:et-sya-pr-1045

#1053 Ret 4037 - add Welsh translations
  src/main/controllers/RespondToApplicationCompleteController.ts
  src/main/controllers/TribunalResponseCompletedController.ts
  src/main/resources/locales/cy/translation/respond-to-application-complete.json
  src/main/resources/locales/cy/translation/tribunal-response-completed.json
  src/test/routes/respond-to-application-complete.test.ts
  src/test/unit/controller/RespondToApplicationCompleteController.test.ts
  src/test/unit/controller/TribunalResponseCompletedController.test.ts
  src/test/unit/views/respond-to-application-complete.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1053

#1081 RET-4062 - Update api links
  src/main/definitions/constants.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1081

#1001 Ret 3729 - add Welsh translations
  src/main/controllers/ContactTheTribunalController.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/en/translation/contact-the-tribunal.json
  src/main/views/components/accordion/macro.njk
  src/main/views/components/accordion/template.njk
  src/main/views/contact-the-tribunal.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1001

#1082 Update bundles endpoint
  src/main/definitions/constants.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1082

#975 RET-3747 Welsh feature flag and cya translation
  .yarnrc.yml
  src/main/controllers/ContactTheTribunalCYAController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/controllers/RespondentApplicationCYAController.ts
  src/main/controllers/SubmitRespondentController.ts
  src/main/controllers/SubmitTribunalCYAController.ts
  src/main/controllers/TribunalResponseCYAController.ts
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
  src/main/modules/helmet/index.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/en/translation/common.json
  src/main/views/template.njk
  src/test/routes/citizen-hub.test.ts
  src/test/routes/copy-to-other-party.test.ts
  src/test/unit/controller/ContactTheTribunalCYAController.test.ts
  src/test/unit/controller/ContactTheTribunalController.test.ts
  src/test/unit/controller/CopyToOtherPartyController.test.ts
  src/test/unit/controller/RespondentApplicationCYAController.test.ts
  src/test/unit/controller/SubmitRespondentController.test.ts
  src/test/unit/controller/TribunalResponseCYAController.test.ts
  src/test/unit/controller/citizen-hub/CitizenHubController.test.ts
  src/test/unit/controller/helpers/ContactTheTribunalCYAHelper.test.ts
  src/test/unit/controller/helpers/RespondentApplcationCYAHelper.test.ts
  src/test/unit/views/citizen-hub.test.ts
  src/test/unit/views/copy-to-other-party.test.ts
  src/test/unit/views/respond-to-application-complete.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-975

#1028 Ret 4034 - add Welsh translations
  src/main/controllers/RespondToApplicationController.ts
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/test/unit/controller/RespondToApplicationController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1028

#1022 Translations for various pages
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/GeneralCorrespondenceListController.ts
  src/main/controllers/GeneralCorrespondenceNotificationDetailsController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/YourAppsToTheTribunalController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/GeneralCorrespondenceHelper.ts
  src/main/helper/dateInLocale.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/locales/cy/translation/general-correspondence-list.json
  src/main/resources/locales/cy/translation/general-correspondence-notification-details.json
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/cy/translation/your-applications.json
  src/main/views/general-correspondence-list.njk
  src/main/views/general-correspondence-notification-details.njk
  src/main/views/respond-to-application.njk
  src/main/views/your-applications.njk
  src/test/unit/controller/GeneralCorrespondenceListController.test.ts
  src/test/unit/controller/GeneralCorrespondenceNotificationDetailsController.test.ts
  src/test/unit/controller/RespondToApplicationController.test.ts
  src/test/unit/controller/YourAppsToTheTribunalController.test.ts
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/GeneralCorrespondenceHelper.test.ts
  src/test/unit/controller/helpers/RespondentApplicationDetailsHelper.test.ts
  src/test/unit/helper/dateInLocale.test.ts
  src/test/unit/views/application-details.test.ts
Labels: ns:et, prd:et, add-or-update, enable_keep_helm, rel:et-sya-pr-1022

#936 RET-4043 -Fix open redirects
  .husky/pre-push
  src/main/controllers/ContactTheTribunalFileController.ts
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/RespondentSupportingMaterialFileController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/helpers/RouterHelpers.ts
  src/test/unit/controller/ContactTheTribunalFileController.test.ts
  src/test/unit/controller/RespondToApplicationController.test.ts
  src/test/unit/controller/RespondToTribunalResponseController.test.ts
  src/test/unit/controller/RespondentSupportingMaterialFileController.test.ts
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  src/test/unit/controller/helpers/RouterHelpers.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUrl.ts
Labels: ns:et, prd:et, rel:et-sya-pr-936, enable_keep_helm

#1086 RET-4043 remove duplicate getlogger import
  src/main/controllers/TribunalRespondToOrderController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1086

#1089 Revert accordian
  src/main/controllers/ContactTheTribunalController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1089

#1010 RET-4049 & 4053 -Add translations to application detail pages
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/DateHelper.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/cy/translation/respond-to-tribunal-response.json
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/cy/translation/your-applications.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/resources/locales/en/translation/respond-to-tribunal-response.json
  src/main/resources/locales/en/translation/respondent-application-details.json
  src/main/views/application-details.njk
  src/main/views/respondent-application-details.njk
  src/test/routes/application-details.test.ts
  src/test/unit/controller/ApplicationDetailsController.test.ts
  src/test/unit/controller/RespondToTribunalResponseController.test.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/RespondentApplicationDetailsHelper.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/views/application-details.test.ts
  src/test/unit/views/respond-to-tribunal-response.test.ts
  src/test/unit/views/respondent-application-details.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1010

#1094 Ret 3741 - Application specific content in Welsh
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/helpers/ContactApplicationHelper.ts
  src/main/controllers/helpers/LanguageHelper.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal-amend.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-change-details.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-non-compliance.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-other.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-postpone.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-publicity.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-reconsider-decision.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-reconsider-judgement.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-respondent.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-strike.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-vary.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-withdraw.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-witness.json
  src/main/resources/locales/en/translation/contact-the-tribunal-amend.json
  src/main/resources/locales/en/translation/contact-the-tribunal-change-details.json
  src/main/resources/locales/en/translation/contact-the-tribunal-non-compliance.json
  src/main/resources/locales/en/translation/contact-the-tribunal-other.json
  src/main/resources/locales/en/translation/contact-the-tribunal-postpone.json
  src/main/resources/locales/en/translation/contact-the-tribunal-publicity.json
  src/main/resources/locales/en/translation/contact-the-tribunal-reconsider-decision.json
  src/main/resources/locales/en/translation/contact-the-tribunal-reconsider-judgement.json
  src/main/resources/locales/en/translation/contact-the-tribunal-respondent.json
  src/main/resources/locales/en/translation/contact-the-tribunal-strike.json
  src/main/resources/locales/en/translation/contact-the-tribunal-vary.json
  src/main/resources/locales/en/translation/contact-the-tribunal-withdraw.json
  src/main/resources/locales/en/translation/contact-the-tribunal-witness.json
  src/main/views/contact-the-tribunal-selected.njk
  src/test/end-to-end/codecept.conf.js
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
  yarn.lock
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1094

#1101 RET-3088 Add bundles to contact tribunal page
  src/main/controllers/ContactTheTribunalController.ts
  src/main/controllers/PrepareDocumentsController.ts
  src/test/unit/controller/AboutHearingDocumentsController.test.ts
  src/test/unit/controller/ContactTheTribunalController.test.ts
  src/test/unit/mocks/mockHearing.ts
  src/test/unit/views/prepare-documents.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1101

#1103 RET-4057 - add missed translation for document
  src/main/controllers/helpers/GeneralCorrespondenceHelper.ts
  src/main/resources/locales/cy/translation/general-correspondence-notification-details.json
  src/main/resources/locales/en/translation/general-correspondence-notification-details.json
Labels: ns:et, prd:et, rel:et-sya-pr-1103

#1104 Ret 4041 - Application & Case Management: All documents page in Welsh
  src/main/controllers/AllDocumentsController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/resources/locales/cy/translation/all-documents.json
  src/main/resources/locales/cy/translation/respondent-applications.json
  src/main/resources/locales/en/translation/respondent-applications.json
  src/main/views/all-documents.njk
  src/test/unit/controller/helpers/AllDocumentsHelper.test.ts
  src/test/unit/views/application-details.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1104

#1102 RET-4512 Redirects Logging
  src/main/modules/oidc/index.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1102

#1108 RET-3091 - update Scottish venue and document link for bundles
  src/main/controllers/helpers/FormHelpers.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/resources/locales/en/translation/hearing-document-upload.json
Labels: ns:et, prd:et, rel:et-sya-pr-1108

#1112 Ret 4535 - Welsh Translation Amendments
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/definitions/radios.ts
  src/main/helper/dateInLocale.ts
  src/main/resources/locales/cy/translation/application-complete.json
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/cy/translation/respondent-applications.json
  src/main/resources/locales/cy/translation/sidebar-contact-us.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/views/citizen-hub-notification-banner.njk
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/RespondentApplicationDetailsHelper.test.ts
  src/test/unit/helper/dateInLocale.test.ts
  src/test/unit/views/respond-to-tribunal-response.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1112

#1109 Ret 4521 - Missing translations for All orders and requests and All judgements
  src/main/controllers/AllJudgmentsController.ts
  src/main/controllers/JudgmentDetailsController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/JudgmentHelpers.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/resources/locales/cy/translation/all-judgments.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/judgment-details.json
  src/main/resources/locales/cy/translation/respond-to-tribunal-response.json
  src/main/resources/locales/cy/translation/tribunal-order-or-request-details.json
  src/main/resources/locales/cy/translation/tribunal-orders-and-requests.json
  src/main/resources/locales/cy/translation/tribunal-respond-to-order.json
  src/main/resources/locales/cy/translation/tribunal-response-cya.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/judgment-details.json
  src/main/resources/locales/en/translation/tribunal-order-or-request-details.json
  src/main/resources/locales/en/translation/tribunal-respond-to-order.json
  src/main/views/all-judgments.njk
  src/main/views/judgment-details.njk
  src/main/views/tribunal-order-or-request-details.njk
  src/main/views/tribunal-orders-and-requests.njk
  src/main/views/tribunal-respond-to-order.njk
  src/test/unit/controller/AllJudgmentsController.test.ts
  src/test/unit/controller/JudgmentDetailsController.test.ts
  src/test/unit/controller/TribunalOrderOrRequestDetailsController.test.ts
  src/test/unit/controller/TribunalOrdersAndRequestsController.test.ts
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockNotificationItem.ts
  src/test/unit/views/all-judgments.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1109

#1119 add missing translation on the supporting material page
  src/main/resources/locales/cy/translation/respondent-supporting-material.json
Labels: ns:et, prd:et, rel:et-sya-pr-1119

#1118 RET-3093 4400 - View bundle pdfs on all documents page of citizen hub
  src/main/controllers/AllDocumentsController.ts
  src/main/controllers/AttachmentController.ts
  src/main/controllers/BundlesDocsForHearingCYAController.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/bundles-completed.json
  src/main/resources/locales/cy/translation/bundles-docs-for-hearing-cya.json
  src/main/resources/locales/en/translation/bundles-completed.json
  src/main/resources/locales/en/translation/bundles-docs-for-hearing-cya.json
  src/main/services/CaseService.ts
  src/test/unit/controller/AllDocumentsController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/controller/helpers/AllDocumentsHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1118

#1117 RET-3089 - Bundles- Have you agreed documents with other party screen
  src/main/controllers/AgreeingDocumentsForHearingController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/test/routes/agreeing-documents-for-hearing.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1117

#1122 RET-4400 - update format of hearing label
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/FormHelpers.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/helpers/FormHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockHearing.ts
  src/test/unit/views/about-hearing-documents.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1122

#1126 RET-4535 - Fix translation
  src/main/controllers/RespondentApplicationCYAController.ts
  src/main/controllers/TribunalResponseCYAController.ts
  src/main/controllers/helpers/RespondentApplicationCYAHelper.ts
  src/main/resources/locales/cy/translation/respondent-application-cya.json
  src/main/resources/locales/cy/translation/tribunal-response-cya.json
  src/main/resources/locales/en/translation/respondent-application-cya.json
  src/main/resources/locales/en/translation/tribunal-response-cya.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1126

#1127 RET-4535 - Fix Welsh navigation
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/helpers/RespondentSupportingMaterialHelper.ts
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
  src/test/unit/controller/helpers/RespondentSupportingMaterialHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1127

#1130 Fix sidebar wrapping
  src/main/views/citizen-hub-sidebar.njk
Labels: ns:et, prd:et, rel:et-sya-pr-1130

#1131 Fix sidebar width
  src/main/views/citizen-hub-sidebar-3rd-width.njk
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/judgment-details.njk
  src/main/views/respondent-application-details.njk
  src/main/views/tribunal-order-or-request-details.njk
Labels: ns:et, prd:et, rel:et-sya-pr-1131
