Repository hmcts/et-sya-frontend, pull requests merged in 2023-12, with the labels that each got.

#1132 RET-4521-Welsh fixes
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/views/citizen-hub-sidebar-3rd-width.njk
  src/main/views/judgment-details.njk
  src/main/views/respondent-application-details.njk
  src/main/views/tribunal-order-or-request-details.njk
  src/test/unit/views/respondent-application-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1132

#1139 Merge master to Rule-92_New branch
  src/main/controllers/RespondentApplicationCYAController.ts
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/TribunalResponseCYAController.ts
  src/main/controllers/helpers/RespondentApplicationCYAHelper.ts
  src/main/controllers/helpers/RespondentSupportingMaterialHelper.ts
  src/main/resources/locales/cy/translation/respondent-application-cya.json
  src/main/resources/locales/cy/translation/tribunal-response-cya.json
  src/main/resources/locales/en/translation/respondent-application-cya.json
  src/main/resources/locales/en/translation/tribunal-response-cya.json
  src/main/views/judgment-details.njk
  src/main/views/respondent-application-details.njk
  src/main/views/tribunal-order-or-request-details.njk
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
  src/test/unit/controller/helpers/RespondentSupportingMaterialHelper.test.ts
  src/test/unit/views/respondent-application-details.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1139

#1135 Create ECC notifications
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/index.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/views/citizen-hub-notification-banner.njk
  src/test/unit/controller/TribunalOrdersAndRequestsController.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockNotificationItem.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1135

#1147 RET-4062 getSupportingMaterial
  src/main/controllers/AttachmentController.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/test/unit/controller/helpers/AllDocumentsHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1147

#1148 Update port to 3002
  Dockerfile
  README.md
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
  config/default.json
  config/development.json
  docker-compose.yml
  src/main/pcq/index.ts
  src/test/a11y/a11y.ts
  src/test/end-to-end/saucelabs.conf.js
  src/test/smoke/smoke.conf.js
  src/test/smoke/tests/healthCheck.test.js
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUrl.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1148

#1150 Update idam port
  config/development.json
Labels: ns:et, prd:et, rel:et-sya-pr-1150

#1149 RET-3271: EEC Notifications on ET3 Response page
  src/main/controllers/citizen-hub/CitizenHubDocumentController.ts
  src/main/definitions/govuk/govukTable.ts
  src/main/views/response-from-respondent-view.njk
  src/test/unit/controller/citizen-hub/CitizenHubDocumentController.test.ts
  src/test/unit/views/response-from-respondent-view.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1149
