Repository hmcts/et-sya-frontend, pull requests merged in 2023-06, with the labels that each got.

#829 RET-3733 - Spacing of tables
  src/main/views/response-from-respondent-view.njk
Labels: ns:et, prd:et, rel:et-sya-pr-829

#833 RET-3715 Orders and request sub-page statuses
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/hub.ts
  src/main/views/tribunal-order-or-request-details.njk
  src/test/unit/controller/TribunalOrderOrRequestDetailsController.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockNotificationItem.ts
Labels: ns:et, prd:et, rel:et-sya-pr-833

#835 RET-3757
  src/main/definitions/constants.ts
Labels: ns:et, prd:et, rel:et-sya-pr-835

#832 RET-3734
  src/main/controllers/CitizenHubDocumentController.ts
  src/main/resources/locales/cy/translation/response-from-respondent.json
  src/main/resources/locales/en/translation/response-from-respondent.json
  src/main/views/response-from-respondent-view.njk
Labels: ns:et, prd:et, rel:et-sya-pr-832

#837 RET-3688: Removed unused notStartedYet notification status
  src/main/controllers/GeneralCorrespondenceNotificationDetailsController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/test/unit/mocks/mockNotificationItem.ts
Labels: ns:et, prd:et, rel:et-sya-pr-837

#840 ET3 Fixes
  src/main/controllers/CitizenHubDocumentController.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
Labels: ns:et, prd:et, rel:et-sya-pr-840

#828 RET-3697. Respondents applications page statuses
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/RespondentApplicationsController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/respondent-applications.json
  src/main/resources/locales/en/translation/respondent-applications.json
  src/main/services/CaseService.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/TseRespondentApplicationHelpers.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockUserCase.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/test-helpers/clone.ts
Labels: ns:et, prd:et, rel:et-sya-pr-828

#841 RET-3715 remove ability to respond when response not required
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/views/tribunal-order-or-request-details.njk
  src/test/unit/controller/TribunalOrderOrRequestDetailsController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-841

#737 RET-3358 Adding Web Chat Module
  src/main/modules/helmet/index.ts
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/components/web-chat.njk
  src/main/views/home.njk
  src/main/views/template.njk
Labels: ns:et, prd:et, rel:et-sya-pr-737

#843 Ret 3762 your claim details
  src/main/resources/locales/cy/translation/claim-details.json
  src/main/resources/locales/en/translation/claim-details.json
  src/main/views/claim-details.njk
  src/test/unit/controller/helpers/RespondentHelpers.test.ts
  src/test/unit/views/claim-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-843

#849 Revert "RET-3452"
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/helpers/FormHelpers.ts
  src/main/resources/locales/cy/translation/check-your-answers.json
  src/main/resources/locales/en/translation/check-your-answers.json
Labels: ns:et, prd:et, rel:et-sya-pr-849

#854 RET-3759
  src/main/views/response-from-respondent-view.njk
Labels: ns:et, prd:et, rel:et-sya-pr-854

#860 RET-2893
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/test/unit/controller/helpers/RespondentAnswersHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-860

#859 Ret 3037 ratelimits
  README.md
  package.json
  src/main/app.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/modules/routes/routes.ts
  src/main/views/form/multipartForm.njk
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/views/describe-what-happened.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-859

#863 Ret 3815 - Fix yarn audit
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-863

#864 RET-3481
  src/main/assets/js/submit-claim.ts
Labels: ns:et, prd:et, rel:et-sya-pr-864

#865 Ret 3452
  src/main/helper/ApiFormatter.ts
Labels: ns:et, prd:et, rel:et-sya-pr-865

#866 RET-3789 Redis version 6 upgrade
  infrastructure/main.tf
Labels: ns:et, prd:et, destroy, rel:et-sya-pr-866

#857 RET-2919
  src/main/controllers/ClaimDetailsController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/views/claim-details.njk
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-857

#847 RET-3684. Status update for respondents applications.
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/definitions/hub.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/services/CaseService.ts
  src/main/views/respondent-applications.njk
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/TseRespondentApplicationHelpers.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-847

#875 Ret 3790 - Claimant views request from tribunal
  package.json
  src/main/controllers/AllDocumentsController.ts
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/AttachmentController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/JudgmentDetailsController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/AdminNotificationHelper.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/JudgmentHelpers.ts
  src/main/definitions/adminNotification.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/respond-to-tribunal-response.json
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/respond-to-tribunal-response.json
  src/main/resources/locales/en/translation/respondent-application-details.json
  src/main/views/application-details.njk
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/respond-to-tribunal-response.njk
  src/main/views/respondent-application-details.njk
  src/test/unit/controller/ApplicationDetailsController.test.ts
  src/test/unit/controller/AttachmentController.test.ts
  src/test/unit/controller/helpers/AdminNotificationsHelper.test.ts
  src/test/unit/controller/helpers/AllDocumentsHelper.test.ts
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
  src/test/unit/views/respondent-application-details.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-875

#876 RET-2923
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/RespondentDetailsRedirectCheckAnswerController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/views/check-your-answers.njk
  src/main/views/respondent-details-check.njk
Labels: ns:et, prd:et, rel:et-sya-pr-876

#881 Ret 3791 - Response to tribunal page
  package.json
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respond-to-tribunal-response.json
  src/main/resources/locales/en/translation/respond-to-tribunal-response.json
  src/main/views/application-details.njk
  src/main/views/respond-to-tribunal-response.njk
  src/main/views/respondent-application-details.njk
  src/test/unit/controller/RespondToTribunalResponseController.test.ts
  src/test/unit/views/respond-to-tribunal-response.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-881

#882 Stop changing respondent applications status when submitting a response from claimant
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/SubmitRespondentController.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/SubmitRespondentController.test.ts
  src/test/unit/mocks/mockApplications.ts
Labels: ns:et, prd:et, rel:et-sya-pr-882

#884 resolutions - jsdom
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-884

#883 Revert "RET-2923"
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/RespondentDetailsRedirectCheckAnswerController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/views/check-your-answers.njk
  src/main/views/respondent-details-check.njk
Labels: ns:et, prd:et, rel:et-sya-pr-883

#885 Revert "RET-2919"
  src/main/controllers/ClaimDetailsController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/views/claim-details.njk
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-885

#886 RET-3792 - Fix Tribunal CYA page
  src/main/controllers/TribunalResponseCYAController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-886

#887 Ret 3690 fixes
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/JudgmentDetailsController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/AdminNotificationHelper.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/JudgmentHelpers.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/views/application-details.njk
  src/main/views/respondent-application-details.njk
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/controller/helpers/JudgmentHelpers.test.ts
  src/test/unit/mocks/mockUserCaseWithDecisionsAndJudgments.ts
Labels: ns:et, prd:et, rel:et-sya-pr-887

#858 PET-1.1.2.2
  README.md
  package.json
  src/main/app.ts
  src/main/assets/js/submit-claim.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/StillWorkingController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/check-your-answers.json
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/check-your-answers.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/views/form/multipartForm.njk
  src/main/views/response-from-respondent-view.njk
  src/test/unit/controller/DescribeWhatHappenedController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/controller/helpers/RespondentAnswersHelper.test.ts
  src/test/unit/views/describe-what-happened.test.ts
  yarn.lock
Labels: ns:et, prd:et, destroy, rel:et-sya-pr-858

#888 RET 3796, 3797 Application response: add value to show if responding to a tribunal order/request or not
  src/main/controllers/RespondentApplicationCYAController.ts
  src/main/controllers/TribunalResponseCYAController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/definitions/case.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/RespondentApplicationCYAController.test.ts
  src/test/unit/controller/TribunalResponseCYAController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-888

#891 RET-0000. Group controllers
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/citizen-hub/CitizenHubDocumentController.ts
  src/main/modules/routes/routes.ts
  src/test/unit/controller/citizen-hub/CitizenHubController.test.ts
  src/test/unit/controller/citizen-hub/CitizenHubDocumentController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-891
