Repository hmcts/et-sya-frontend, pull requests merged in 2023-04, with the labels that each got.

#741 RET-2927
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/definitions/constants.ts
  src/main/services/CaseService.ts
  src/main/views/citizen-hub-notification-banner.njk
  src/test/unit/controller/TribunalOrderOrRequestDetailsController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-741

#746 Claim processing number of days adjusted
  src/main/controllers/CitizenHubController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-746

#742 Ret 3234
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/AttachmentController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/RespondentApplicationCYAController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/RespondentApplicationsController.ts
  src/main/controllers/SupportingMaterialController.ts
  src/main/controllers/TribunalOrderDocumentController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/complexTypes/triageQuestions.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/cy/translation/your-applications.json
  src/main/resources/locales/en/translation/respondent-application-details.json
  src/main/resources/locales/en/translation/your-applications.json
  src/main/views/respondent-application-details.njk
  src/main/views/respondent-applications.njk
  src/test/unit/controller/AttachmentController.test.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/SupportingMaterialController.test.ts
  src/test/unit/controller/TribunalOrderDocumentController.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
  src/test/unit/controller/helpers/RespondentApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/controller/helpers/TseRespondentApplicationHelpers.test.ts
  src/test/unit/routes/callback.test.ts
  src/test/unit/views/respondent-application-details.test.ts
  src/test/unit/views/respondentApplicationDetails.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-742

#751 RET-3381 Document download update
  src/main/controllers/CaseDocumentController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/test/unit/controller/CaseDocumentController.test.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-751

#750 RET-3435 Disabling submit button to not trigger submit case event twice
  src/main/assets/js/index.js
  src/main/assets/js/submit-claim.ts
  src/main/views/check-your-answers.njk
  src/test/end-to-end/pages/checkYourAnswers/checkYourAnswers.js
Labels: ns:et, prd:et, rel:et-sya-pr-750

#752 RET-3472 and RET-3473
  src/main/resources/locales/cy/translation/compensation.json
  src/main/resources/locales/cy/translation/tell-us-what-you-want.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/compensation.json
  src/main/resources/locales/en/translation/tell-us-what-you-want.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/form/form.njk
  src/test/end-to-end/pages/claimDetails/claimDetailsContentHelper.js
Labels: ns:et, prd:et, rel:et-sya-pr-752

#754 Ret 3482
  src/main/components/form/validator.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-754

#756 RET-3434
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/views/template.njk
Labels: ns:et, prd:et, rel:et-sya-pr-756

#759 RET-3381 Citizen hub document problem
  src/main/controllers/CaseDocumentController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/test/unit/controller/CaseDocumentController.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-759

#758 RET 3090 - Bundles- About your hearing documents
  src/main/controllers/AboutHearingDocumentsController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/controllers/helpers/FormHelpers.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/about-hearing-documents.json
  src/main/resources/locales/en/translation/about-hearing-documents.json
  src/main/views/about-hearing-documents.njk
  src/test/unit/controller/AboutHearingDocumentsController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/views/about-hearing-documents.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-758

#761 RET-3381
  src/main/controllers/CaseDocumentController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/test/unit/controller/CaseDocumentController.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-761

#764 Ret 3472 new
  package.json
  src/main/controllers/BenefitsController.ts
  src/main/controllers/NewJobController.ts
  src/main/controllers/NewJobPayController.ts
  src/main/controllers/NewJobStartDateController.ts
  src/main/controllers/NoticePeriodController.ts
  src/main/controllers/NoticeTypeController.ts
  src/main/controllers/PayController.ts
  src/main/controllers/PensionController.ts
  src/main/views/form/form.njk
  src/test/unit/controller/BenefitsController.test.ts
  src/test/unit/controller/NewJobController.test.ts
  src/test/unit/controller/NewJobStartDateController.test.ts
  src/test/unit/controller/NoticePeriodController.test.ts
  src/test/unit/controller/NoticeTypeController.test.ts
  src/test/unit/controller/PayController.test.ts
  src/test/unit/controller/PensionController.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-764

#762 RET-3381 Case document file format - Code updates
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/CaseDocumentController.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-762

#772 RET-2929_bug_fix
  src/main/controllers/AttachmentController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-772

#773 RET-2929_bug_fix
  src/main/controllers/CitizenHubController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-773

#775 Add withdraw as a type b application
  src/main/definitions/contact-applications.ts
Labels: ns:et, prd:et, rel:et-sya-pr-775

#753 Ret 3459
  charts/et-sya/Chart.yaml
  src/main/assets/js/address/submit.ts
  src/main/controllers/BenefitsController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/NewJobStartDateController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/triageQuestions.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/nunjucks/njkFilters.ts
  src/main/views/address/postcodeSelect.njk
  src/test/end-to-end/config.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/end-to-end/pages/welshTranslations/employment.and.respondent.details.welsh.page.js
  src/test/end-to-end/pages/welshTranslations/personal.details.welsh.page.js
  src/test/unit/controller/BenefitsController.test.ts
  src/test/unit/controller/NewJobController.test.ts
  src/test/unit/controller/NoticePeriodController.test.ts
  src/test/unit/controller/PayController.test.ts
  src/test/unit/controller/PensionController.test.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/modules/nunjucks/njkFilters.test.ts
  src/test/unit/routes/callback.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-753

#777 RET-3483
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ContactTheTribunalCYAController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/TribunalResponseCYAController.ts
  src/main/controllers/YourAppsToTheTribunalController.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/cy/translation/respondent-supporting-material.json
  src/main/resources/locales/cy/translation/tribunal-order-or-request-details.json
  src/main/resources/locales/cy/translation/tribunal-respond-to-order.json
  src/main/resources/locales/cy/translation/tribunal-response-cya.json
  src/main/resources/locales/cy/translation/your-applications.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/en/translation/respondent-application-details.json
  src/main/resources/locales/en/translation/respondent-supporting-material.json
  src/main/resources/locales/en/translation/tribunal-order-or-request-details.json
  src/main/resources/locales/en/translation/tribunal-respond-to-order.json
  src/main/resources/locales/en/translation/tribunal-response-cya.json
  src/main/resources/locales/en/translation/your-applications.json
Labels: ns:et, prd:et, rel:et-sya-pr-777

#778 RET-3483
  src/main/controllers/RespondentApplicationCYAController.ts
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/cy/translation/respondent-application-cya.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/resources/locales/en/translation/respondent-application-cya.json
Labels: ns:et, prd:et, rel:et-sya-pr-778

#769 Sonar fix
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-769

#770 RET-3426 - Speeding up tests locally & in the pipeline and upgrading a ton of dependencies.
  .dockerignore
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarnrc.yml
  Dockerfile
  jest.config.js
  jest.unit.config.js
  jest.views.config.js
  package.json
  src/main/pcq/createToken.ts
  src/main/pcq/index.ts
  src/test/api/pact/pact-test/idam/get-user-details.test.ts
  src/test/api/pact/publish/publish.ts
  src/test/unit/assets/js/session/session-timeout.test.ts
  src/test/unit/utils/createToken.test.ts
  tsconfig.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-770
