Repository hmcts/et-sya-frontend, pull requests merged in 2023-01, with the labels that each got.

#571 RET-2987 - adding Welsh translations
  src/main/resources/locales/cy/translation/acas-cert-num.json
  src/main/resources/locales/cy/translation/acas-multiple.json
  src/main/resources/locales/cy/translation/acknowledgement-of-claim.json
  src/main/resources/locales/cy/translation/average-weekly-hours.json
  src/main/resources/locales/cy/translation/benefits.json
  src/main/resources/locales/cy/translation/check-your-answers.json
  src/main/resources/locales/cy/translation/checklist.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/claim-details-check.json
  src/main/resources/locales/cy/translation/claim-details.json
  src/main/resources/locales/cy/translation/claim-saved.json
  src/main/resources/locales/cy/translation/claim-submitted.json
  src/main/resources/locales/cy/translation/claim-type-discrimination.json
  src/main/resources/locales/cy/translation/claim-type-pay.json
  src/main/resources/locales/cy/translation/claimant-applications.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/contact-acas.json
  src/main/resources/locales/cy/translation/cookie-preferences.json
  src/main/resources/locales/cy/translation/end-date.json
  src/main/resources/locales/cy/translation/enter-address.json
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/lip-or-representative.json
  src/main/resources/locales/cy/translation/new-job-pay.json
  src/main/resources/locales/cy/translation/new-job-start-date.json
  src/main/resources/locales/cy/translation/new-job.json
  src/main/resources/locales/cy/translation/no-acas-reason.json
  src/main/resources/locales/cy/translation/notice-end.json
  src/main/resources/locales/cy/translation/notice-length-months.json
  src/main/resources/locales/cy/translation/notice-length-weeks.json
  src/main/resources/locales/cy/translation/notice-period-no-longer-working.json
  src/main/resources/locales/cy/translation/notice-type.json
  src/main/resources/locales/cy/translation/place-of-work.json
  src/main/resources/locales/cy/translation/reasonable-adjustments.json
  src/main/resources/locales/cy/translation/rejection-of-claim.json
  src/main/resources/locales/cy/translation/respondent-address.json
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/cy/translation/respondent-name.json
  src/main/resources/locales/cy/translation/response-acknowledgement.json
  src/main/resources/locales/cy/translation/response-from-respondent.json
  src/main/resources/locales/cy/translation/response-rejection.json
  src/main/resources/locales/cy/translation/return-to-existing.json
  src/main/resources/locales/cy/translation/sex-and-title.json
  src/main/resources/locales/cy/translation/sidebar-contact-us.json
  src/main/resources/locales/cy/translation/single-or-multiple-claim.json
  src/main/resources/locales/cy/translation/start-date.json
  src/main/resources/locales/cy/translation/steps-to-making-your-claim.json
  src/main/resources/locales/cy/translation/tasklist-check.json
  src/main/resources/locales/cy/translation/tell-us-what-you-want.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/cy/translation/type-of-claim.json
  src/main/resources/locales/cy/translation/valid-no-acas-reason.json
  src/main/resources/locales/cy/translation/video-hearings.json
  src/main/resources/locales/cy/translation/work-address.json
  src/main/resources/locales/cy/translation/work-postcode.json
Labels: ns:et, prd:et, rel:et-sya-pr-571

#574 RET-2941 and RET-2935
  src/main/resources/locales/en/translation/home.json
  src/main/resources/locales/en/translation/valid-no-acas-reason.json
  src/test/end-to-end/helpers/commonFlowContent.js
Labels: ns:et, prd:et, rel:et-sya-pr-574

#572 RET-2865 - Set currentUrl on ClaimantApplications page
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/ClaimSavedController.ts
  src/main/controllers/ClaimantApplicationsController.ts
  src/main/controllers/HomeController.ts
  src/main/controllers/NewAccountLandingController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/helpers/LanguageHelper.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/controllers/helpers/RouterHelpers.ts
  src/main/services/CaseSelectionService.ts
  src/main/views/check-your-answers.njk
  src/main/views/claim-saved.njk
  src/main/views/claimant-applications.njk
  src/main/views/cookie-banner.njk
  src/main/views/home.njk
  src/main/views/new-account-landing.njk
  src/main/views/respondent-details-check.njk
  src/test/unit/controller/HomeController.test.ts
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/services/CaseSelectionService.test.ts
  src/test/unit/views/claim-submitted.test.ts
  src/test/unit/views/cookie-preferences.test.ts
  src/test/unit/views/home.test.ts
  src/test/unit/views/job-title.test.ts
  src/test/unit/views/lip-or-representative.test.ts
  src/test/unit/views/single-or-multiple-claim.test.ts
  src/test/unit/views/start-date.test.ts
  src/test/unit/views/video-hearing.test.ts
  src/test/unit/views/whistleblowing-claims.test.ts
  src/test/unit/views/work-postcode.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-572

#576 Welsh language journey - enter translations
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/claim-details.json
  src/main/resources/locales/cy/translation/claim-type-discrimination.json
  src/main/resources/locales/cy/translation/claim-type-pay.json
  src/main/resources/locales/cy/translation/claimant-applications.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/compensation.json
  src/main/resources/locales/cy/translation/date-of-birth.json
  src/main/resources/locales/cy/translation/describe-what-happened.json
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/sex-and-title.json
  src/main/resources/locales/cy/translation/sidebar-contact-us.json
  src/main/resources/locales/cy/translation/tell-us-what-you-want.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/cy/translation/tribunal-recommendation.json
  src/main/resources/locales/cy/translation/type-of-claim.json
Labels: ns:et, prd:et, rel:et-sya-pr-576

#578 Replace removed placeholder
  src/main/resources/locales/cy/translation/common.json
Labels: ns:et, prd:et, rel:et-sya-pr-578

#575 RET-2934
  src/main/modules/helmet/index.ts
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/test/end-to-end/helpers/commonFlowContent.js
Labels: ns:et, prd:et, rel:et-sya-pr-575

#581 RET-2936
  src/main/resources/locales/en/translation/no-acas-reason.json
  src/main/views/no-acas-reason.njk
Labels: ns:et, prd:et, rel:et-sya-pr-581

#580 RET-3005: Fix LanguageHelper
  src/main/controllers/helpers/LanguageHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-580

#583 Updated enterPersonalDetails.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
Labels: ns:et, prd:et, rel:et-sya-pr-583

#582 Ret-2038 Prebuild automation for accessibility
  Jenkinsfile_CNP
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-582

#584 Ret 2936 automation
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-584

#585 Ret 2619 - Applications complete page- Placeholder
  src/main/controllers/ApplicationCompleteController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/application-complete.json
  src/main/resources/locales/en/translation/application-complete.json
  src/main/views/application-complete.njk
  src/test/routes/application-complete.test.ts
  src/test/unit/controller/ApplicationCompleteController.test.ts
  src/test/unit/views/application-complete.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-585

#586 Ret 2941 automation
  src/test/end-to-end/helpers/commonFlow.js
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-586

#587 Fix package security
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-587

#573 PET - PI28 S5
  Jenkinsfile_CNP
  package.json
  src/main/modules/helmet/index.ts
  src/main/resources/locales/en/translation/date-of-birth.json
  src/main/resources/locales/en/translation/home.json
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/no-acas-reason.json
  src/main/resources/locales/en/translation/valid-no-acas-reason.json
  src/main/views/no-acas-reason.njk
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-573

#588 Ret 2078
  src/main/controllers/CitizenHubController.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/helper/ApiFormatter.ts
  src/main/helper/state-sequence.ts
  src/main/views/response-from-respondent-view.njk
  src/test/unit/controller/StepsToMakingYourClaimController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-588

#590 Ret 3035 - Bug fixes
  package.json
  src/main/assets/js/address/submit.ts
  src/main/modules/oidc/index.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/claim-type-discrimination.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/citizen-hub.njk
  src/main/views/claim-details.njk
  src/main/views/document-view.njk
  src/main/views/response-from-respondent-view.njk
  src/main/views/template.njk
  src/test/end-to-end/pages/claimDetails/claimDet.js
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-590

#591 Ret 3038 - Enter translations
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/date-of-birth.json
  src/main/resources/locales/cy/translation/home.json
  src/main/resources/locales/cy/translation/no-acas-reason.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/cy/translation/valid-no-acas-reason.json
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-591

#592 Ret-3001 Trimming spaces from start and end of string inputs
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/FormHelpers.ts
Labels: ns:et, prd:et, rel:et-sya-pr-592

#594 RET-3030 - Add translation plus span to links
  src/main/resources/locales/cy/translation/lip-or-representative.json
Labels: ns:et, prd:et, rel:et-sya-pr-594

#595 RET-3004
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-595

#596 Pet pi28 s6
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/FormHelpers.ts
Labels: ns:et, prd:et, rel:et-sya-pr-596

#599 Helm Chart
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-599

#598 RET-3036 Adding Accessibility Statement to Footer Menu
  src/main/controllers/AccessibilityStatementController.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/en/translation/accessibility-statement.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/accessibility-statement.njk
  src/main/views/template.njk
  src/test/unit/controller/AccessibilityStatementController.test.ts
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-598

#603 Update locators in test
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-603

#604 Ret 3036
  src/main/resources/locales/en/translation/accessibility-statement.json
  src/main/views/template.njk
Labels: ns:et, prd:et, rel:et-sya-pr-604

#605 Ret-3036 Adding Accessibility Statement to Footer Menu
  src/main/resources/locales/en/translation/accessibility-statement.json
Labels: ns:et, prd:et, rel:et-sya-pr-605

#601 Pet pi28 s6
  src/main/controllers/AccessibilityStatementController.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/en/translation/accessibility-statement.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/accessibility-statement.njk
  src/main/views/template.njk
  src/test/unit/controller/AccessibilityStatementController.test.ts
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-601

#606 RET-3066 - Add placeholder text
  src/main/resources/locales/cy/translation/accessibility-statement.json
  src/main/resources/locales/cy/translation/template.json
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-606

#607 Update default contact tribunal status
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/CitizenHubDocumentController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/test/end-to-end/features/functionalTests/haveYouCompletedThisSectionValidation.js
  src/test/unit/mocks/mockEt1DataModel.ts
Labels: ns:et, prd:et, rel:et-sya-pr-607

#610 Update end date to be in future
  src/test/unit/controller/NoticeEndController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-610

#614 Resolve security issues
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-614

#612 RET-3046 Average weekly hours Decimal Check Fails
  src/main/components/form/validator.ts
  src/main/controllers/AverageWeeklyHoursController.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/NoticeEndController.test.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-612

#615 RET-3066 - Add accessibility translations
  src/main/resources/locales/cy/translation/accessibility-statement.json
Labels: ns:et, prd:et, rel:et-sya-pr-615

#616 Bump node chart to 2.4.13
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-616

#618 Ret 3046
  src/main/components/form/validator.ts
Labels: ns:et, prd:et, rel:et-sya-pr-618

#620 RER-2618
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/ContactTheTribunalCYAController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/controllers/SubmitTribunalCYAController.ts
  src/main/controllers/SupportingMaterialController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/hub.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/contact-the-tribunal-cya.json
  src/main/services/CaseService.ts
  src/main/views/contact-the-tribunal-cya.njk
  src/main/views/footer.njk
  src/main/views/template.njk
  src/test/unit/controller/SubmitTribunalCYAController.test.ts
  src/test/unit/controller/SupportingMaterialController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/views/claim-submitted.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-620

#622 Ret 3046
  src/main/components/form/validator.ts
  src/test/unit/components/validator.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-622

#613 Ret 2942
  src/main/controllers/ClaimantApplicationsController.ts
  src/main/controllers/helpers/ApplicationTableRecordTranslationHelper.ts
  src/main/services/CaseSelectionService.ts
  src/test/unit/mocks/mockTranslations.ts
  src/test/unit/services/CaseSelectionService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-613

#624 RET-3021
  src/main/resources/locales/en/translation/work-postcode.json
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/unit/views/work-postcode.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-624

#602 Ret 2616. Create claimant applications.
  .eslintrc.js
  src/main/controllers/ApplicationCompleteController.ts
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/ContactTheTribunalCYAController.ts
  src/main/controllers/ContactTheTribunalFileController.ts
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/controllers/DescribeWhatHappenedController.ts
  src/main/controllers/SubmitTribunalCYAController.ts
  src/main/controllers/SupportingMaterialController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/ContactApplicationHelper.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/ClaimantTse.ts
  src/main/definitions/constants.ts
  src/main/definitions/form.ts
  src/main/definitions/hub.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/cy/translation/copy-to-other-party.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/en/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/en/translation/contact-the-tribunal.json
  src/main/resources/locales/en/translation/copy-to-other-party.json
  src/main/services/CaseService.ts
  src/main/views/contact-the-tribunal-cya.njk
  src/main/views/contact-the-tribunal-selected.njk
  src/main/views/copy-to-other-party.njk
  src/main/views/footer.njk
  src/main/views/form/fields/button.njk
  src/main/views/form/fields/insetFields.njk
  src/main/views/form/fields/summaryList.njk
  src/main/views/form/form.njk
  src/main/views/form/multipartForm.njk
  src/main/views/form/saveButtons.njk
  src/main/views/template.njk
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
  src/test/unit/controller/SubmitTribunalCYAController.test.ts
  src/test/unit/controller/SupportingMaterialController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/views/claim-submitted.test.ts
  src/test/unit/views/copy-to-other-party.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-602

#626 Ret 2942
  src/main/controllers/helpers/ApplicationTableRecordTranslationHelper.ts
  src/test/unit/mocks/mockTranslations.ts
Labels: ns:et, prd:et, rel:et-sya-pr-626

#628 RET-2619-fix
  src/main/resources/locales/en/translation/application-complete.json
Labels: ns:et, prd:et, rel:et-sya-pr-628

#630 Ret 3114 and ret 3118
  Jenkinsfile_CNP
  src/main/controllers/helpers/ApplicationTableRecordTranslationHelper.ts
  src/main/definitions/case.ts
  src/main/resources/locales/en/translation/et1-details.json
  src/main/views/claimant-applications.njk
  src/test/unit/mocks/mockApplications.ts
Labels: ns:et, prd:et, rel:et-sya-pr-630

#632 Ret 3118
  src/main/controllers/helpers/ApplicationTableRecordTranslationHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-632

#633 Ret 3080
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/resources/locales/en/translation/et1-details.json
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-633

#635 Jenkinsfile_nightly fix
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-635

#629 Ret 3107
  src/main/controllers/BenefitsController.ts
  src/main/controllers/ClaimSubmittedController.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/definitions/form.ts
  src/main/resources/locales/cy/translation/acas-cert-num.json
  src/main/resources/locales/cy/translation/acas-multiple.json
  src/main/resources/locales/cy/translation/average-weekly-hours.json
  src/main/resources/locales/cy/translation/benefits.json
  src/main/resources/locales/cy/translation/check-your-answers.json
  src/main/resources/locales/cy/translation/checklist.json
  src/main/resources/locales/cy/translation/claim-submitted.json
  src/main/resources/locales/cy/translation/claim-type-discrimination.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/date-of-birth.json
  src/main/resources/locales/cy/translation/describe-what-happened.json
  src/main/resources/locales/cy/translation/end-date.json
  src/main/resources/locales/cy/translation/enter-address.json
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/job-title.json
  src/main/resources/locales/cy/translation/new-job-pay.json
  src/main/resources/locales/cy/translation/new-job.json
  src/main/resources/locales/cy/translation/no-acas-reason.json
  src/main/resources/locales/cy/translation/notice-end.json
  src/main/resources/locales/cy/translation/notice-length-months.json
  src/main/resources/locales/cy/translation/notice-length-weeks.json
  src/main/resources/locales/cy/translation/notice-period-no-longer-working.json
  src/main/resources/locales/cy/translation/notice-period-working.json
  src/main/resources/locales/cy/translation/pay.json
  src/main/resources/locales/cy/translation/reasonable-adjustments.json
  src/main/resources/locales/cy/translation/respondent-name.json
  src/main/resources/locales/cy/translation/return-to-existing.json
  src/main/resources/locales/cy/translation/steps-to-making-your-claim.json
  src/main/resources/locales/cy/translation/tell-us-what-you-want.json
  src/main/resources/locales/cy/translation/type-of-claim.json
  src/main/resources/locales/cy/translation/valid-no-acas-reason.json
  src/main/resources/locales/en/translation/acas-multiple.json
  src/main/resources/locales/en/translation/benefits.json
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/new-job.json
  src/main/resources/locales/en/translation/notice-length-months.json
  src/main/resources/locales/en/translation/notice-length-weeks.json
  src/main/resources/locales/en/translation/notice-period-no-longer-working.json
  src/main/resources/locales/en/translation/notice-period-working.json
  src/main/resources/locales/en/translation/valid-no-acas-reason.json
  src/main/views/check-your-answers.njk
  src/main/views/cookie-preferences.njk
  src/main/views/form/fields/charactercount.njk
  src/main/views/notice-length.njk
  src/test/end-to-end/pages/welshTranslations/submit.claim.welsh.page.js
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-629

#639 Ret 2617 - Rule 92 question - both parties are system users (CitizenUI)
  src/main/controllers/ApplicationCompleteController.ts
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/definitions/case.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/cy/translation/copy-to-other-party.json
  src/main/resources/locales/en/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/en/translation/copy-to-other-party.json
  src/main/services/CaseService.ts
  src/main/views/contact-the-tribunal-cya.njk
  src/main/views/copy-to-other-party.njk
Labels: ns:et, prd:et, rel:et-sya-pr-639

#641 RET-3107. Fix acas 'no' translation
  src/main/controllers/helpers/RespondentAnswersHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-641

#637 Jenkinsfile_nightly fix
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-637
