Repository hmcts/et-sya-frontend, pull requests merged in 2023-02, with the labels that each got.

#645 Ret-3111 Update yarn v3
  .gitignore
  .yarn/releases/yarn-3.4.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-645

#648 Ret-3133 Upgrade to helm-nodejs version 2.4.13
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-648

#649 Merge latest
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/main/components/form/validator.ts
  src/main/controllers/AverageWeeklyHoursController.ts
  src/main/controllers/helpers/ApplicationTableRecordTranslationHelper.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/definitions/case.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/work-postcode.json
  src/main/views/claimant-applications.njk
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/NoticeEndController.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockTranslations.ts
  src/test/unit/views/check-your-answers.test.ts
  src/test/unit/views/work-postcode.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-649

#646 RET-2616-fix
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/en/translation/contact-the-tribunal-selected.json
  src/main/views/contact-the-tribunal-selected.njk
Labels: ns:et, prd:et, rel:et-sya-pr-646

#650 Add work postcode translations
  src/main/resources/locales/cy/translation/work-postcode.json
Labels: ns:et, prd:et, rel:et-sya-pr-650

#651 Ret 2617 fix
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/test/routes/copy-to-other-party.test.ts
  src/test/unit/controller/CopyToOtherPartyController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-651

#654 RET-2997
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/api/caseApiBody.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/triageQuestions.ts
  src/main/helper/ApiFormatter.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, add-or-update, rel:et-sya-pr-654

#656 RET-2618-v2
  src/main/controllers/ContactTheTribunalCYAController.ts
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/definitions/case.ts
  src/main/helper/ApiFormatter.ts
  src/main/views/contact-the-tribunal-cya.njk
  src/test/unit/helper/ApiFormatter.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-656

#643 RET-2288: application details in ET1
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ClaimDetailsController.ts
  src/main/controllers/ContactTheTribunalCYAController.ts
  src/main/controllers/SupportingMaterialController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/claim-details.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/claim-details.json
  src/main/views/application-details.njk
  src/main/views/claim-details.njk
  src/test/unit/controller/SupportingMaterialController.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
Labels: ns:et, prd:et, rel:et-sya-pr-643

#659 RET-2618-fix-language-param: Add language param to state in ContactTh…
  src/main/controllers/ContactTheTribunalCYAController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-659

#660 Ret 2617 - fix - clear session errors
  src/main/controllers/CopyToOtherPartyController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-660

#661 RET-3160. Fix footer links in accessibility page
  src/main/resources/locales/cy/translation/template.json
Labels: ns:et, prd:et, rel:et-sya-pr-661

#663 Ret 2618 small improvements
  src/main/controllers/ContactTheTribunalCYAController.ts
  src/main/controllers/SubmitTribunalCYAController.ts
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal-cya.json
  src/main/resources/locales/en/translation/contact-the-tribunal-cya.json
  src/test/unit/controller/SubmitTseController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-663

#665 RET-2288-fix: Fixed file size formatting
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-665

#664 Fix logging
  src/main/modules/properties-volume/index.ts
  src/test/unit/translations.spec.ts
Labels: ns:et, prd:et, rel:et-sya-pr-664

#666 Upgrade yarn version to v3 (berry)
  .gitignore
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  charts/et-sya/Chart.yaml
  infrastructure/.terraform-version
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
  package.json
  yarn.lock
Labels: ns:et, prd:et, add-or-update, rel:et-sya-pr-666

#670 Add missing packages
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-670

#668 RET-2288 - minor bug fixes
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/ClaimDetailsController.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/views/check-your-answers.njk
  src/main/views/claim-details.njk
  src/test/unit/views/claim-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-668

#671 RET-3102
  src/main/components/form/validator.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/resources/locales/en/translation/type-of-claim.json
Labels: ns:et, prd:et, add-or-update, rel:et-sya-pr-671

#676 RET-2289
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/views/application-details.njk
Labels: ns:et, prd:et, rel:et-sya-pr-676

#677 Ret 3102- change to make text area as character count
  charts/et-sya/Chart.yaml
  src/main/controllers/TypeOfClaimController.ts
Labels: ns:et, prd:et, no-changes, rel:et-sya-pr-677

#678 RET-2289
  charts/et-sya/Chart.yaml
  src/main/controllers/YourAppsToTheTribunalController.ts
  src/main/controllers/helpers/PageContentHelpers.ts
Labels: ns:et, prd:et, rel:et-sya-pr-678

#679 RET-2289-test: Add additional checks to SubmitTseController test
  src/test/unit/controller/SubmitTseController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-679

#680 Ret 2816
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
  src/main/definitions/constants.ts
  src/main/definitions/contact-applications.ts
  src/main/services/CaseService.ts
Labels: ns:et, prd:et, rel:et-sya-pr-680

#682 RET-2289-fix: Change your-application.njk contacts margin, add 'displ…
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/views/your-applications.njk
Labels: ns:et, prd:et, rel:et-sya-pr-682

#686 Remove backlink from application-complete page
  src/main/modules/routes/routes.ts
  src/main/views/application-complete.njk
Labels: ns:et, prd:et, rel:et-sya-pr-686

#687 Ret 3102 1500 chars limit
  src/main/components/form/validator.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/resources/locales/cy/translation/type-of-claim.json
  src/main/resources/locales/en/translation/type-of-claim.json
  src/test/unit/components/validator.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-687

#688 RET-2973. Restrict free text for TSE
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/en/translation/contact-the-tribunal-selected.json
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-688

#689 3245 - Improve test coverage
  src/main/components/form/form.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/test/unit/components/form.test.ts
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-689

#692 RET-3245
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-692

#691 3245 more coverage
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/test/unit/controller/ContactTheTribunalController.test.ts
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
  src/test/unit/controller/helpers/ContactTheTribunalCYAHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-691

#694 RET-3245-regex-fix
  src/main/controllers/SupportingMaterialController.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/helper/ApiFormatter.ts
  src/test/unit/helper/ApiFormatter.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-694

#696 Ret 3102 100 chars limit
  src/main/components/form/validator.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/resources/locales/cy/translation/type-of-claim.json
  src/main/resources/locales/en/translation/type-of-claim.json
  src/test/unit/components/validator.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-696

#699 RET-3244 - Add application state
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-699

#700 RET-3260
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-700
