Repository hmcts/et-sya-frontend, pull requests merged in 2023-09, with the labels that each got.

#955 RET-4054 - Display notification banner for Other (General Correspondence)
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/complexTypes/sendNotificationTypeItem.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/helpers/GeneralCorrespondenceHelper.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockNotificationItem.ts
Labels: ns:et, prd:et, rel:et-sya-pr-955

#938 PET-1.2.1
  README.md
  package.json
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/definitions/case.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/common.json
  src/main/views/error-summary.njk
  yarn.lock
Labels: ns:et, prd:et, destroy, rel:et-sya-pr-938

#963 Temporarily removing the path and disabling test for urgent fix
  src/main/utils/getLegacyUrlFromLng.ts
  src/test/routes/lip-or-representative.test.ts
  src/test/routes/single-or-multiple-claim.test.ts
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/controller/SingleOrMultipleController.test.ts
  src/test/unit/controller/WorkPostcodeController.test.ts
  src/test/unit/utils/getLegacyUrlFromLng.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-963

#964 Ret 4109
  src/main/controllers/RespondToApplicationController.ts
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/views/respond-to-application.njk
Labels: ns:et, prd:et, rel:et-sya-pr-964

#966 Ret 4154
  src/main/controllers/helpers/CaseHelpers.ts
Labels: ns:et, prd:et, rel:et-sya-pr-966

#965 PET-1.2.2
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/views/error-summary.njk
  src/main/views/respond-to-application.njk
Labels: ns:et, prd:et, rel:et-sya-pr-965

#970 RET-4197
  src/main/controllers/ClaimDetailsController.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-970

#962 RET-4164 addSummaryRow
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/GeneralCorrespondenceNotificationDetailsController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/ContactApplicationHelper.ts
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/GeneralCorrespondenceHelper.ts
  src/main/controllers/helpers/JudgmentHelpers.ts
  src/main/controllers/helpers/RespondentApplicationCYAHelper.ts
  src/main/controllers/helpers/RespondentSupportingMaterialHelper.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/main/controllers/helpers/YourDetailsAnswersHelper.ts
  src/main/definitions/form.ts
  src/main/definitions/govuk/govukSummaryList.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/controller/helpers/GeneralCorrespondenceHelper.test.ts
  src/test/unit/controller/helpers/JudgmentHelpers.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-962

#969 RET-4146
  config/custom-environment-variables.json
  src/main/address/index.ts
  src/main/app.ts
  src/main/controllers/ReturnToExistingController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/modules/health/index.ts
  src/main/modules/session/index.ts
  src/main/pcq/index.ts
  src/main/services/CaseService.ts
  src/main/utils/getLegacyUrlFromLng.ts
  src/main/views/webpack/css.njk
  src/main/views/webpack/js.njk
  src/test/unit/auth/auth.test.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-969, enable_keep_helm

#974 RET-4219 - Renovate Config Change
  .github/renovate.json
  package.json
  src/test/end-to-end/features/e2e_Scenarios/submitClaimForSinglePerson.js
Labels: ns:et, prd:et, rel:et-sya-pr-974

#973 RET-3879
  src/main/assets/js/index.js
  src/main/assets/js/submit-claim.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/modules/routes/routes.ts
  src/main/views/check-your-answers.njk
Labels: ns:et, prd:et, rel:et-sya-pr-973

#992 Ret 3879 new
  src/main/controllers/CheckYourAnswersController.ts
  src/main/definitions/appRequest.ts
  src/main/views/check-your-answers.njk
  src/test/unit/mocks/mockApp.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-992

#997 RET-4232 - Set up feature flagging
  charts/et-sya/Chart.yaml
  charts/et-sya/values.aat.template.yaml
  charts/et-sya/values.preview.template.yaml
  charts/et-sya/values.yaml
  config/default.json
  config/development.json
  package.json
  src/main/modules/featureFlag/launchDarkly.ts
  src/main/modules/properties-volume/index.ts
  src/main/views/template-language-disabled.njk
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-997

#1004 Use nunjucks template
  src/main/modules/nunjucks/index.ts
  src/main/views/template-language-disabled.njk
  src/main/views/template.njk
Labels: ns:et, prd:et, rel:et-sya-pr-1004

#988 RET-4039 - Add translations to respondent applications
  src/main/controllers/RespondentApplicationsController.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/respondent-applications.json
  src/main/resources/locales/en/translation/respondent-applications.json
  src/main/views/respondent-applications.njk
  src/test/routes/respondent-applications.test.ts
  src/test/unit/controller/RespondentApplicationsController.test.ts
  src/test/unit/views/respondent-applications.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-988

#982 RET-4035 - Add welsh translations supporting materials
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/helpers/ContactApplicationHelper.ts
  src/main/controllers/helpers/RespondentSupportingMaterialHelper.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/respondent-supporting-material.json
  src/main/resources/locales/en/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/en/translation/respondent-supporting-material.json
  src/main/views/respondent-supporting-material.njk
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-982

#1013 Upgrade gradle for fortify
  src/test/java/build.gradle
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
Labels: ns:et, prd:et, rel:et-sya-pr-1013
