Repository hmcts/et-sya-frontend, pull requests merged in 2023-10, with the labels that each got.

#1016 RET-4062 - Application stored date
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1016

#1017 RET-4062 - Citizen Hub Remove holding page
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1017

#1008 Ret 3740 - add Welsh translations
  src/main/controllers/ContactTheTribunalController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/cy/translation/copy-to-other-party.json
  src/main/views/copy-to-other-party.njk
  src/test/routes/copy-to-other-party.test.ts
  src/test/unit/controller/ContactTheTribunalController.test.ts
  src/test/unit/controller/CopyToOtherPartyController.test.ts
  src/test/unit/views/copy-to-other-party.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1008

#1018 RET-4062 - CYA page
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/TribunalResponseCYANotSystemUserController.ts
  src/main/controllers/helpers/CopyToOtherPartyHelper.ts
  src/main/controllers/helpers/RespondentApplicationCYAHelper.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/tribunal-response-cya.json
  src/main/resources/locales/en/translation/tribunal-response-cya.json
  src/test/unit/controller/CopyToOtherPartyNotSystemUserController.test.ts
  src/test/unit/controller/RespondToTribunalResponseController.test.ts
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  src/test/unit/controller/helpers/RespondentApplcationCYAHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1018

#1024 RET-4062 - Citizen Hub Banner
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/definitions/storeNotification.ts
  src/main/views/citizen-hub-notification-banner.njk
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1024

#990 Ret 4036 - adding Welsh translations
  src/main/controllers/RespondentApplicationCYAController.ts
  src/main/controllers/TribunalResponseCYAController.ts
  src/main/controllers/helpers/RespondentApplicationCYAHelper.ts
  src/main/resources/locales/cy/translation/respondent-application-cya.json
  src/main/views/contact-the-tribunal-cya.njk
  src/test/unit/controller/RespondentApplicationCYAController.test.ts
  src/test/unit/controller/TribunalResponseCYAController.test.ts
  src/test/unit/controller/helpers/RespondentApplcationCYAHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-990

#1021 Ret 3728 - add Welsh translations
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/AdminNotificationHelper.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/citizen-hub.njk
  src/test/routes/citizen-hub.test.ts
  src/test/unit/controller/citizen-hub/CitizenHubController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1021

#1030 RET-4062 - Store Application
  src/main/controllers/StoreTseController.ts
  src/main/controllers/StoredApplicationConfirmationController.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/StoreTseController.test.ts
  src/test/unit/controller/StoredApplicationConfirmationController.test.ts
  src/test/unit/controller/StoredToSubmitController.test.ts
  src/test/unit/views/stored-application-confirmation.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1030

#972 RET-4021: Display notification banner on tribunal notification responses
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/complexTypes/sendNotificationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/definitions/util-types.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/views/citizen-hub-notification-banner.njk
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  src/test/unit/controller/helpers/GeneralCorrespondenceHelper.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockNotificationItem.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-972

#1042 Update notice-end.test.ts
  src/test/routes/notice-end.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1042

#1032 RET-4062 - Store Response of Application
  src/main/controllers/StoreRespondentController.ts
  src/main/controllers/StoredResponseAppConfirmationController.ts
  src/main/controllers/TribunalResponseCYANotSystemUserController.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/StoreRespondentController.test.ts
  src/test/unit/controller/StoredResponseAppConfirmationController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1032

#1040 Migrate redis cache to Basic sku in non-prod env
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:et, prd:et, destroy, rel:et-sya-pr-1040

#1048 Node v20
  Dockerfile
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1048

#1050 Node 20
  .nvmrc
  Jenkinsfile_CNP
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-1050

#1057 Memory bump
  charts/et-sya/Chart.yaml
  charts/et-sya/values.aat.template.yaml
  charts/et-sya/values.preview.template.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-1057

#1052 Rule 92 Merge Fix
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/controllers/CopyToOtherPartyNotSystemUserController.ts
  src/main/controllers/TribunalResponseCYANotSystemUserController.ts
  src/main/controllers/helpers/CopyToOtherPartyHelper.ts
  src/test/unit/controller/CopyToOtherPartyNotSystemUserController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/RespondentApplcationCYAHelper.test.ts
  src/test/unit/views/copy-to-other-party-not-system-user.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1052

#1058 RET-4324 - Switch to tsc & yarn node over ts-node
  Dockerfile
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-1058

#1046 RET-4062 - Submit Stored Response
  src/main/controllers/StoreRespondentController.ts
  src/main/controllers/StoredToSubmitResponseController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/LinkHelpers.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/StoredToSubmitResponseController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1046

#1063 RET-4337 - Google Analytics CSP change
  src/main/modules/helmet/index.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1063

#1072 Update NodeJS version in readme
  README.md
Labels: ns:et, prd:et, rel:et-sya-pr-1072

#1065 RET-4062 - Store Response to Tribunal
  src/main/controllers/StoredResponseTribunalConfirmationController.ts
  src/main/controllers/StoredToSubmitController.ts
  src/main/controllers/StoredToSubmitResponseController.ts
  src/main/controllers/TribunalResponseCYANotSystemUserController.ts
  src/main/controllers/TribunalResponseStoreController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/StoredToSubmitHelpers.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/StoredResponseTribunalConfirmationController.test.ts
  src/test/unit/controller/TribunalResponseStoreController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1065

#1077 RET-4062 - Submit Stored Response to Tribunal
  src/main/controllers/StoredResponseTribunalConfirmationController.ts
  src/main/controllers/StoredToSubmitTribunalController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/LinkHelpers.ts
  src/main/controllers/helpers/StoredToSubmitHelpers.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/sendNotificationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/StoredToSubmitTribunalController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/LinkHelpers.test.ts
  src/test/unit/controller/helpers/StoredToSubmitHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1077

#1078 RET-4062
  src/test/unit/controller/ContactTheTribunalCYANotSystemUserController.test.ts
  src/test/unit/controller/StoreRespondentController.test.ts
  src/test/unit/controller/StoreTseController.test.ts
  src/test/unit/controller/StoredApplicationConfirmationController.test.ts
  src/test/unit/controller/StoredResponseAppConfirmationController.test.ts
  src/test/unit/controller/StoredToSubmitController.test.ts
  src/test/unit/controller/StoredToSubmitResponseController.test.ts
  src/test/unit/controller/StoredToSubmitTribunalController.test.ts
  src/test/unit/controller/TribunalResponseCYANotSystemUserController.test.ts
  src/test/unit/controller/TribunalResponseStoreController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1078

#1079 RET-4062 - Respondent Supporting Material
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1079
