Repository hmcts/et-sya-frontend, pull requests merged in 2023-03, with the labels that each got.

#705 enable slack notifications
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-sya-pr-705

#697 Set language param
  src/main/modules/oidc/index.ts
Labels: ns:et, prd:et, rel:et-sya-pr-697

#711 Ret-2917 Remove session data after submission of claim
  src/main/controllers/CaseDocumentController.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/ClaimSubmittedController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/appRequest.ts
  src/main/helper/ApiFormatter.ts
  src/main/views/claim-submitted.njk
  src/test/unit/controller/CaseDocumentController.test.ts
  src/test/unit/controller/CheckAnswers.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/mocks/mockRequest.ts
Labels: ns:et, prd:et, rel:et-sya-pr-711

#716 Ret 2785 - Respond to an application from Respondent
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/RespondentApplicationsController.ts
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/definitions/contact-applications.ts
  src/main/definitions/definition.ts
  src/main/definitions/hub.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/cy/translation/respondent-applications.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/resources/locales/en/translation/respondent-application-details.json
  src/main/resources/locales/en/translation/respondent-applications.json
  src/main/services/CaseService.ts
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/claim-details.njk
  src/main/views/respond-to-application.njk
  src/main/views/respondent-application-details.njk
  src/main/views/respondent-applications.njk
  src/main/views/your-applications.njk
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-716

#717 Fix merge issues
  src/main/controllers/helpers/ErrorHelpers.ts
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-717

#721 Ret 2785 more tests
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/test/unit/controller/ApplicationDetailsController.test.ts
  src/test/unit/controller/RespondToApplicationController.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
  src/test/unit/mocks/mockRequest.ts
Labels: ns:et, prd:et, rel:et-sya-pr-721

#726 RET-2788 fix
  src/main/controllers/SupportingMaterialController.ts
  src/main/resources/locales/cy/translation/respondent-supporting-material.json
  src/main/resources/locales/en/translation/respondent-supporting-material.json
Labels: ns:et, prd:et, rel:et-sya-pr-726

#725 Ret 2790 update
  src/main/controllers/RespondToApplicationCompleteController.ts
  src/main/controllers/SubmitRespondentController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respond-to-application-complete.json
  src/main/resources/locales/en/translation/respond-to-application-complete.json
  src/main/views/respond-to-application-complete.njk
  src/test/routes/respond-to-application-complete.test.ts
  src/test/unit/controller/RespondToApplicationCompleteController.test.ts
  src/test/unit/views/respond-to-application-complete.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-725

#724 Ret 2786 - added tests
  charts/et-sya/Chart.yaml
  src/test/routes/application-details.test.ts
  src/test/unit/views/application-details.test.ts
  src/test/unit/views/respondent-application-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-724

#727 Ret 2786 final
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/definitions/definition.ts
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/respondent-application-details.njk
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
  src/test/unit/views/respondent-applications.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-727

#729 Add dymnamic application type description
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
  src/test/unit/views/respondent-application-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-729

#731 Remove wip from running in pipeline
  src/test/end-to-end/features/WIP/empDetailsWhileOnNotice.js
  src/test/end-to-end/features/WIP/empDetailsWhileWorking.js
  src/test/end-to-end/features/WIP/employeeGotNewJob.js
  src/test/end-to-end/features/WIP/employeeNotWorking.js
  src/test/end-to-end/features/WIP/etMultipleClaimsForMyself.js
  src/test/end-to-end/features/WIP/returnToExistingClaim.js
Labels: ns:et, prd:et, rel:et-sya-pr-731

#734 Ret 3383
  src/main/controllers/CitizenHubController.ts
  src/main/controllers/RespondentApplicationsController.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/main/resources/locales/en/translation/respondent-application-details.json
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/respondent-applications.njk
  src/test/unit/controller/RespondentApplicationDetailsController.test.ts
  src/test/unit/controller/RespondentApplicationsController.test.ts
  src/test/unit/controller/helpers/PageContentHelpers.test.ts
  src/test/unit/controller/helpers/TseRespondentApplicationHelpers.test.ts
  src/test/unit/views/respondent-application-details.test.ts
  src/test/unit/views/respondentApplicationDetails.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-734

#735 Adding the Fix to the Nightly failures...
  src/test/end-to-end/helpers/commonFlowContent.js
Labels: ns:et, prd:et, rel:et-sya-pr-735

#739 Ret 3316. Remove 'personal details' hub section
  src/main/controllers/CitizenHubController.ts
  src/main/definitions/hub.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/mocks/mockUserCaseWithCitizenHubLinks.ts
  src/test/end-to-end/pages/citizenHub/citizenHub.js
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-739
