Repository hmcts/et-sya-frontend, pull requests merged in 2023-07, with the labels that each got.

#895 RET-3895
  src/main/components/form/validator.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/resources/locales/cy/translation/acas-cert-num.json
  src/main/resources/locales/en/translation/acas-cert-num.json
  src/test/unit/controller/helpers/ErrorHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-895

#890 Ret 3690 - Update application states
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/ApplicationStateHelper.ts
  src/main/controllers/helpers/TseRespondentApplicationHelpers.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/views/application-details.njk
  src/test/unit/controller/helpers/ApplicationStateHelper.test.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
Labels: ns:et, prd:et, rel:et-sya-pr-890

#897 Fix decision state update
  src/main/controllers/JudgmentDetailsController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/services/CaseService.ts
  src/test/routes/judgment-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-897

#898 Ret 3785 new
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
  config/custom-environment-variables.json
  config/default.json
  src/main/controllers/ReturnToExistingController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/definitions/constants.ts
  src/main/utils/getLegacyUrlFromLng.ts
  src/test/routes/return-to-existing.test.ts
  src/test/unit/utils/getLegacyUrlFromLng.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-898

#900 RET-3690 - Prevent tag transforming to uppercase
  src/main/views/your-applications.njk
Labels: ns:et, prd:et, rel:et-sya-pr-900

#903 RET-3901: Fix for Holding page not displayed
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/definitions/hub.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-903

#894 RET-3684 fixes
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/views/respondent-application-details.njk
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/views/respondent-application-details.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-894

#905 Update Chart.yaml
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-905

#908 Ret 3684 banner fix
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-908

#899 RET-3714: Response from respondent status changes
  charts/et-sya/Chart.yaml
  src/main/controllers/CaseDocumentController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/citizen-hub/CitizenHubDocumentController.ts
  src/main/controllers/helpers/CaseDocumentHelper.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/definitions/constants.ts
  src/main/definitions/hub.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/test/unit/controller/helpers/CaseDocumentHelper.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-899

#904 Ret 3682 - Request and applications to the tribunal (CitizenUI Status tags)
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/resources/mocks/mockUserCaseWithoutTseApp.ts
  src/test/unit/controller/citizen-hub/CitizenHubController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
Labels: ns:et, prd:et, rel:et-sya-pr-904

#896 RET-3844
  charts/et-sya/Chart.yaml
  src/main/controllers/AcasCertNumController.ts
  src/main/controllers/CheckYourAnswersController.ts
  src/main/controllers/NoAcasNumberController.ts
  src/main/controllers/RespondentAddInCheckAnswerController.ts
  src/main/controllers/RespondentDetailsCheckController.ts
  src/main/controllers/RespondentRemoveController.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/controllers/helpers/RespondentHelpers.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/respondent-details-check.json
  src/main/resources/locales/en/translation/et1-details.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  src/main/views/check-your-answers.njk
  src/main/views/claim-details.njk
  src/main/views/respondent-details-check.njk
  src/test/unit/controller/RespondentAddInCheckAnswerController.test.ts
  src/test/unit/controller/RespondentRemoveController.test.ts
  src/test/unit/views/respondent-details-check.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-896

#909 RET-3684. Fix banner for all respondent responses to TSE applications
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-909

#911 CVE-2023-26136
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-911

#912 RET-3844
  src/main/controllers/RespondentRemoveController.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/views/check-your-answers.njk
  src/main/views/respondent-details-check.njk
Labels: ns:et, prd:et, rel:et-sya-pr-912

#913 RET-3912 - Open redirect on logout
  package.json
  src/main/modules/oidc/index.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-913

#914 Ret 3792 - Responding to the tribunal
  src/main/controllers/helpers/AdminNotificationHelper.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/test/unit/controller/helpers/AdminNotificationsHelper.test.ts
  src/test/unit/controller/helpers/ApplicationStateHelper.test.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-914

#915 Ret 3792 fix
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/AdminNotificationHelper.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/services/CaseService.ts
  src/main/views/all-judgments.njk
  src/test/unit/controller/helpers/AdminNotificationsHelper.test.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-915

#916 RET-3918
  src/main/resources/locales/en/translation/template.json
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/helpers/contactUs.js
Labels: ns:et, prd:et, rel:et-sya-pr-916

#922 Update terraform provider version to latest
  infrastructure/.terraform-version
  infrastructure/state.tf
  renovate.json
Labels: ns:et, prd:et, no-changes, rel:et-sya-pr-922

#921 updated ret-3764 implementation
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/resources/locales/cy/translation/response-from-respondent.json
  src/main/resources/locales/en/translation/response-from-respondent.json
  src/main/views/response-from-respondent-view.njk
  src/test/unit/views/response-from-respondent-view.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-921
