Repository hmcts/et-sya-frontend, pull requests merged in 2024-02, with the labels that each got.

#1190 RET-4230
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/describe-what-happened.json
  src/main/resources/locales/en/translation/describe-what-happened.json
  src/main/resources/locales/en/translation/hearing-document-upload.json
  src/test/unit/components/validator.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1190

#1206 RET-4731
  src/main/resources/locales/cy/translation/accessibility-statement.json
  src/main/resources/locales/cy/translation/claim-submitted.json
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/cy/translation/sidebar-contact-us.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/accessibility-statement.json
  src/main/resources/locales/en/translation/claim-submitted.json
  src/main/resources/locales/en/translation/contact-the-tribunal.json
  src/main/resources/locales/en/translation/sidebar-contact-us.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/claim-submitted.njk
  src/main/views/contact-the-tribunal.njk
  src/main/views/home.njk
  src/main/views/template.njk
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/helpers/contactUs.js
  src/test/end-to-end/helpers/contactUsForCitizenHub.js
  src/test/unit/views/claim-submitted.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1206

#1205 RET-4751
  src/main/views/citizen-hub-sidebar.njk
Labels: ns:et, prd:et, rel:et-sya-pr-1205

#1226 RET-4125: Fix party to respond not showing on notification details page
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1226

#1227 RET-3576
  src/main/controllers/ContactTheTribunalCYANotSystemUserController.ts
  src/test/unit/controller/ContactTheTribunalCYANotSystemUserController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1227

#1146 Ret 4393 - Provide something tribunal asked for- Display response from claimant
  README.md
  src/main/controllers/AttachmentController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/complexTypes/sendNotificationTypeItem.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/tribunal-order-or-request-details.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/tribunal-order-or-request-details.json
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/tribunal-order-or-request-details.njk
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockNotificationItem.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1146

#1233 Rule-92 Fix Merge
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/StoredToSubmitController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/ContactTheTribunalCYAHelper.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
  src/test/unit/controller/helpers/ApplicationDetailsHelper.test.ts
  src/test/unit/controller/helpers/ContactTheTribunalCYAHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1233

#1216 RET-4659
  src/main/controllers/StillWorkingController.ts
  src/test/unit/controller/StillWorkingController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1216

#1251 Dynatrace RUM
  package.json
  src/main/views/template.njk
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1251

#1255 Dynatrace Rum
  src/main/modules/helmet/index.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1255

#1256 Fix nightly functional test
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-1256

#1247 RET-4801
  src/main/definitions/constants.ts
  src/test/unit/controller/helpers/TypeOfClaimHelpers.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1247

#1248 RET-4806
  src/main/controllers/TribunalResponseCYAController.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1248

#1259 RET-3577 Fix
  src/main/controllers/TribunalResponseCYANotSystemUserController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1259
