Repository hmcts/et-sya-frontend, pull requests merged in 2024-09, with the labels that each got.

#1666 Update CSPs around Webchat to stop throwing errors
  src/main/modules/helmet/index.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1666

#1665 RET-3229
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/template.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1665

#1674 Remove Axios CVE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1674

#1678 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-1678

#1670 RET-5385
  src/main/controllers/ReturnToExistingController.ts
  src/main/resources/locales/cy/translation/return-to-existing.json
  src/main/resources/locales/en/translation/return-to-existing.json
  src/main/views/return-to-claim.njk
  src/test/unit/controller/ReturnToExistingController.test.ts
  src/test/unit/views/return-to-claim.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1670

#1619 work address changes
  src/main/controllers/WorkAddressController.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/work-address.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/work-address.json
  src/main/views/work-address.njk
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/unit/views/work-address.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1619

#1703 RET-5360
  src/main/resources/locales/en/translation/claim-jurisdiction-selection.json
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/unit/views/claim-jurisdiction-selection.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1703

#1711 Update WebChat script
  src/main/views/components/web-chat.njk
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-1711
