Repository hmcts/et-sya-frontend, pull requests merged in 2024-05, with the labels that each got.

#1376 RET-5063
  src/main/controllers/helpers/TypeOfClaimHelpers.ts
  src/main/definitions/constants.ts
  src/main/definitions/postcode.ts
  src/test/unit/controller/WorkPostcodeController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1376

#1397 Disable workAddressTypes Functional Test
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-1397

#1409 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-1409

#1410 RET-5089
  src/main/resources/locales/cy/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/views/lip-or-representative.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1410

#1408 RET-5071
  src/main/views/footer.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1408

#1145 RET-3823 - Lead Case view
  src/main/assets/scss/main.scss
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/multiples/MultiplePanelHelper.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/multiples/multiplePanelData.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/mocks/mockUserCaseWithCitizenHubLinks.ts
  src/main/views/citizen-hub.njk
  src/main/views/multiples/multiplePanel.njk
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/multiples/MultiplePanelHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1145

#1424 Add Owasp Zap scanner
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-1424

#1423 CUI - Fix welsh translation for banner
  src/main/resources/locales/cy/translation/citizen-hub.json
Labels: ns:et, prd:et, rel:et-sya-pr-1423

#1425 RET-3825 - Show stayed and nonlead cases
  package.json
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/multiples/MultiplePanelHelper.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/views/multiples/multiplePanel.njk
  src/test/unit/controller/helpers/multiples/MultiplePanelHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  yarn.lock
Labels: ns:et, prd:et, aat/add-or-update, prod/no-changes, rel:et-sya-pr-1425

#1445 RET-5110
  src/main/controllers/LipOrRepController.ts
  src/main/definitions/case.ts
  src/main/resources/locales/cy/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/views/lip-or-representative.test.ts
Labels: ns:et, prd:et, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:et-sya-pr-1445

#1262 Do Not Merge - RET-4584
  charts/et-sya/Chart.yaml
  charts/et-sya/values.yaml
  config/default.json
  src/main/controllers/LipOrRepController.ts
  src/main/controllers/MakingClaimAsLegalRepController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/lip-or-representative.json
  src/main/resources/locales/cy/translation/making-claim-as-legal-representative.json
  src/main/resources/locales/en/translation/lip-or-representative.json
  src/main/resources/locales/en/translation/making-claim-as-legal-representative.json
  src/main/views/making-claim-as-legal-representative.njk
  src/test/unit/controller/LipOrRepController.test.ts
  src/test/unit/controller/MakingClaimAsLegalRepController.test.ts
  src/test/unit/views/lip-or-representative.test.ts
  src/test/unit/views/making-claim-as-legal-representative.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1262
