Repository hmcts/et-sya-frontend, pull requests merged in 2024-06, with the labels that each got.

#1439 DO NOT MERGE - RET-5173 - To be merged 03/06/2024
  src/main/definitions/constants.ts
  src/main/definitions/postcode.ts
  src/test/unit/controller/WorkPostcodeController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/controller/helpers/TypeOfClaimHelpers.test.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1439

#1448 RET-5185
  src/main/controllers/StoredToSubmitController.ts
  src/main/controllers/StoredToSubmitResponseController.ts
  src/main/controllers/StoredToSubmitTribunalController.ts
  src/test/unit/controller/StoredToSubmitTribunalController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1448

#1469 RET-5198
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1469

#1475 RET-5203
  src/main/controllers/AboutHearingDocumentsController.ts
  src/main/controllers/HearingDocumentFileController.ts
  src/main/controllers/HearingDocumentUploadController.ts
  src/main/controllers/helpers/HearingDocumentUploadHelper.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/HearingDocumentFileController.test.ts
  src/test/unit/controller/HearingDocumentUploadController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1475

#1489 Update postcode.ts
  src/main/definitions/postcode.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1489

#1481 To be merged 17/06/2024 - RET-5208
  src/main/definitions/constants.ts
  src/main/definitions/postcode.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1481

#1497 Ret 5088 - Skip Rule 92 for ECC
  package.json
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1497

#1351 RET-5230
  src/main/definitions/contact-applications.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1351
