Repository hmcts/et-sya-frontend, pull requests merged in 2024-04, with the labels that each got.

#1270 RET-4899
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/StoreTseController.ts
  src/main/controllers/StoredApplicationConfirmationController.ts
  src/main/controllers/StoredToSubmitController.ts
  src/main/controllers/TribunalResponseStoreController.ts
  src/main/controllers/YourAppsToTheTribunalController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/ApplicationDetailsHelper.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/StoredToSubmitHelpers.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/definitions/contact-applications.ts
  src/main/helper/ApiFormatter.ts
  src/main/services/CaseService.ts
  src/test/unit/controller/StoreTseController.test.ts
  src/test/unit/controller/StoredApplicationConfirmationController.test.ts
  src/test/unit/controller/StoredToSubmitController.test.ts
  src/test/unit/controller/TribunalResponseStoreController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/views/stored-application-confirmation.test.ts
  src/test/unit/views/stored-to-submit.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1270

#1158 RET- 4165 - Show ECC response notifications + fix status tags
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/tribunal-respond-to-order.json
  src/main/resources/locales/en/translation/tribunal-respond-to-order.json
  src/main/services/CaseService.ts
  src/main/views/tribunal-respond-to-order.njk
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
  src/test/unit/controller/TribunalOrderOrRequestDetailsController.test.ts
  src/test/unit/controller/TribunalOrdersAndRequestsController.test.ts
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/mocks/mockTribunalResponse.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
Labels: ns:et, prd:et, add-or-update, rel:et-sya-pr-1158

#1286 Rule-92 v2 Fix merge conflicts
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/StoredToSubmitTribunalController.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/StoredToSubmitHelpers.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1286

#1291 RET-4062
  src/main/controllers/StoredToSubmitController.ts
  src/main/controllers/StoredToSubmitResponseController.ts
  src/main/controllers/StoredToSubmitTribunalController.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1291

#1296 RET-3578
  src/main/resources/locales/en/translation/stored-to-submit.json
Labels: ns:et, prd:et, aat/add-or-update, rel:et-sya-pr-1296

#1300 RET-4062
  src/main/controllers/helpers/StoredToSubmitHelpers.ts
  src/test/unit/controller/helpers/StoredToSubmitHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1300

#1301 RET-3578
  src/main/resources/locales/cy/translation/stored-to-submit.json
Labels: ns:et, prd:et, rel:et-sya-pr-1301

#1302 RET-4987
  src/main/controllers/StoredToSubmitController.ts
  src/main/controllers/StoredToSubmitResponseController.ts
  src/main/controllers/StoredToSubmitTribunalController.ts
  src/test/unit/controller/StoredToSubmitController.test.ts
  src/test/unit/controller/StoredToSubmitResponseController.test.ts
  src/test/unit/controller/StoredToSubmitTribunalController.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1302

#1297 RET-4877
  src/main/resources/locales/en/translation/et1-details.json
Labels: ns:et, prd:et, enable_keep_helm, aat/add-or-update, rel:et-sya-pr-1297

#1311 RET-4997
  src/main/controllers/RespondToTribunalResponseController.ts
Labels: ns:et, prd:et, aat/add-or-update, rel:et-sya-pr-1311

#1316 RET-5004
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
Labels: ns:et, prd:et, aat/add-or-update, rel:et-sya-pr-1316

#1308 RET-4979
  src/main/resources/locales/cy/translation/accessibility-statement.json
  src/main/resources/locales/en/translation/accessibility-statement.json
  src/main/views/accessibility-statement.njk
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1308

#1319 RET-5011 - Add value from Scottish configs
  src/main/controllers/helpers/AdminNotificationHelper.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/common.json
Labels: ns:et, prd:et, rel:et-sya-pr-1319

#1331 RET-5005
  src/main/controllers/helpers/AdminNotificationHelper.ts
  src/test/unit/controller/helpers/AdminNotificationsHelper.test.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
Labels: ns:et, prd:et, aat/add-or-update, rel:et-sya-pr-1331

#1345 Formidable CVE
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1345
