Repository hmcts/et-sya-frontend, pull requests merged in 2024-03, with the labels that each got.

#1238 RET-4334
  src/main/controllers/SubmitBundlesHearingDocsCYAController.ts
  src/main/controllers/SubmitRespondentController.ts
  src/main/controllers/SubmitTribunalCYAController.ts
  src/main/controllers/TribunalResponseSubmitController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/test/unit/controller/SubmitBundlesHearingDocsCYAController.test.ts
  src/test/unit/controller/SubmitRespondentController.test.ts
  src/test/unit/controller/SubmitTseController.test.ts
  src/test/unit/controller/TribunalResponseSubmitController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1238

#1261 RET-4725
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1261

#1252 RET-4807
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1252

#1265 RET-4221
  src/main/components/form/address_validator.ts
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/PlaceOfWorkController.ts
  src/main/controllers/RespondentAddressController.ts
  src/test/unit/components/address_validator.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1265

#1174 RET-4386
  src/main/controllers/helpers/EmploymentAnswersHelper.ts
  src/main/controllers/helpers/RespondentAnswersHelper.ts
  src/main/resources/locales/cy/translation/acas-cert-num.json
  src/main/resources/locales/cy/translation/address-details.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/et1-details.json
  src/main/resources/locales/cy/translation/update-preference.json
  src/main/resources/locales/en/translation/et1-details.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1174

#1274 Add Dynatrace monitoring in prod
  src/main/views/template.njk
Labels: ns:et, prd:et, rel:et-sya-pr-1274
