Repository hmcts/et-sya-frontend, pull requests merged in 2024-01, with the labels that each got.

#1168 Fixing typo
  package.json
  src/main/resources/locales/en/translation/respondent-details-check.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1168

#1172 RET-4642
  src/main/views/citizen-hub-sidebar.njk
  src/main/views/citizen-hub.njk
Labels: ns:et, prd:et, rel:et-sya-pr-1172

#1173 RET-4630
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/YourAppsToTheTribunalController.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/controllers/helpers/YourAppsToTheTribunalHelpers.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/controller/helpers/YourAppsToTheTribunalHelpers.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1173

#1152 RET-4551, RET-4298
  README.md
  bin/kill-redis-server.sh
  bin/kill-residual-processes.sh
  src/main/controllers/AllDocumentsController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/AllDocumentsHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/definitions/hub.ts
  src/main/views/all-documents.njk
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
  src/test/unit/controller/helpers/AllDocumentsHelper.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockUserCaseWithRespondentDocuments.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1152

#1159 Ret 4558 - Welsh translation amendments
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-amend.json
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/cy/translation/describe-what-happened.json
  src/main/resources/locales/cy/translation/judgment-details.json
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/cy/translation/respondent-applications.json
  src/main/resources/locales/cy/translation/respondent-supporting-material.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/cy/translation/tribunal-order-or-request-details.json
  src/main/resources/locales/cy/translation/tribunal-response-cya.json
  src/main/resources/locales/cy/translation/your-applications.json
  src/main/resources/locales/en/translation/template.json
  src/main/resources/locales/en/translation/tribunal-order-or-request-details.json
  src/main/views/footer.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1159

#1179 RET-4682
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/helpers/TypeOfClaimHelpers.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/helpers/TypeOfClaimHelpers.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1179
