Repository hmcts/et-sya-frontend, pull requests merged in 2024-07, with the labels that each got.

#1531 RET-5241
  src/main/views/all-documents.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1531

#1539 Update package.json
  package.json
Labels: ns:et, prd:et, rel:et-sya-pr-1539

#1505 RET-5229
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondToTribunalResponseController.ts
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/helpers/RespondToApplicationHelper.ts
  src/test/unit/controller/RespondToApplicationController.test.ts
  src/test/unit/controller/RespondToTribunalResponseController.test.ts
  src/test/unit/controller/RespondentSupportingMaterialController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1505

#1532 To be merged 15 July - RET-5240
  src/main/definitions/constants.ts
  src/main/definitions/postcode.ts
  src/test/unit/controller/WorkPostcodeController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/controller/helpers/TypeOfClaimHelpers.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1532

#1564 Adjust postcodes
  src/main/definitions/postcode.ts
  src/test/unit/controller/WorkPostcodeController.test.ts
  src/test/unit/controller/helpers/TypeOfClaimHelpers.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1564

#1536 RET-5271
  src/main/controllers/ContactTheTribunalFileController.ts
  src/main/controllers/RespondentSupportingMaterialController.ts
  src/main/controllers/RespondentSupportingMaterialFileController.ts
  src/main/controllers/StoreRespondentController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/TribunalResponseStoreController.ts
  src/main/controllers/helpers/RespondentSupportingMaterialHelper.ts
  src/test/unit/controller/ContactTheTribunalFileController.test.ts
  src/test/unit/controller/RespondentSupportingMaterialFileController.test.ts
  src/test/unit/controller/StoreRespondentController.test.ts
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  src/test/unit/controller/TribunalResponseStoreController.test.ts
  src/test/unit/controller/helpers/RespondentSupportingMaterialHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1536

#1538 RET-3052 WCAG Accessibility
  src/main/assets/scss/main.scss
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/claimant-applications.njk
  src/main/views/home.njk
  src/main/views/template.njk
  src/test/end-to-end/helpers/commonFlowContent.js
  src/test/end-to-end/helpers/contactUs.js
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1538
