Repository hmcts/et-sya-frontend, pull requests merged in 2024-08, with the labels that each got.

#1586 RET-5332
  src/main/controllers/helpers/HearingHelpers.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/helper/state-sequence.ts
  src/test/unit/controller/helpers/HearingHelpers.test.ts
  src/test/unit/helper/state-sequence.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1586

#1594 RET-5343
  src/main/resources/locales/en/translation/cookie-preferences.json
  src/main/views/footer.njk
  src/main/views/template.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1594

#1606 RET-5357
  src/main/resources/locales/cy/translation/accessibility-statement.json
  src/main/resources/locales/en/translation/accessibility-statement.json
  src/main/views/accessibility-statement.njk
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1606

#1616 Update axios to 1.7.4
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1616

#1635 RET-5357
  src/main/controllers/AccessibilityStatementController.ts
  src/main/resources/locales/cy/translation/accessibility-statement.json
  src/main/resources/locales/en/translation/accessibility-statement.json
  src/main/views/accessibility-statement.njk
  src/test/unit/views/accessibility-statement.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1635

#1615 RET-5367
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1615

#1643 Fix CVE Temp
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-1643

#1654 Danny Pipeline Optimisations 1 - Attempt to resolve redundant puppeteer installs
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1654

#1636 RET-5373
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubProgressBarHelper.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/govuk/hmctsProgressBar.ts
  src/main/helper/ApiFormatter.ts
  src/main/helper/state-sequence.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/views/citizen-hub.njk
  src/test/unit/controller/helpers/CitizenHubProgressBarHelper.test.ts
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/helper/state-sequence.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1636
