Repository hmcts/et-sya-frontend, pull requests merged in 2025-02, with the labels that each got.

#1834 Ret 5112 patch final
  Jenkinsfile_nightly
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1834

#1855 Update known issues
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1855

#1858 reset the zap filter library annotation
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-1858

#1867 RET-5647
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-1867
