Repository hmcts/et-sya-frontend, pull requests merged in 2025-07, with the labels that each got.

#2058 RET-5774
  src/main/resources/locales/cy/translation/application-complete.json
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-non-compliance.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-respondent.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-strike.json
  src/main/resources/locales/cy/translation/contact-the-tribunal-withdraw.json
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/cy/translation/your-applications.json
  src/main/resources/locales/en/translation/application-complete.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/contact-the-tribunal-non-compliance.json
  src/main/resources/locales/en/translation/contact-the-tribunal-respondent.json
  src/main/resources/locales/en/translation/contact-the-tribunal-strike.json
  src/main/resources/locales/en/translation/contact-the-tribunal-withdraw.json
  src/main/resources/locales/en/translation/contact-the-tribunal.json
  src/main/resources/locales/en/translation/your-applications.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2058

#2071 Update CSP for Gov5 Changes
  src/main/modules/helmet/index.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2071

#2090 fix cve
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-2090

#2065 RET-5895
  src/main/components/form/address-validator.ts
  src/main/components/form/claim-details-validator.ts
  src/main/components/form/currency-validator.ts
  src/main/components/form/date-validator.ts
  src/main/components/form/validator.ts
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/AddressPostCodeEnterController.ts
  src/main/controllers/ClaimDetailsCheckController.ts
  src/main/controllers/CompensationController.ts
  src/main/controllers/EmploymentAndRespondentCheckController.ts
  src/main/controllers/NewJobPayController.ts
  src/main/controllers/PayController.ts
  src/main/controllers/PensionController.ts
  src/main/controllers/PersonalDetailsCheckController.ts
  src/main/controllers/PlaceOfWorkController.ts
  src/main/controllers/RespondentPostCodeEnterController.ts
  src/main/controllers/WorkPostCodeEnterController.ts
  src/main/controllers/helpers/ErrorHelpers.ts
  src/main/controllers/helpers/RespondentAddressHelper.ts
  src/main/definitions/constants.ts
  src/main/definitions/currency-fields.ts
  src/main/definitions/dates.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/compensation.json
  src/main/resources/locales/cy/translation/new-job-pay.json
  src/main/resources/locales/cy/translation/pay.json
  src/main/resources/locales/cy/translation/pension.json
  src/main/resources/locales/en/translation/compensation.json
  src/main/resources/locales/en/translation/new-job-pay.json
  src/main/resources/locales/en/translation/pay.json
  src/main/resources/locales/en/translation/pension.json
  src/test/unit/components/address-validator.test.ts
  src/test/unit/components/claim-details-validator.test.ts
  src/test/unit/components/currency-validator.test.ts
  src/test/unit/components/date-validator.test.ts
  src/test/unit/components/form.test.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/ClaimDetailsCheckController.test.ts
  src/test/unit/controller/CompensationController.test.ts
  src/test/unit/controller/EmploymentAndRespondentCheckController.test.ts
  src/test/unit/controller/NewJobPayController.test.ts
  src/test/unit/controller/PayController.test.ts
  src/test/unit/controller/PensionController.test.ts
  src/test/unit/views/pension.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2065

#2096 Use the app insights connection string rather than depreciated instrumentation key
  charts/et-sya/Chart.yaml
  charts/et-sya/values.aat.template.yaml
  charts/et-sya/values.preview.template.yaml
  charts/et-sya/values.yaml
  config/default.json
  src/main/modules/appinsights/index.ts
  src/main/modules/properties-volume/index.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2096

#2103 RET-5914
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2103

#2110 RET-5914
  src/main/controllers/helpers/ClaimDetailsAnswersHelper.ts
  src/test/unit/controller/CheckAnswers.test.ts
  src/test/unit/views/check-your-answers.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2110
