Repository hmcts/et-sya-frontend, pull requests merged in 2025-06, with the labels that each got.

#2018 Use OCI repository instead of Helm
  charts/et-sya/Chart.yaml
Labels: ns:et, prd:et, rel:et-sya-pr-2018

#1697 RET-4646
  src/main/controllers/HearingDetailsController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/HearingHelpers.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/complexTypes/sendNotificationTypeItem.ts
  src/main/definitions/constants.ts
  src/main/definitions/hearingDetails.ts
  src/main/helper/dateInLocale.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/hearing-details.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/hearing-details.json
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/citizen-hub-notification-banner/notifications-hearings.njk
  src/main/views/citizen-hub-notification-banner/notifications.njk
  src/main/views/hearing-details.njk
  src/test/routes/citizen-hub.test.ts
  src/test/unit/controller/HearingDetailsController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/HearingHelpers.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
  src/test/unit/helper/dateInLocale.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1697

#2028 Bump brace expansion
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-2028

#2031 RET-5854
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/RespondentContactDetailsHelper.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/RespondentContactDetailsHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2031

#2034 RET-5415
  src/main/controllers/AppointLegalRepController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/appoint-legal-representative.json
  src/main/resources/locales/en/translation/appoint-legal-representative.json
  src/main/views/appoint-legal-representative.njk
  src/main/views/citizen-hub.njk
  src/test/unit/controller/AppointLegalRepController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2034

#2053 Update Fortify client dependency and change Maven repository URL
  src/test/java/build.gradle
Labels: ns:et, prd:et, rel:et-sya-pr-2053

#2049 RET-5419
  src/main/controllers/ContactTheTribunalController.ts
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/ClaimantRepresentative.ts
  src/main/helper/ApiFormatter.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/contact-the-tribunal.json
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/citizen-hub-notification-banner/notifications-claimant-represented.njk
  src/main/views/contact-the-tribunal.njk
  src/main/views/respondent-application-details.njk
  src/test/unit/helper/ApiFormatter.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
Labels: ns:et, prd:et, rel:et-sya-pr-2049
