Repository hmcts/et-sya-frontend, pull requests merged in 2025-03, with the labels that each got.

#1891 disable zap security scan
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-1891

#1904 RET-5723
  src/main/controllers/RespondentApplicationDetailsController.ts
  src/main/controllers/helpers/CopyToOtherPartyHelper.ts
  src/main/definitions/constants.ts
  src/test/unit/controller/helpers/CopyToOtherPartyHelper.test.ts
  src/test/unit/controller/helpers/RespondentApplcationCYAHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1904

#1907 RET-5602 - Migrate SYA tests to playwright framework
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  playwright.config.ts
  playwrighte2e/common/web.actions.ts
  playwrighte2e/data/test-file/test-doc.pdf
  playwrighte2e/fixtures/common.fixture.ts
  playwrighte2e/fixtures/page.fixture.ts
  playwrighte2e/pages/basePage.ts
  playwrighte2e/pages/claimDetailsPage.ts
  playwrighte2e/pages/claimStartPage.ts
  playwrighte2e/pages/employmentDetailsPage.ts
  playwrighte2e/pages/loginPage.ts
  playwrighte2e/pages/makeClaimPage.ts
  playwrighte2e/pages/personalDetailsPage.ts
  playwrighte2e/pages/saveCardPage.ts
  playwrighte2e/pages/submitPage.ts
  playwrighte2e/tests/accessibility.test.ts
  playwrighte2e/tests/submitSingleClaim.test.ts
  playwrighte2e/utils/DateUtilComponent.ts
  playwrighte2e/utils/config.ts
  src/main/controllers/JobTitleController.ts
  src/main/modules/routes/routes.ts
  src/test/unit/components/validator.test.ts
  src/test/unit/controller/ContactTheTribunalSelectedController.test.ts
  webpack.config.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-sya-pr-1907
