Repository hmcts/et-sya-frontend, pull requests merged in 2025-04, with the labels that each got.

#1899 RET-5708
  src/main/controllers/helpers/CaseHelpers.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1899

#1922 RET-5744
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/respondent-application-details.json
  src/main/resources/locales/cy/translation/tribunal-respond-to-order.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/respondent-application-details.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1922

#1923 RET-5682
  src/main/views/form/multipartForm.njk
  src/test/unit/views/describe-what-happened.test.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1923

#1934 RET-5745
  src/main/modules/helmet/index.ts
  src/main/views/home.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1934
