Repository hmcts/et-sya-frontend, pull requests merged in 2025-05, with the labels that each got.

#1954 Re-enable delay on waiting for work address
  src/test/end-to-end/pages/employmentDetails/respondentDetailsPages.js
Labels: ns:et, prd:et, rel:et-sya-pr-1954

#1956 functional test fix
  playwrighte2e/pages/employmentDetailsPage.ts
  playwrighte2e/pages/personalDetailsPage.ts
Labels: ns:et, prd:et, rel:et-sya-pr-1956

#1958 Removing perftest for Dean
  Jenkinsfile_CNP
Labels: ns:et, prd:et, rel:et-sya-pr-1958

#1962 formidable vulnerability suppress
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-1962

#1944 RET-5662
  src/main/controllers/ContactTheTribunalSelectedController.ts
  src/main/resources/locales/cy/translation/contact-the-tribunal-selected.json
  src/main/resources/locales/en/translation/contact-the-tribunal-selected.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1944

#1910 RET-5718
  src/main/controllers/GeneralCorrespondenceNotificationDetailsController.ts
  src/main/controllers/StoredToSubmitTribunalController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/citizen-hub/CitizenHubDocumentController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/DocumentHelpers.ts
  src/main/controllers/helpers/GeneralCorrespondenceHelper.ts
  src/main/controllers/helpers/LinkHelpers.ts
  src/main/controllers/helpers/PageContentHelpers.ts
  src/main/controllers/helpers/TribunalOrderOrRequestHelper.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/general-correspondence-notification-details.json
  src/main/resources/locales/cy/translation/notification-details.json
  src/main/resources/locales/cy/translation/notification-subjects.json
  src/main/resources/locales/cy/translation/notifications.json
  src/main/resources/locales/cy/translation/tribunal-orders-and-requests.json
  src/main/resources/locales/cy/translation/tribunal-respond-to-order.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/general-correspondence-notification-details.json
  src/main/resources/locales/en/translation/notification-details.json
  src/main/resources/locales/en/translation/notification-subjects.json
  src/main/resources/locales/en/translation/notifications.json
  src/main/resources/locales/en/translation/tribunal-orders-and-requests.json
  src/main/resources/locales/en/translation/tribunal-respond-to-order.json
  src/main/views/citizen-hub-notification-banner.njk
  src/main/views/notification-details.njk
  src/main/views/notifications.njk
  src/test/end-to-end/pages/citizenHub/citizenHub.js
  src/test/unit/controller/AttachmentController.test.ts
  src/test/unit/controller/StoredResponseTribunalConfirmationController.test.ts
  src/test/unit/controller/StoredToSubmitTribunalController.test.ts
  src/test/unit/controller/TribunalOrderOrRequestDetailsController.test.ts
  src/test/unit/controller/TribunalOrdersAndRequestsController.test.ts
  src/test/unit/controller/citizen-hub/CitizenHubDocumentController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/DocumentHelpers.test.ts
  src/test/unit/controller/helpers/GeneralCorrespondenceHelper.test.ts
  src/test/unit/controller/helpers/LinkHelpers.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1910

#1943 RET-5516
  src/main/controllers/RespondentContactDetailsController.ts
  src/main/controllers/helpers/CitizenHubHelper.ts
  src/main/controllers/helpers/RespondentContactDetailsHelper.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/representative.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/definitions/hub.ts
  src/main/helper/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/respondent-contact-details.json
  src/main/resources/locales/en/translation/citizen-hub.json
  src/main/resources/locales/en/translation/respondent-contact-details.json
  src/main/views/respondent-contact-details.njk
  src/test/unit/controller/RespondentContactDetailsController.test.ts
  src/test/unit/controller/helpers/CitizenHubHelper.test.ts
  src/test/unit/controller/helpers/RespondentContactDetailsHelper.test.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/views/citizen-hub.test.ts
Labels: ns:et, prd:et, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:et-sya-pr-1943

#1972 DTSPO-24173 Fix ZAP security scanner alerting filters
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-sya-pr-1972

#1933 fix ET1 online flow
  playwrighte2e/pages/claimDetailsPage.ts
  playwrighte2e/pages/claimStartPage.ts
  playwrighte2e/pages/personalDetailsPage.ts
  playwrighte2e/tests/submitSingleClaim.test.ts
  src/main/components/form/claimDetailsValidator.ts
  src/main/controllers/AcasMultipleController.ts
  src/main/controllers/ClaimDetailsCheckController.ts
  src/main/controllers/EmploymentAndRespondentCheckController.ts
  src/main/controllers/PastEmployerController.ts
  src/main/controllers/PersonalDetailsCheckController.ts
  src/main/controllers/StepsToMakingYourClaimController.ts
  src/main/controllers/StillWorkingController.ts
  src/main/controllers/TypeOfClaimController.ts
  src/main/controllers/UpdatePreferenceController.ts
  src/main/controllers/ValidNoAcasReasonController.ts
  src/main/controllers/VideoHearingsController.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/RedirectHelpers.ts
  src/main/resources/locales/cy/translation/claim-details-check.json
  src/main/resources/locales/cy/translation/past-employer.json
  src/main/resources/locales/cy/translation/reasonable-adjustments.json
  src/main/resources/locales/cy/translation/tasklist-check.json
  src/main/resources/locales/cy/translation/type-of-claim.json
  src/main/resources/locales/cy/translation/update-preference.json
  src/main/resources/locales/cy/translation/video-hearings.json
  src/main/resources/locales/en/translation/claim-details-check.json
  src/main/resources/locales/en/translation/past-employer.json
  src/main/resources/locales/en/translation/reasonable-adjustments.json
  src/main/resources/locales/en/translation/steps-to-making-your-claim.json
  src/main/resources/locales/en/translation/tasklist-check.json
  src/main/resources/locales/en/translation/type-of-claim.json
  src/main/resources/locales/en/translation/update-preference.json
  src/main/resources/locales/en/translation/video-hearings.json
  src/main/utils/RedisUtils.ts
  src/test/end-to-end/helpers/commonFlow.js
  src/test/end-to-end/pages/personalDetails/enterPersonalDetails.js
  src/test/routes/acas-multiple.test.ts
  src/test/routes/update-preference.test.ts
  src/test/routes/valid-no-acas-reason.test.ts
  src/test/routes/video-hearings.test.ts
  src/test/unit/components/claimDetailsValidator.test.ts
  src/test/unit/controller/AcasMultipleController.test.ts
  src/test/unit/controller/ClaimDetailsCheckController.test.ts
  src/test/unit/controller/EmploymentAndRespondentCheckController.test.ts
  src/test/unit/controller/PastEmployerController.test.ts
  src/test/unit/controller/PersonalDetailsCheckController.test.ts
  src/test/unit/controller/StillWorkingController.test.ts
  src/test/unit/controller/TypeOfClaimController.test.ts
  src/test/unit/controller/UpdatePreferenceController.test.ts
  src/test/unit/controller/ValidNoAcasReasonController.test.ts
  src/test/unit/controller/VideoHearingsController.test.ts
  src/test/unit/controller/helpers/CaseHelpers.test.ts
  src/test/unit/utils/RedisUtils.test.ts
  src/test/unit/views/steps-to-making-your-claim.test.ts
  src/test/unit/views/type-of-claim.test.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:et-sya-pr-1933

#1996 cookie-slack-detector-issue
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-sya-pr-1996

#1980 RET-5661
  src/main/controllers/AddressDetailsController.ts
  src/main/controllers/AddressPostCodeEnterController.ts
  src/main/controllers/AddressPostCodeSelectController.ts
  src/main/controllers/RespondentPostCodeEnterController.ts
  src/main/controllers/RespondentPostCodeSelectController.ts
  src/main/controllers/WorkPostCodeEnterController.ts
  src/main/controllers/WorkPostCodeSelectController.ts
  src/main/controllers/helpers/AddressPostCodeHelper.ts
  src/main/controllers/helpers/CaseHelpers.ts
  src/main/controllers/helpers/RespondentPostCodeHelper.ts
  src/main/controllers/helpers/RespondentPostCodeSelectHelper.ts
  src/main/controllers/helpers/WorkPostCodeHelper.ts
  src/main/definitions/constants.ts
  src/main/views/address-postcode-select.njk
  src/main/views/form/fields/option.njk
  src/main/views/respondent-postcode-select.njk
  src/main/views/work-postcode-select.njk
  src/test/unit/controller/TribunalRespondToOrderController.test.ts
  src/test/unit/controller/helpers/AddressPostCodeHelper.test.ts
  src/test/unit/controller/helpers/RespondentPostCodeHelper.test.ts
  src/test/unit/controller/helpers/WorkPostCodeHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-1980
