Repository hmcts/et-sya-frontend, pull requests merged in 2025-08, with the labels that each got.

#2097 RET-5938
  src/main/controllers/citizen-hub/CitizenHubResponseFromRespondentController.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/constants.ts
  src/main/helper/ApiFormatter.ts
  src/main/views/response-from-respondent-view.njk
  src/test/unit/helper/ApiFormatter.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-sya-pr-2097

#2123 welsh translations noc
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/appoint-legal-representative.json
  src/main/resources/locales/cy/translation/citizen-hub.json
  src/main/resources/locales/cy/translation/contact-the-tribunal.json
  src/main/resources/locales/cy/translation/your-applications.json
Labels: ns:et, prd:et, aat/add-or-update, prod/no-changes, rel:et-sya-pr-2123

#2126 Ret 5801
  src/main/controllers/helpers/RouterHelpers.ts
  src/main/decorators/CaseStateCheck.ts
  src/main/definitions/constants.ts
  src/test/unit/utils/CollectionUtils.test.ts
  src/test/unit/utils/NumberUtils.test.ts
  src/test/unit/utils/StringUtils.test.ts
  src/test/unit/utils/UrlUtils.test.ts
Labels: ns:et, prd:et, rel:et-sya-pr-2126

#2117 RET-5488
  src/main/controllers/StoredToSubmitTribunalController.ts
  src/main/controllers/TribunalOrderOrRequestDetailsController.ts
  src/main/controllers/TribunalOrdersAndRequestsController.ts
  src/main/controllers/TribunalRespondToOrderController.ts
  src/main/controllers/citizen-hub/CitizenHubController.ts
  src/main/controllers/helpers/GeneralCorrespondenceHelper.ts
  src/main/controllers/helpers/TribunalOrderOrRequestDetailsHelper.ts
  src/main/controllers/helpers/TribunalOrderOrRequestsHelper.ts
  src/main/definitions/tribunal-notification.ts
  src/main/resources/locales/cy/translation/notifications.json
  src/main/resources/locales/en/translation/notifications.json
  src/main/views/notifications.njk
  src/test/unit/controller/TribunalOrdersAndRequestsController.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestDetailsHelper.test.ts
  src/test/unit/controller/helpers/TribunalOrderOrRequestsHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:et-sya-pr-2117
